#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
using System.Web.UI.WebControls;
namespace DevExpress.Web.Mvc {
	public class ImageZoomNavigatorSettings: SettingsBase {
		public ImageZoomNavigatorSettings() {
			Items = new ImageZoomNavigatorItemCollection();
			SettingsAutoGeneratedImages = new ImageZoomNavigatorAutoGeneratedImagesSettings(null);
			ItemSpacing = Unit.Pixel(5);
		}
		public ActiveItemChangeAction ActiveItemChangeAction { get; set; }
		public ClientSideEvents ClientSideEvents { get { return (ClientSideEvents)ClientSideEventsInternal; } }
		public ImageZoomNavigatorItemCollection Items { get; private set; }
		public Unit ItemSpacing { get; set; }
		public NavigationBarPagingMode PagingMode { get; set; }
		public Orientation Orientation { get; set; }
		public NavigationButtonVisibilityMode NavigationButtonVisibility { get; set; }
		public ImageZoomNavigatorAutoGeneratedImagesSettings SettingsAutoGeneratedImages { get; private set; }
		public int VisibleItemCount { get; set; }
		public string ImageContentBytesField { get; set; }
		public string ImageUrlField { get; set; }
		public string ThumbnailUrlField { get; set; }
		public string LargeImageUrlField { get; set; }
		public string ZoomWindowTextField { get; set; }
		public string ExpandWindowTextField { get; set; }
		public ImageZoomNavigatorStyles Styles { get { return (ImageZoomNavigatorStyles)StylesInternal; } }
		public ImageZoomNavigatorImages Images { get { return (ImageZoomNavigatorImages)ImagesInternal; } }
		public EventHandler DataBound { get; set; }
		public ImageZoomNavigatorItemEventHandler ItemDataBound { get; set; }
		protected override ClientSideEventsBase CreateClientSideEvents() {
			return new ClientSideEvents();
		}
		protected override ImagesBase CreateImages() {
			return new ImageZoomNavigatorImages(null);
		}
		protected override StylesBase CreateStyles() {
			return new ImageZoomNavigatorStyles(null);
		}
	}
}
