#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System.Web.Mvc;
namespace DevExpress.Web.Mvc {
	public class ImageZoomNavigatorExtension: ExtensionBase {
		public ImageZoomNavigatorExtension(ImageZoomNavigatorSettings settings)
			: base(settings) {
		}
		public ImageZoomNavigatorExtension(ImageZoomNavigatorSettings settings, ViewContext viewContext)
			: base(settings, viewContext) {
		}
		protected internal new ImageZoomNavigatorSettings Settings {
			get { return (ImageZoomNavigatorSettings)base.Settings; }
		}
		protected internal new MVCxImageZoomNavigator Control {
			get { return (MVCxImageZoomNavigator)base.Control; }
		}
		protected override void AssignInitialProperties() {
			base.AssignInitialProperties();
			Control.ActiveItemChangeAction = Settings.ActiveItemChangeAction;
			Control.ClientSideEvents.Assign(Settings.ClientSideEvents);
			Control.Items.Assign(Settings.Items);
			Control.ItemSpacing = Settings.ItemSpacing;
			Control.PagingMode = Settings.PagingMode;
			Control.Orientation = Settings.Orientation;
			Control.NavigationButtonVisibility= Settings.NavigationButtonVisibility;
			Control.SettingsAutoGeneratedImages.Assign(Settings.SettingsAutoGeneratedImages);
			Control.VisibleItemCount = Settings.VisibleItemCount;
			Control.ImageContentBytesField = Settings.ImageContentBytesField;
			Control.ImageUrlField = Settings.ImageUrlField;
			Control.ThumbnailUrlField = Settings.ThumbnailUrlField;
			Control.LargeImageUrlField = Settings.LargeImageUrlField;
			Control.ZoomWindowTextField = Settings.ZoomWindowTextField;
			Control.ExpandWindowTextField = Settings.ExpandWindowTextField;
			Control.Styles.CopyFrom(Settings.Styles);
			Control.Images.CopyFrom(Settings.Images);
			Control.DataBound += Settings.DataBound;
			Control.ItemDataBound += Settings.ItemDataBound;
		}
		public ImageZoomNavigatorExtension BindToFolder(string path) {
			Control.ImageSourceFolder = path;
			return this;
		}
		public ImageZoomNavigatorExtension Bind(object dataObject) {
			BindInternal(dataObject);
			return this;
		}
		public ImageZoomNavigatorExtension BindToXML(string fileName) {
			return BindToXML(fileName, string.Empty, string.Empty);
		}
		public ImageZoomNavigatorExtension BindToXML(string fileName, string xPath) {
			return BindToXML(fileName, xPath, string.Empty);
		}
		public ImageZoomNavigatorExtension BindToXML(string fileName, string xPath, string transformFileName) {
			BindToXMLInternal(fileName, xPath, transformFileName);
			return this;
		}
		protected override ASPxWebControl CreateControl() {
			return new MVCxImageZoomNavigator();
		}
	}
}
