#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using DevExpress.Design.SmartTags;
using DevExpress.Xpf.Core.Design;
using System;
using System.Collections.Generic;
using System.Linq;
namespace DevExpress.Xpf.Controls.Design.Features {
#pragma warning disable 612, 618
	sealed class BarCodeControlPropertyLineProvider : PropertyLinesProviderBase {
		public BarCodeControlPropertyLineProvider() : base(typeof(BarCodeControl)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.AutoModuleProperty)));
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.ShowTextProperty)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.ModuleProperty)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.TextProperty)));
			lines.Add(() => new ItemListPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.SymbologyProperty), typeof(SymbologyBase), BarCodeSymbologyDXTypeInfoInstanceSource.FromTypeList(BarCodeSymbologyStorage.GetSymbologyTypes())));
			lines.Add(() => new NestedPropertyLinesViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => BarCodeControl.SymbologyProperty)));
			return lines;
		}
	}
	class BarCodeSymbologyDXTypeInfoInstanceSource : DXTypeInfoInstanceSource {
		public new static IEnumerable<InstanceSourceBase> FromTypeList(IEnumerable<Type> types) {
			return types.Select(t => DXTypeInfo.FromType(t)).Select(dxt => new BarCodeSymbologyDXTypeInfoInstanceSource(dxt));
		}
		public BarCodeSymbologyDXTypeInfoInstanceSource(DXTypeInfo typeInfo) : base(typeInfo) {}
		public override string Name { get { return base.Name.Replace("Symbology", ""); } }
	}
	#region following propertylineproviders has been generated by DevExpress.Xpf.Controls.Tests.BarCodeSymbologyPropertyLineProvideGenerator.Generate()
	sealed class CodabarSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public CodabarSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.CodabarSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.CodabarSymbology.StartStopPairProperty), typeof(DevExpress.XtraPrinting.BarCode.CodabarStartStopPair)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.CodabarSymbology.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class Code11SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code11SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code11Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code128SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code128SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code128Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code39ExtendedSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code39ExtendedSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code39ExtendedSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code39SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code39SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code39Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code93ExtendedSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code93ExtendedSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code93ExtendedSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code93SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Code93SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code93Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class CodeMSISymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public CodeMSISymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.CodeMSISymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.CodeMSISymbology.MSICheckSumProperty), typeof(DevExpress.XtraPrinting.BarCode.MSICheckSum)));
			return lines;
		}
	}
	sealed class DataBarSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public DataBarSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.DataBarSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataBarSymbology.FNC1SubstituteProperty)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataBarSymbology.SegmentsInRowProperty)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataBarSymbology.TypeProperty), typeof(DevExpress.XtraPrinting.BarCode.DataBarType)));
			return lines;
		}
	}
	sealed class DataMatrixGS1SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public DataMatrixGS1SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.DataMatrixGS1Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataMatrixGS1Symbology.FNC1SubstituteProperty)));
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataMatrixGS1Symbology.HumanReadableTextProperty)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataMatrixGS1Symbology.MatrixSizeProperty), typeof(DevExpress.XtraPrinting.BarCode.DataMatrixSize)));
			return lines;
		}
	}
	sealed class DataMatrixSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public DataMatrixSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.DataMatrixSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataMatrixSymbology.CompactionModeProperty), typeof(DevExpress.XtraPrinting.BarCode.DataMatrixCompactionMode)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.DataMatrixSymbology.MatrixSizeProperty), typeof(DevExpress.XtraPrinting.BarCode.DataMatrixSize)));
			return lines;
		}
	}
	sealed class EAN128SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public EAN128SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.EAN128Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.EAN128Symbology.FNC1SubstituteProperty)));
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.EAN128Symbology.HumanReadableTextProperty)));
			return lines;
		}
	}
	sealed class EAN13SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public EAN13SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.EAN13Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class EAN8SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public EAN8SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.EAN8Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Industrial2of5SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Industrial2of5SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Industrial2of5Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class IntelligentMailSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public IntelligentMailSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.IntelligentMailSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Interleaved2of5SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Interleaved2of5SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Interleaved2of5Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class ITF14SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public ITF14SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.ITF14Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Matrix2of5SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public Matrix2of5SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Matrix2of5Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class PDF417SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public PDF417SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.PDF417Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.ColumnsProperty)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.CompactionModeProperty), typeof(DevExpress.XtraPrinting.BarCode.PDF417CompactionMode)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.ErrorCorrectionLevelProperty), typeof(DevExpress.XtraPrinting.BarCode.ErrorCorrectionLevel)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.RowsProperty)));
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.TruncateSymbolProperty)));
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.PDF417Symbology.YToXRatioProperty)));
			return lines;
		}
	}
	sealed class PostNetSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public PostNetSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.PostNetSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class QRCodeSymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public QRCodeSymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.QRCodeSymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.QRCodeSymbology.CompactionModeProperty), typeof(DevExpress.XtraPrinting.BarCode.QRCodeCompactionMode)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.QRCodeSymbology.ErrorCorrectionLevelProperty), typeof(DevExpress.XtraPrinting.BarCode.QRCodeErrorCorrectionLevel)));
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.QRCodeSymbology.VersionProperty), typeof(DevExpress.XtraPrinting.BarCode.QRCodeVersion)));
			return lines;
		}
	}
	sealed class UPCASymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public UPCASymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.UPCASymbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class UPCE0SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public UPCE0SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.UPCE0Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class UPCE1SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public UPCE1SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.UPCE1Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class UPCSupplemental2SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public UPCSupplemental2SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.UPCSupplemental2Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class UPCSupplemental5SymbologyPropertyLineProvider : PropertyLinesProviderBase {
		public UPCSupplemental5SymbologyPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.UPCSupplemental5Symbology)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			return lines;
		}
	}
	sealed class Code128SymbologyBaseCode128GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Code128SymbologyBaseCode128GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code128SymbologyBase<DevExpress.XtraPrinting.BarCode.Code128Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Code128SymbologyBase<DevExpress.XtraPrinting.BarCode.Code128Generator>.CharacterSetProperty), typeof(DevExpress.XtraPrinting.BarCode.Code128Charset)));
			return lines;
		}
	}
	sealed class Code39SymbologyBaseCode39ExtendedGeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Code39SymbologyBaseCode39ExtendedGeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code39SymbologyBase<DevExpress.XtraPrinting.BarCode.Code39ExtendedGenerator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Code39SymbologyBase<DevExpress.XtraPrinting.BarCode.Code39ExtendedGenerator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseCode39ExtendedGeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseCode39ExtendedGeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code39ExtendedGenerator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code39ExtendedGenerator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	sealed class Code39SymbologyBaseCode39GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Code39SymbologyBaseCode39GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code39SymbologyBase<DevExpress.XtraPrinting.BarCode.Code39Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Code39SymbologyBase<DevExpress.XtraPrinting.BarCode.Code39Generator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseCode39GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseCode39GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code39Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code39Generator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseCode93ExtendedGeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseCode93ExtendedGeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code93ExtendedGenerator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code93ExtendedGenerator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseCode93GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseCode93GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code93Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Code93Generator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	sealed class Code128SymbologyBaseEAN128GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Code128SymbologyBaseEAN128GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Code128SymbologyBase<DevExpress.XtraPrinting.BarCode.EAN128Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new EnumPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Code128SymbologyBase<DevExpress.XtraPrinting.BarCode.EAN128Generator>.CharacterSetProperty), typeof(DevExpress.XtraPrinting.BarCode.Code128Charset)));
			return lines;
		}
	}
	sealed class Industrial2of5SymbologyBaseIndustrial2of5GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Industrial2of5SymbologyBaseIndustrial2of5GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Industrial2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Industrial2of5Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Industrial2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Industrial2of5Generator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseIndustrial2of5GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseIndustrial2of5GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Industrial2of5Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Industrial2of5Generator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	sealed class Interleaved2of5SymbologyBaseInterleaved2of5GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Interleaved2of5SymbologyBaseInterleaved2of5GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Interleaved2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Interleaved2of5Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Interleaved2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Interleaved2of5Generator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class Interleaved2of5SymbologyBaseITF14GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Interleaved2of5SymbologyBaseITF14GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Interleaved2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.ITF14Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Interleaved2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.ITF14Generator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class Industrial2of5SymbologyBaseMatrix2of5GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public Industrial2of5SymbologyBaseMatrix2of5GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.Industrial2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Matrix2of5Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new ObjectPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.Industrial2of5SymbologyBase<DevExpress.XtraPrinting.BarCode.Matrix2of5Generator>.WideNarrowRatioProperty)));
			return lines;
		}
	}
	sealed class SymbologyCheckSumBaseMatrix2of5GeneratorPropertyLineProvider : PropertyLinesProviderBase {
		public SymbologyCheckSumBaseMatrix2of5GeneratorPropertyLineProvider() : base(typeof(DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Matrix2of5Generator>)) { }
		protected override SmartTagLineViewModelFactoryList GetPropertiesImpl(FrameworkElementSmartTagPropertiesViewModel viewModel) {
			SmartTagLineViewModelFactoryList lines = base.GetPropertiesImpl(viewModel);
			lines.Add(() => new BooleanPropertyLineViewModel(viewModel, DependencyPropertyHelper.GetPropertyName(() => DevExpress.Xpf.Controls.SymbologyCheckSumBase<DevExpress.XtraPrinting.BarCode.Matrix2of5Generator>.CalcCheckSumProperty)));
			return lines;
		}
	}
	#endregion
#pragma warning restore 612, 618
}
