#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{       Dashboard                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
using System.Collections.Generic;
using System.Drawing;
using DevExpress.DashboardCommon;
using DevExpress.DashboardCommon.Native;
using DevExpress.DashboardCommon.ViewModel;
using DevExpress.DashboardWin.Localization;
namespace DevExpress.DashboardWin.Native {
	class FormatRuleGradientRangeBarControlPresenter : FormatRuleRangeGradientControlPresenter {
		protected override string Caption {
			get { return DashboardWinLocalizer.GetString(DashboardWinStringId.CommandFormatRuleGradientRangeBar); }
		}
		protected override string DescriptionFormat {
			get { return DashboardWinLocalizer.GetString(DashboardWinStringId.CommandFormatRuleGradientRangeBarDescription); }
		}
		protected override bool IsApplyToReadOnly { get { return true; } }
		protected override bool IsApplyToColumnSupported { get { return false; } }
		IFormatRuleControlBarOptionsView SpecificView { get { return (IFormatRuleControlBarOptionsView)base.View; } }
		FormatConditionGradientRangeBar SpecificCondition {
			get { return (FormatConditionGradientRangeBar)base.Rule.Condition; }
			set { base.Rule.Condition = value; }
		}
		FormatConditionBarOptions BarOptions { get { return SpecificCondition.BarOptions; } }
		public FormatRuleGradientRangeBarControlPresenter(IServiceProvider serviceProvider, DataDashboardItem dashboardItem, DataItem dataItem, DashboardItemFormatRule initialFormatRule)
			: base(serviceProvider, dashboardItem, dataItem, initialFormatRule) {
		}
		public FormatRuleGradientRangeBarControlPresenter(IServiceProvider serviceProvider, DataDashboardItem dashboardItem, DataItem dataItem, FormatConditionRangeGradientPredefinedType type)
			: base(serviceProvider, dashboardItem, dataItem, type) {
		}
		protected override void CreateCondition(FormatRuleRangeGradientViewGeneratingEventArgs e, Dictionary<int, StyleSettingsBase> customStyles, int oldCount) {
			SpecificCondition = new FormatConditionGradientRangeBar(customStyles[0], customStyles[oldCount - 1], e.Count);
		}
		protected override void CreateCondition(FormatConditionRangeGradientPredefinedType type, DashboardFormatConditionValueType valueType) {
			SpecificCondition = new FormatConditionGradientRangeBar(type) { ValueType = valueType };
		}
		protected override IStyleSettings PrepareAutoGeneratedAppearance(RangeInfo range) {
			int index = ((RangeIndexSettings)range.ActualStyleSettings).Index;
			ConditionModel gradientModel = SpecificCondition.CreateModel();
			Color backColor = FormatConditionalStyleSettingsProvider.GetBackColor(index, gradientModel, IsDarkSkin, StyleSettingsContainerPainter.GetDefaultBackColor(LookAndFeel));
			return new BarStyleSettings(backColor);
		}
		protected override StyleMode GetRangeStyleMode(int rangeIndex) {
			if(rangeIndex == 0 || rangeIndex == SpecificCondition.RangeSet.Count - 1) {
				return StyleMode.BarGradientNonemptyStop;
			}
			else
				return SpecificCondition.SortedRanges[rangeIndex].StyleSettings == null ? StyleMode.BarGradientGenerated : StyleMode.BarGradientStop;
		}
		protected override IStyleSettings GetStyleSettings(RangeInfo range, StyleMode styleMode) {
			IStyleSettings styleSettings = styleMode == StyleMode.BarGradientGenerated ? PrepareAutoGeneratedAppearance(range) : range.ActualStyleSettings;
			return styleSettings;
		}
		protected override FormatRuleControlViewInitializationContext CreateViewInitializationContext() {
			Dimension dimension = DataItem as Dimension;
			FormatRuleViewGradientRangeBarContext context = new FormatRuleViewGradientRangeBarContext() {
				PredefinedType = SpecificCondition.ActualPredefinedType,
				DataType = DataItem.ActualDataFieldType,
				DateTimeGroupInterval = dimension != null ? dimension.DateTimeGroupInterval : DateTimeGroupInterval.None,
				IsPercentsSupported = IsPercentsSupported
			};
			IFormatRuleBarOptionsInitializationContext contextBarOptions = context.BarOptions;
			FormatConditionBarOptions barOptions = SpecificCondition.BarOptions;
			contextBarOptions.AllowNegativeAxis = barOptions.AllowNegativeAxis;
			contextBarOptions.DrawAxis = barOptions.DrawAxis;
			contextBarOptions.ShowBarOnly = barOptions.ShowBarOnly;
			return context;
		}
		protected override void ApplyView() {
			base.ApplyView();
			SpecificCondition.BarOptions.AllowNegativeAxis = SpecificView.BarOptions.AllowNegativeAxis;
			SpecificCondition.BarOptions.DrawAxis = SpecificView.BarOptions.DrawAxis;
			SpecificCondition.BarOptions.ShowBarOnly = SpecificView.BarOptions.ShowBarOnly;
		}
	}
}
