#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

namespace DevExpress.XtraCharts.Designer.Native {
	partial class SmartBindingForm {
		private System.ComponentModel.IContainer components = null;
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		#region Windows Form Designer generated code
		private void InitializeComponent() {
			this.comboBoxEdit1 = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblDataSource = new DevExpress.XtraEditors.LabelControl();
			this.cbChartDataMember = new DevExpress.XtraEditors.PopupContainerEdit();
			this.cbSeriesViewType = new DevExpress.XtraEditors.ImageComboBoxEdit();
			this.cbSeriesDataMember = new DevExpress.XtraEditors.PopupContainerEdit();
			this.popupContainerEdit1 = new DevExpress.XtraEditors.PopupContainerEdit();
			this.txtEndText = new DevExpress.XtraEditors.TextEdit();
			this.grSeriesProperties = new DevExpress.XtraEditors.GroupControl();
			this.grFamiliarDataSourceOptions = new DevExpress.XtraEditors.GroupControl();
			this.cheAutoLayoutSettings = new DevExpress.XtraEditors.CheckEdit();
			this.cheAutoBindingSettings = new DevExpress.XtraEditors.CheckEdit();
			this.grSort = new DevExpress.XtraEditors.GroupControl();
			this.grArgumentSettings = new DevExpress.XtraEditors.GroupControl();
			this.grValueSettings = new DevExpress.XtraEditors.GroupControl();
			this.grColorSettings = new DevExpress.XtraEditors.GroupControl();
			this.chartPanelControl3 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbColor = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblColor = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlSummaryFunction = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.beSummaryFunction = new DevExpress.XtraEditors.ButtonEdit();
			this.lblSummaryFunction = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlValue4 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbValue4 = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblValue4 = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblDockOffset4 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlValue3 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbValue3 = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblValue3 = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblDockOffset3 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlValue2 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbValue2 = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblValue2 = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblDockOffset2 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlValue1 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbValue1 = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblValue1 = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.chartPanelControl1 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlBindingMode = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbBindingMode = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblBindingMode = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblDockOffset1 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlValueScaleType = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbValueScaleType = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblValueScaleType = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlArgument = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbArgument = new DevExpress.XtraEditors.PopupContainerEdit();
			this.lblArgument = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlArgumentSplitter = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlArgumentScaleType = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbArgumentScaleType = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblArgumentScaleType = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.chartPanelControl2 = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlDataFilters = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.beFilters = new DevExpress.XtraEditors.ButtonEdit();
			this.lblDataFilters = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlDataFiltersSplitter = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlSortBy = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbPointSortingKey = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblSortBy = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlSortungSplitter = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlPointSortOrder = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbPointSorting = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblPointSortOrder = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.pnlSortOrderSplitter = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.pnlSeriesSortOrder = new DevExpress.XtraCharts.Wizard.ChartPanelControl();
			this.cbSeriesSorting = new DevExpress.XtraEditors.ComboBoxEdit();
			this.lblSeriesSortOrder = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblNameSuffix = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblDataMember = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.chartLabelControl1 = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblViewType = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.lblSeries = new DevExpress.XtraCharts.Wizard.ChartLabelControl();
			this.btnOK = new DevExpress.XtraEditors.SimpleButton();
			this.btnCancel = new DevExpress.XtraEditors.SimpleButton();
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cbChartDataMember.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesViewType.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesDataMember.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.popupContainerEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.txtEndText.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grSeriesProperties)).BeginInit();
			this.grSeriesProperties.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grFamiliarDataSourceOptions)).BeginInit();
			this.grFamiliarDataSourceOptions.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cheAutoLayoutSettings.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cheAutoBindingSettings.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grSort)).BeginInit();
			this.grSort.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grArgumentSettings)).BeginInit();
			this.grArgumentSettings.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grValueSettings)).BeginInit();
			this.grValueSettings.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grColorSettings)).BeginInit();
			this.grColorSettings.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl3)).BeginInit();
			this.chartPanelControl3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbColor.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSummaryFunction)).BeginInit();
			this.pnlSummaryFunction.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.beSummaryFunction.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue4)).BeginInit();
			this.pnlValue4.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbValue4.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue3)).BeginInit();
			this.pnlValue3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbValue3.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue2)).BeginInit();
			this.pnlValue2.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbValue2.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue1)).BeginInit();
			this.pnlValue1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbValue1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlBindingMode)).BeginInit();
			this.pnlBindingMode.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbBindingMode.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValueScaleType)).BeginInit();
			this.pnlValueScaleType.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbValueScaleType.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgument)).BeginInit();
			this.pnlArgument.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbArgument.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgumentSplitter)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgumentScaleType)).BeginInit();
			this.pnlArgumentScaleType.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbArgumentScaleType.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlDataFilters)).BeginInit();
			this.pnlDataFilters.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.beFilters.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlDataFiltersSplitter)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortBy)).BeginInit();
			this.pnlSortBy.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbPointSortingKey.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortungSplitter)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlPointSortOrder)).BeginInit();
			this.pnlPointSortOrder.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbPointSorting.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortOrderSplitter)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSeriesSortOrder)).BeginInit();
			this.pnlSeriesSortOrder.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesSorting.Properties)).BeginInit();
			this.SuspendLayout();
			this.comboBoxEdit1.EditValue = "(none)";
			this.comboBoxEdit1.Location = new System.Drawing.Point(129, 34);
			this.comboBoxEdit1.Name = "comboBoxEdit1";
			this.comboBoxEdit1.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.comboBoxEdit1.Size = new System.Drawing.Size(173, 20);
			this.comboBoxEdit1.TabIndex = 0;
			this.lblDataSource.Location = new System.Drawing.Point(9, 37);
			this.lblDataSource.Name = "lblDataSource";
			this.lblDataSource.Size = new System.Drawing.Size(106, 13);
			this.lblDataSource.TabIndex = 1;
			this.lblDataSource.Text = "Choose a datasource:";
			this.cbChartDataMember.EditValue = "";
			this.cbChartDataMember.EnterMoveNextControl = true;
			this.cbChartDataMember.Location = new System.Drawing.Point(129, 60);
			this.cbChartDataMember.Name = "cbChartDataMember";
			this.cbChartDataMember.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbChartDataMember.Size = new System.Drawing.Size(173, 20);
			this.cbChartDataMember.TabIndex = 67;
			this.cbSeriesViewType.EditValue = "Numerical";
			this.cbSeriesViewType.EnterMoveNextControl = true;
			this.cbSeriesViewType.Location = new System.Drawing.Point(129, 86);
			this.cbSeriesViewType.Name = "cbSeriesViewType";
			this.cbSeriesViewType.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbSeriesViewType.Properties.Sorted = true;
			this.cbSeriesViewType.Size = new System.Drawing.Size(173, 20);
			this.cbSeriesViewType.TabIndex = 68;
			this.cbSeriesDataMember.EditValue = "";
			this.cbSeriesDataMember.EnterMoveNextControl = true;
			this.cbSeriesDataMember.Location = new System.Drawing.Point(129, 112);
			this.cbSeriesDataMember.Name = "cbSeriesDataMember";
			this.cbSeriesDataMember.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbSeriesDataMember.Size = new System.Drawing.Size(173, 20);
			this.cbSeriesDataMember.TabIndex = 70;
			this.popupContainerEdit1.EditValue = "";
			this.popupContainerEdit1.EnterMoveNextControl = true;
			this.popupContainerEdit1.Location = new System.Drawing.Point(129, 138);
			this.popupContainerEdit1.Name = "popupContainerEdit1";
			this.popupContainerEdit1.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.popupContainerEdit1.Size = new System.Drawing.Size(173, 20);
			this.popupContainerEdit1.TabIndex = 72;
			this.txtEndText.Location = new System.Drawing.Point(129, 164);
			this.txtEndText.Name = "txtEndText";
			this.txtEndText.Size = new System.Drawing.Size(173, 20);
			this.txtEndText.TabIndex = 74;
			this.grSeriesProperties.AutoSize = true;
			this.grSeriesProperties.Controls.Add(this.comboBoxEdit1);
			this.grSeriesProperties.Controls.Add(this.txtEndText);
			this.grSeriesProperties.Controls.Add(this.lblDataSource);
			this.grSeriesProperties.Controls.Add(this.lblNameSuffix);
			this.grSeriesProperties.Controls.Add(this.lblDataMember);
			this.grSeriesProperties.Controls.Add(this.popupContainerEdit1);
			this.grSeriesProperties.Controls.Add(this.cbChartDataMember);
			this.grSeriesProperties.Controls.Add(this.chartLabelControl1);
			this.grSeriesProperties.Controls.Add(this.lblViewType);
			this.grSeriesProperties.Controls.Add(this.cbSeriesDataMember);
			this.grSeriesProperties.Controls.Add(this.cbSeriesViewType);
			this.grSeriesProperties.Controls.Add(this.lblSeries);
			this.grSeriesProperties.Location = new System.Drawing.Point(12, 12);
			this.grSeriesProperties.Name = "grSeriesProperties";
			this.grSeriesProperties.Padding = new System.Windows.Forms.Padding(10);
			this.grSeriesProperties.Size = new System.Drawing.Size(317, 199);
			this.grSeriesProperties.TabIndex = 76;
			this.grSeriesProperties.Text = "Series Properties";
			this.grFamiliarDataSourceOptions.AutoSize = true;
			this.grFamiliarDataSourceOptions.Controls.Add(this.cheAutoLayoutSettings);
			this.grFamiliarDataSourceOptions.Controls.Add(this.chartPanelControl2);
			this.grFamiliarDataSourceOptions.Controls.Add(this.cheAutoBindingSettings);
			this.grFamiliarDataSourceOptions.Location = new System.Drawing.Point(12, 360);
			this.grFamiliarDataSourceOptions.Name = "grFamiliarDataSourceOptions";
			this.grFamiliarDataSourceOptions.Padding = new System.Windows.Forms.Padding(10);
			this.grFamiliarDataSourceOptions.Size = new System.Drawing.Size(317, 87);
			this.grFamiliarDataSourceOptions.TabIndex = 78;
			this.grFamiliarDataSourceOptions.Text = "Familiar Data Source Options";
			this.cheAutoLayoutSettings.Dock = System.Windows.Forms.DockStyle.Top;
			this.cheAutoLayoutSettings.Location = new System.Drawing.Point(12, 56);
			this.cheAutoLayoutSettings.Name = "cheAutoLayoutSettings";
			this.cheAutoLayoutSettings.Properties.Caption = "Automatic Layout Settings";
			this.cheAutoLayoutSettings.Size = new System.Drawing.Size(293, 19);
			this.cheAutoLayoutSettings.TabIndex = 1;
			this.cheAutoBindingSettings.Dock = System.Windows.Forms.DockStyle.Top;
			this.cheAutoBindingSettings.Location = new System.Drawing.Point(12, 31);
			this.cheAutoBindingSettings.Name = "cheAutoBindingSettings";
			this.cheAutoBindingSettings.Properties.Caption = "Automatic Binding Settings";
			this.cheAutoBindingSettings.Size = new System.Drawing.Size(293, 19);
			this.cheAutoBindingSettings.TabIndex = 0;
			this.grSort.AutoSize = true;
			this.grSort.Controls.Add(this.pnlDataFilters);
			this.grSort.Controls.Add(this.pnlDataFiltersSplitter);
			this.grSort.Controls.Add(this.pnlSortBy);
			this.grSort.Controls.Add(this.pnlSortungSplitter);
			this.grSort.Controls.Add(this.pnlPointSortOrder);
			this.grSort.Controls.Add(this.pnlSortOrderSplitter);
			this.grSort.Controls.Add(this.pnlSeriesSortOrder);
			this.grSort.Location = new System.Drawing.Point(12, 217);
			this.grSort.Name = "grSort";
			this.grSort.Padding = new System.Windows.Forms.Padding(10);
			this.grSort.Size = new System.Drawing.Size(317, 143);
			this.grSort.TabIndex = 77;
			this.grSort.Text = "Sorting && Filtering";
			this.grArgumentSettings.AutoSize = true;
			this.grArgumentSettings.Controls.Add(this.pnlArgument);
			this.grArgumentSettings.Controls.Add(this.pnlArgumentSplitter);
			this.grArgumentSettings.Controls.Add(this.pnlArgumentScaleType);
			this.grArgumentSettings.Location = new System.Drawing.Point(335, 12);
			this.grArgumentSettings.Name = "grArgumentSettings";
			this.grArgumentSettings.Padding = new System.Windows.Forms.Padding(10);
			this.grArgumentSettings.Size = new System.Drawing.Size(341, 87);
			this.grArgumentSettings.TabIndex = 79;
			this.grArgumentSettings.Text = "Argument Properties";
			this.grValueSettings.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.grValueSettings.Controls.Add(this.pnlSummaryFunction);
			this.grValueSettings.Controls.Add(this.pnlValue4);
			this.grValueSettings.Controls.Add(this.lblDockOffset4);
			this.grValueSettings.Controls.Add(this.pnlValue3);
			this.grValueSettings.Controls.Add(this.lblDockOffset3);
			this.grValueSettings.Controls.Add(this.pnlValue2);
			this.grValueSettings.Controls.Add(this.lblDockOffset2);
			this.grValueSettings.Controls.Add(this.pnlValue1);
			this.grValueSettings.Controls.Add(this.chartPanelControl1);
			this.grValueSettings.Controls.Add(this.pnlBindingMode);
			this.grValueSettings.Controls.Add(this.lblDockOffset1);
			this.grValueSettings.Controls.Add(this.pnlValueScaleType);
			this.grValueSettings.Location = new System.Drawing.Point(335, 105);
			this.grValueSettings.Name = "grValueSettings";
			this.grValueSettings.Padding = new System.Windows.Forms.Padding(10);
			this.grValueSettings.Size = new System.Drawing.Size(341, 201);
			this.grValueSettings.TabIndex = 80;
			this.grValueSettings.Text = "Value Properties";
			this.grColorSettings.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.grColorSettings.Controls.Add(this.chartPanelControl3);
			this.grColorSettings.Location = new System.Drawing.Point(335, 312);
			this.grColorSettings.Name = "grColorSettings";
			this.grColorSettings.Padding = new System.Windows.Forms.Padding(10);
			this.grColorSettings.Size = new System.Drawing.Size(341, 63);
			this.grColorSettings.TabIndex = 81;
			this.grColorSettings.Text = "Color Properties";
			this.chartPanelControl3.AutoSize = true;
			this.chartPanelControl3.BackColor = System.Drawing.Color.Transparent;
			this.chartPanelControl3.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.chartPanelControl3.Controls.Add(this.cbColor);
			this.chartPanelControl3.Controls.Add(this.lblColor);
			this.chartPanelControl3.Dock = System.Windows.Forms.DockStyle.Top;
			this.chartPanelControl3.Location = new System.Drawing.Point(12, 31);
			this.chartPanelControl3.Name = "chartPanelControl3";
			this.chartPanelControl3.Size = new System.Drawing.Size(317, 20);
			this.chartPanelControl3.TabIndex = 3;
			this.cbColor.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbColor.EditValue = "";
			this.cbColor.EnterMoveNextControl = true;
			this.cbColor.Location = new System.Drawing.Point(110, 0);
			this.cbColor.Name = "cbColor";
			this.cbColor.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbColor.Size = new System.Drawing.Size(207, 20);
			this.cbColor.TabIndex = 0;
			this.lblColor.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblColor.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblColor.Location = new System.Drawing.Point(0, 0);
			this.lblColor.Name = "lblColor";
			this.lblColor.Size = new System.Drawing.Size(110, 20);
			this.lblColor.TabIndex = 0;
			this.lblColor.Text = "Color:";
			this.pnlSummaryFunction.AutoSize = true;
			this.pnlSummaryFunction.BackColor = System.Drawing.Color.Transparent;
			this.pnlSummaryFunction.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlSummaryFunction.Controls.Add(this.beSummaryFunction);
			this.pnlSummaryFunction.Controls.Add(this.lblSummaryFunction);
			this.pnlSummaryFunction.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlSummaryFunction.Location = new System.Drawing.Point(12, 171);
			this.pnlSummaryFunction.Name = "pnlSummaryFunction";
			this.pnlSummaryFunction.Size = new System.Drawing.Size(317, 20);
			this.pnlSummaryFunction.TabIndex = 7;
			this.beSummaryFunction.Dock = System.Windows.Forms.DockStyle.Top;
			this.beSummaryFunction.Location = new System.Drawing.Point(110, 0);
			this.beSummaryFunction.Name = "beSummaryFunction";
			this.beSummaryFunction.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton()});
			this.beSummaryFunction.Properties.ValidateOnEnterKey = true;
			this.beSummaryFunction.Size = new System.Drawing.Size(207, 20);
			this.beSummaryFunction.TabIndex = 0;
			this.lblSummaryFunction.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblSummaryFunction.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblSummaryFunction.Location = new System.Drawing.Point(0, 0);
			this.lblSummaryFunction.Name = "lblSummaryFunction";
			this.lblSummaryFunction.Size = new System.Drawing.Size(110, 20);
			this.lblSummaryFunction.TabIndex = 0;
			this.lblSummaryFunction.Text = "Summary function:";
			this.pnlValue4.AutoSize = true;
			this.pnlValue4.BackColor = System.Drawing.Color.Transparent;
			this.pnlValue4.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlValue4.Controls.Add(this.cbValue4);
			this.pnlValue4.Controls.Add(this.lblValue4);
			this.pnlValue4.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlValue4.Location = new System.Drawing.Point(12, 151);
			this.pnlValue4.Name = "pnlValue4";
			this.pnlValue4.Size = new System.Drawing.Size(317, 20);
			this.pnlValue4.TabIndex = 6;
			this.cbValue4.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbValue4.EditValue = "";
			this.cbValue4.EnterMoveNextControl = true;
			this.cbValue4.Location = new System.Drawing.Point(110, 0);
			this.cbValue4.Name = "cbValue4";
			this.cbValue4.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbValue4.Size = new System.Drawing.Size(207, 20);
			this.cbValue4.TabIndex = 0;
			this.lblValue4.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblValue4.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblValue4.Location = new System.Drawing.Point(0, 0);
			this.lblValue4.Name = "lblValue4";
			this.lblValue4.Size = new System.Drawing.Size(110, 20);
			this.lblValue4.TabIndex = 0;
			this.lblValue4.Text = "Value:";
			this.lblDockOffset4.BackColor = System.Drawing.Color.Transparent;
			this.lblDockOffset4.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.lblDockOffset4.Dock = System.Windows.Forms.DockStyle.Top;
			this.lblDockOffset4.Location = new System.Drawing.Point(12, 147);
			this.lblDockOffset4.Name = "lblDockOffset4";
			this.lblDockOffset4.Size = new System.Drawing.Size(317, 4);
			this.lblDockOffset4.TabIndex = 101;
			this.pnlValue3.AutoSize = true;
			this.pnlValue3.BackColor = System.Drawing.Color.Transparent;
			this.pnlValue3.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlValue3.Controls.Add(this.cbValue3);
			this.pnlValue3.Controls.Add(this.lblValue3);
			this.pnlValue3.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlValue3.Location = new System.Drawing.Point(12, 127);
			this.pnlValue3.Name = "pnlValue3";
			this.pnlValue3.Size = new System.Drawing.Size(317, 20);
			this.pnlValue3.TabIndex = 5;
			this.cbValue3.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbValue3.EditValue = "";
			this.cbValue3.EnterMoveNextControl = true;
			this.cbValue3.Location = new System.Drawing.Point(110, 0);
			this.cbValue3.Name = "cbValue3";
			this.cbValue3.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbValue3.Size = new System.Drawing.Size(207, 20);
			this.cbValue3.TabIndex = 0;
			this.lblValue3.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblValue3.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblValue3.Location = new System.Drawing.Point(0, 0);
			this.lblValue3.Name = "lblValue3";
			this.lblValue3.Size = new System.Drawing.Size(110, 20);
			this.lblValue3.TabIndex = 0;
			this.lblValue3.Text = "Value:";
			this.lblDockOffset3.BackColor = System.Drawing.Color.Transparent;
			this.lblDockOffset3.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.lblDockOffset3.Dock = System.Windows.Forms.DockStyle.Top;
			this.lblDockOffset3.Location = new System.Drawing.Point(12, 123);
			this.lblDockOffset3.Name = "lblDockOffset3";
			this.lblDockOffset3.Size = new System.Drawing.Size(317, 4);
			this.lblDockOffset3.TabIndex = 99;
			this.pnlValue2.AutoSize = true;
			this.pnlValue2.BackColor = System.Drawing.Color.Transparent;
			this.pnlValue2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlValue2.Controls.Add(this.cbValue2);
			this.pnlValue2.Controls.Add(this.lblValue2);
			this.pnlValue2.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlValue2.Location = new System.Drawing.Point(12, 103);
			this.pnlValue2.Name = "pnlValue2";
			this.pnlValue2.Size = new System.Drawing.Size(317, 20);
			this.pnlValue2.TabIndex = 4;
			this.cbValue2.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbValue2.EditValue = "";
			this.cbValue2.EnterMoveNextControl = true;
			this.cbValue2.Location = new System.Drawing.Point(110, 0);
			this.cbValue2.Name = "cbValue2";
			this.cbValue2.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbValue2.Size = new System.Drawing.Size(207, 20);
			this.cbValue2.TabIndex = 0;
			this.lblValue2.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblValue2.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblValue2.Location = new System.Drawing.Point(0, 0);
			this.lblValue2.Name = "lblValue2";
			this.lblValue2.Size = new System.Drawing.Size(110, 20);
			this.lblValue2.TabIndex = 0;
			this.lblValue2.Text = "Value:";
			this.lblDockOffset2.BackColor = System.Drawing.Color.Transparent;
			this.lblDockOffset2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.lblDockOffset2.Dock = System.Windows.Forms.DockStyle.Top;
			this.lblDockOffset2.Location = new System.Drawing.Point(12, 99);
			this.lblDockOffset2.Name = "lblDockOffset2";
			this.lblDockOffset2.Size = new System.Drawing.Size(317, 4);
			this.lblDockOffset2.TabIndex = 97;
			this.pnlValue1.AutoSize = true;
			this.pnlValue1.BackColor = System.Drawing.Color.Transparent;
			this.pnlValue1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlValue1.Controls.Add(this.cbValue1);
			this.pnlValue1.Controls.Add(this.lblValue1);
			this.pnlValue1.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlValue1.Location = new System.Drawing.Point(12, 79);
			this.pnlValue1.Name = "pnlValue1";
			this.pnlValue1.Size = new System.Drawing.Size(317, 20);
			this.pnlValue1.TabIndex = 3;
			this.cbValue1.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbValue1.EditValue = "";
			this.cbValue1.EnterMoveNextControl = true;
			this.cbValue1.Location = new System.Drawing.Point(110, 0);
			this.cbValue1.Name = "cbValue1";
			this.cbValue1.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbValue1.Size = new System.Drawing.Size(207, 20);
			this.cbValue1.TabIndex = 0;
			this.lblValue1.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblValue1.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblValue1.Location = new System.Drawing.Point(0, 0);
			this.lblValue1.Name = "lblValue1";
			this.lblValue1.Size = new System.Drawing.Size(110, 20);
			this.lblValue1.TabIndex = 0;
			this.lblValue1.Text = "Value:";
			this.chartPanelControl1.BackColor = System.Drawing.Color.Transparent;
			this.chartPanelControl1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.chartPanelControl1.Dock = System.Windows.Forms.DockStyle.Top;
			this.chartPanelControl1.Location = new System.Drawing.Point(12, 75);
			this.chartPanelControl1.Name = "chartPanelControl1";
			this.chartPanelControl1.Size = new System.Drawing.Size(317, 4);
			this.chartPanelControl1.TabIndex = 103;
			this.pnlBindingMode.AutoSize = true;
			this.pnlBindingMode.BackColor = System.Drawing.Color.Transparent;
			this.pnlBindingMode.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlBindingMode.Controls.Add(this.cbBindingMode);
			this.pnlBindingMode.Controls.Add(this.lblBindingMode);
			this.pnlBindingMode.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlBindingMode.Location = new System.Drawing.Point(12, 55);
			this.pnlBindingMode.Name = "pnlBindingMode";
			this.pnlBindingMode.Size = new System.Drawing.Size(317, 20);
			this.pnlBindingMode.TabIndex = 2;
			this.cbBindingMode.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbBindingMode.EditValue = "Values";
			this.cbBindingMode.EnterMoveNextControl = true;
			this.cbBindingMode.Location = new System.Drawing.Point(110, 0);
			this.cbBindingMode.Name = "cbBindingMode";
			this.cbBindingMode.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbBindingMode.Properties.Items.AddRange(new object[] {
			"Values",
			"Summary Function"});
			this.cbBindingMode.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbBindingMode.Properties.SelectedIndexChanged += new System.EventHandler(this.cbBindingMode_SelectedIndexChanged);
			this.cbBindingMode.Size = new System.Drawing.Size(207, 20);
			this.cbBindingMode.TabIndex = 0;
			this.lblBindingMode.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblBindingMode.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblBindingMode.Location = new System.Drawing.Point(0, 0);
			this.lblBindingMode.Name = "lblBindingMode";
			this.lblBindingMode.Size = new System.Drawing.Size(110, 20);
			this.lblBindingMode.TabIndex = 0;
			this.lblBindingMode.Text = "Binding mode:";
			this.lblDockOffset1.BackColor = System.Drawing.Color.Transparent;
			this.lblDockOffset1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.lblDockOffset1.Dock = System.Windows.Forms.DockStyle.Top;
			this.lblDockOffset1.Location = new System.Drawing.Point(12, 51);
			this.lblDockOffset1.Name = "lblDockOffset1";
			this.lblDockOffset1.Size = new System.Drawing.Size(317, 4);
			this.lblDockOffset1.TabIndex = 95;
			this.pnlValueScaleType.AutoSize = true;
			this.pnlValueScaleType.BackColor = System.Drawing.Color.Transparent;
			this.pnlValueScaleType.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlValueScaleType.Controls.Add(this.cbValueScaleType);
			this.pnlValueScaleType.Controls.Add(this.lblValueScaleType);
			this.pnlValueScaleType.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlValueScaleType.Location = new System.Drawing.Point(12, 31);
			this.pnlValueScaleType.Name = "pnlValueScaleType";
			this.pnlValueScaleType.Size = new System.Drawing.Size(317, 20);
			this.pnlValueScaleType.TabIndex = 1;
			this.cbValueScaleType.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbValueScaleType.EditValue = "Numerical";
			this.cbValueScaleType.EnterMoveNextControl = true;
			this.cbValueScaleType.Location = new System.Drawing.Point(110, 0);
			this.cbValueScaleType.Name = "cbValueScaleType";
			this.cbValueScaleType.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbValueScaleType.Properties.Items.AddRange(new object[] {
			"Numerical",
			"DateTime"});
			this.cbValueScaleType.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbValueScaleType.Size = new System.Drawing.Size(207, 20);
			this.cbValueScaleType.TabIndex = 0;
			this.lblValueScaleType.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblValueScaleType.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblValueScaleType.Location = new System.Drawing.Point(0, 0);
			this.lblValueScaleType.Name = "lblValueScaleType";
			this.lblValueScaleType.Size = new System.Drawing.Size(110, 20);
			this.lblValueScaleType.TabIndex = 0;
			this.lblValueScaleType.Text = "Value scale type:";
			this.pnlArgument.AutoSize = true;
			this.pnlArgument.BackColor = System.Drawing.Color.Transparent;
			this.pnlArgument.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlArgument.Controls.Add(this.cbArgument);
			this.pnlArgument.Controls.Add(this.lblArgument);
			this.pnlArgument.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlArgument.Location = new System.Drawing.Point(12, 55);
			this.pnlArgument.Name = "pnlArgument";
			this.pnlArgument.Size = new System.Drawing.Size(317, 20);
			this.pnlArgument.TabIndex = 3;
			this.cbArgument.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbArgument.EditValue = "";
			this.cbArgument.EnterMoveNextControl = true;
			this.cbArgument.Location = new System.Drawing.Point(110, 0);
			this.cbArgument.Name = "cbArgument";
			this.cbArgument.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbArgument.Size = new System.Drawing.Size(207, 20);
			this.cbArgument.TabIndex = 0;
			this.lblArgument.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblArgument.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblArgument.Location = new System.Drawing.Point(0, 0);
			this.lblArgument.Name = "lblArgument";
			this.lblArgument.Size = new System.Drawing.Size(110, 20);
			this.lblArgument.TabIndex = 0;
			this.lblArgument.Text = "Argument:";
			this.pnlArgumentSplitter.BackColor = System.Drawing.Color.Transparent;
			this.pnlArgumentSplitter.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlArgumentSplitter.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlArgumentSplitter.Location = new System.Drawing.Point(12, 51);
			this.pnlArgumentSplitter.Name = "pnlArgumentSplitter";
			this.pnlArgumentSplitter.Size = new System.Drawing.Size(317, 4);
			this.pnlArgumentSplitter.TabIndex = 92;
			this.pnlArgumentScaleType.AutoSize = true;
			this.pnlArgumentScaleType.BackColor = System.Drawing.Color.Transparent;
			this.pnlArgumentScaleType.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlArgumentScaleType.Controls.Add(this.cbArgumentScaleType);
			this.pnlArgumentScaleType.Controls.Add(this.lblArgumentScaleType);
			this.pnlArgumentScaleType.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlArgumentScaleType.Location = new System.Drawing.Point(12, 31);
			this.pnlArgumentScaleType.Name = "pnlArgumentScaleType";
			this.pnlArgumentScaleType.Size = new System.Drawing.Size(317, 20);
			this.pnlArgumentScaleType.TabIndex = 2;
			this.cbArgumentScaleType.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbArgumentScaleType.EditValue = "Qualitative";
			this.cbArgumentScaleType.EnterMoveNextControl = true;
			this.cbArgumentScaleType.Location = new System.Drawing.Point(110, 0);
			this.cbArgumentScaleType.Name = "cbArgumentScaleType";
			this.cbArgumentScaleType.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbArgumentScaleType.Properties.Items.AddRange(new object[] {
			"Qualitative",
			"Numerical",
			"DateTime",
			"Auto"});
			this.cbArgumentScaleType.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbArgumentScaleType.Size = new System.Drawing.Size(207, 20);
			this.cbArgumentScaleType.TabIndex = 0;
			this.lblArgumentScaleType.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblArgumentScaleType.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblArgumentScaleType.Location = new System.Drawing.Point(0, 0);
			this.lblArgumentScaleType.Name = "lblArgumentScaleType";
			this.lblArgumentScaleType.Size = new System.Drawing.Size(110, 20);
			this.lblArgumentScaleType.TabIndex = 0;
			this.lblArgumentScaleType.Text = "Argument scale type:";
			this.chartPanelControl2.BackColor = System.Drawing.Color.Transparent;
			this.chartPanelControl2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.chartPanelControl2.Dock = System.Windows.Forms.DockStyle.Top;
			this.chartPanelControl2.Location = new System.Drawing.Point(12, 50);
			this.chartPanelControl2.Name = "chartPanelControl2";
			this.chartPanelControl2.Size = new System.Drawing.Size(293, 6);
			this.chartPanelControl2.TabIndex = 64;
			this.pnlDataFilters.AutoSize = true;
			this.pnlDataFilters.BackColor = System.Drawing.Color.Transparent;
			this.pnlDataFilters.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlDataFilters.Controls.Add(this.beFilters);
			this.pnlDataFilters.Controls.Add(this.lblDataFilters);
			this.pnlDataFilters.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlDataFilters.Location = new System.Drawing.Point(12, 111);
			this.pnlDataFilters.Name = "pnlDataFilters";
			this.pnlDataFilters.Size = new System.Drawing.Size(293, 20);
			this.pnlDataFilters.TabIndex = 66;
			this.beFilters.Dock = System.Windows.Forms.DockStyle.Top;
			this.beFilters.Location = new System.Drawing.Point(120, 0);
			this.beFilters.Name = "beFilters";
			this.beFilters.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton()});
			this.beFilters.Properties.ReadOnly = true;
			this.beFilters.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.beFilters.Size = new System.Drawing.Size(173, 20);
			this.beFilters.TabIndex = 0;
			this.lblDataFilters.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblDataFilters.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblDataFilters.Location = new System.Drawing.Point(0, 0);
			this.lblDataFilters.Name = "lblDataFilters";
			this.lblDataFilters.Size = new System.Drawing.Size(120, 20);
			this.lblDataFilters.TabIndex = 0;
			this.lblDataFilters.Text = "Data filters:";
			this.pnlDataFiltersSplitter.BackColor = System.Drawing.Color.Transparent;
			this.pnlDataFiltersSplitter.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlDataFiltersSplitter.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlDataFiltersSplitter.Location = new System.Drawing.Point(12, 107);
			this.pnlDataFiltersSplitter.Name = "pnlDataFiltersSplitter";
			this.pnlDataFiltersSplitter.Size = new System.Drawing.Size(293, 4);
			this.pnlDataFiltersSplitter.TabIndex = 65;
			this.pnlSortBy.AutoSize = true;
			this.pnlSortBy.BackColor = System.Drawing.Color.Transparent;
			this.pnlSortBy.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlSortBy.Controls.Add(this.cbPointSortingKey);
			this.pnlSortBy.Controls.Add(this.lblSortBy);
			this.pnlSortBy.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlSortBy.Location = new System.Drawing.Point(12, 87);
			this.pnlSortBy.Name = "pnlSortBy";
			this.pnlSortBy.Size = new System.Drawing.Size(293, 20);
			this.pnlSortBy.TabIndex = 64;
			this.cbPointSortingKey.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbPointSortingKey.Location = new System.Drawing.Point(120, 0);
			this.cbPointSortingKey.Name = "cbPointSortingKey";
			this.cbPointSortingKey.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbPointSortingKey.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbPointSortingKey.Size = new System.Drawing.Size(173, 20);
			this.cbPointSortingKey.TabIndex = 0;
			this.lblSortBy.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblSortBy.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblSortBy.Location = new System.Drawing.Point(0, 0);
			this.lblSortBy.Name = "lblSortBy";
			this.lblSortBy.Size = new System.Drawing.Size(120, 20);
			this.lblSortBy.TabIndex = 0;
			this.lblSortBy.Text = "Sort points by:";
			this.pnlSortungSplitter.BackColor = System.Drawing.Color.Transparent;
			this.pnlSortungSplitter.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlSortungSplitter.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlSortungSplitter.Location = new System.Drawing.Point(12, 75);
			this.pnlSortungSplitter.Name = "pnlSortungSplitter";
			this.pnlSortungSplitter.Size = new System.Drawing.Size(293, 12);
			this.pnlSortungSplitter.TabIndex = 63;
			this.pnlPointSortOrder.AutoSize = true;
			this.pnlPointSortOrder.BackColor = System.Drawing.Color.Transparent;
			this.pnlPointSortOrder.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlPointSortOrder.Controls.Add(this.cbPointSorting);
			this.pnlPointSortOrder.Controls.Add(this.lblPointSortOrder);
			this.pnlPointSortOrder.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlPointSortOrder.Location = new System.Drawing.Point(12, 55);
			this.pnlPointSortOrder.Name = "pnlPointSortOrder";
			this.pnlPointSortOrder.Size = new System.Drawing.Size(293, 20);
			this.pnlPointSortOrder.TabIndex = 62;
			this.cbPointSorting.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbPointSorting.Location = new System.Drawing.Point(120, 0);
			this.cbPointSorting.Name = "cbPointSorting";
			this.cbPointSorting.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbPointSorting.Properties.Items.AddRange(new object[] {
			"None",
			"Ascending",
			"Descending"});
			this.cbPointSorting.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbPointSorting.Size = new System.Drawing.Size(173, 20);
			this.cbPointSorting.TabIndex = 0;
			this.lblPointSortOrder.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblPointSortOrder.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblPointSortOrder.Location = new System.Drawing.Point(0, 0);
			this.lblPointSortOrder.Name = "lblPointSortOrder";
			this.lblPointSortOrder.Size = new System.Drawing.Size(120, 20);
			this.lblPointSortOrder.TabIndex = 0;
			this.lblPointSortOrder.Text = "Point sort order:";
			this.pnlSortOrderSplitter.BackColor = System.Drawing.Color.Transparent;
			this.pnlSortOrderSplitter.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlSortOrderSplitter.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlSortOrderSplitter.Location = new System.Drawing.Point(12, 51);
			this.pnlSortOrderSplitter.Name = "pnlSortOrderSplitter";
			this.pnlSortOrderSplitter.Size = new System.Drawing.Size(293, 4);
			this.pnlSortOrderSplitter.TabIndex = 61;
			this.pnlSeriesSortOrder.AutoSize = true;
			this.pnlSeriesSortOrder.BackColor = System.Drawing.Color.Transparent;
			this.pnlSeriesSortOrder.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.pnlSeriesSortOrder.Controls.Add(this.cbSeriesSorting);
			this.pnlSeriesSortOrder.Controls.Add(this.lblSeriesSortOrder);
			this.pnlSeriesSortOrder.Dock = System.Windows.Forms.DockStyle.Top;
			this.pnlSeriesSortOrder.Location = new System.Drawing.Point(12, 31);
			this.pnlSeriesSortOrder.Name = "pnlSeriesSortOrder";
			this.pnlSeriesSortOrder.Size = new System.Drawing.Size(293, 20);
			this.pnlSeriesSortOrder.TabIndex = 47;
			this.cbSeriesSorting.Dock = System.Windows.Forms.DockStyle.Top;
			this.cbSeriesSorting.Location = new System.Drawing.Point(120, 0);
			this.cbSeriesSorting.Name = "cbSeriesSorting";
			this.cbSeriesSorting.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cbSeriesSorting.Properties.Items.AddRange(new object[] {
			"None",
			"Ascending",
			"Descending"});
			this.cbSeriesSorting.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cbSeriesSorting.Size = new System.Drawing.Size(173, 20);
			this.cbSeriesSorting.TabIndex = 0;
			this.lblSeriesSortOrder.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblSeriesSortOrder.Dock = System.Windows.Forms.DockStyle.Left;
			this.lblSeriesSortOrder.Location = new System.Drawing.Point(0, 0);
			this.lblSeriesSortOrder.Name = "lblSeriesSortOrder";
			this.lblSeriesSortOrder.Size = new System.Drawing.Size(120, 20);
			this.lblSeriesSortOrder.TabIndex = 0;
			this.lblSeriesSortOrder.Text = "Series sort order:";
			this.lblNameSuffix.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblNameSuffix.Location = new System.Drawing.Point(9, 164);
			this.lblNameSuffix.Name = "lblNameSuffix";
			this.lblNameSuffix.Size = new System.Drawing.Size(120, 20);
			this.lblNameSuffix.TabIndex = 75;
			this.lblNameSuffix.Text = "Name suffix:";
			this.lblDataMember.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblDataMember.Location = new System.Drawing.Point(9, 60);
			this.lblDataMember.Name = "lblDataMember";
			this.lblDataMember.Size = new System.Drawing.Size(120, 20);
			this.lblDataMember.TabIndex = 66;
			this.lblDataMember.Text = "Data Member:";
			this.chartLabelControl1.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.chartLabelControl1.Location = new System.Drawing.Point(9, 138);
			this.chartLabelControl1.Name = "chartLabelControl1";
			this.chartLabelControl1.Size = new System.Drawing.Size(120, 20);
			this.chartLabelControl1.TabIndex = 73;
			this.chartLabelControl1.Text = "Series:";
			this.lblViewType.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblViewType.Location = new System.Drawing.Point(9, 86);
			this.lblViewType.Name = "lblViewType";
			this.lblViewType.Size = new System.Drawing.Size(120, 20);
			this.lblViewType.TabIndex = 69;
			this.lblViewType.Text = "View type:";
			this.lblSeries.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.lblSeries.Location = new System.Drawing.Point(9, 112);
			this.lblSeries.Name = "lblSeries";
			this.lblSeries.Size = new System.Drawing.Size(120, 20);
			this.lblSeries.TabIndex = 71;
			this.lblSeries.Text = "Series:";
			this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.btnOK.Location = new System.Drawing.Point(520, 451);
			this.btnOK.Name = "btnOK";
			this.btnOK.Size = new System.Drawing.Size(75, 23);
			this.btnOK.TabIndex = 82;
			this.btnOK.Text = "OK";
			this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.btnCancel.Location = new System.Drawing.Point(601, 451);
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Size = new System.Drawing.Size(75, 23);
			this.btnCancel.TabIndex = 83;
			this.btnCancel.Text = "Cancel";
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(689, 484);
			this.Controls.Add(this.btnCancel);
			this.Controls.Add(this.btnOK);
			this.Controls.Add(this.grColorSettings);
			this.Controls.Add(this.grValueSettings);
			this.Controls.Add(this.grArgumentSettings);
			this.Controls.Add(this.grFamiliarDataSourceOptions);
			this.Controls.Add(this.grSort);
			this.Controls.Add(this.grSeriesProperties);
			this.FormBorderEffect = DevExpress.XtraEditors.FormBorderEffect.Shadow;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			this.Name = "SmartBindingForm";
			this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Smart Binding";
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cbChartDataMember.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesViewType.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesDataMember.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.popupContainerEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.txtEndText.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grSeriesProperties)).EndInit();
			this.grSeriesProperties.ResumeLayout(false);
			this.grSeriesProperties.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grFamiliarDataSourceOptions)).EndInit();
			this.grFamiliarDataSourceOptions.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cheAutoLayoutSettings.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cheAutoBindingSettings.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grSort)).EndInit();
			this.grSort.ResumeLayout(false);
			this.grSort.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grArgumentSettings)).EndInit();
			this.grArgumentSettings.ResumeLayout(false);
			this.grArgumentSettings.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grValueSettings)).EndInit();
			this.grValueSettings.ResumeLayout(false);
			this.grValueSettings.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grColorSettings)).EndInit();
			this.grColorSettings.ResumeLayout(false);
			this.grColorSettings.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl3)).EndInit();
			this.chartPanelControl3.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbColor.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSummaryFunction)).EndInit();
			this.pnlSummaryFunction.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.beSummaryFunction.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue4)).EndInit();
			this.pnlValue4.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbValue4.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue3)).EndInit();
			this.pnlValue3.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbValue3.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue2)).EndInit();
			this.pnlValue2.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbValue2.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValue1)).EndInit();
			this.pnlValue1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbValue1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlBindingMode)).EndInit();
			this.pnlBindingMode.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbBindingMode.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lblDockOffset1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlValueScaleType)).EndInit();
			this.pnlValueScaleType.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbValueScaleType.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgument)).EndInit();
			this.pnlArgument.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbArgument.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgumentSplitter)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlArgumentScaleType)).EndInit();
			this.pnlArgumentScaleType.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbArgumentScaleType.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chartPanelControl2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlDataFilters)).EndInit();
			this.pnlDataFilters.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.beFilters.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlDataFiltersSplitter)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortBy)).EndInit();
			this.pnlSortBy.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbPointSortingKey.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortungSplitter)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlPointSortOrder)).EndInit();
			this.pnlPointSortOrder.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbPointSorting.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSortOrderSplitter)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pnlSeriesSortOrder)).EndInit();
			this.pnlSeriesSortOrder.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.cbSeriesSorting.Properties)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
		private XtraEditors.ComboBoxEdit comboBoxEdit1;
		private XtraEditors.LabelControl lblDataSource;
		private XtraEditors.PopupContainerEdit cbChartDataMember;
		private Wizard.ChartLabelControl lblDataMember;
		private XtraEditors.ImageComboBoxEdit cbSeriesViewType;
		private Wizard.ChartLabelControl lblViewType;
		private XtraEditors.PopupContainerEdit cbSeriesDataMember;
		private Wizard.ChartLabelControl lblSeries;
		private XtraEditors.PopupContainerEdit popupContainerEdit1;
		private Wizard.ChartLabelControl chartLabelControl1;
		private XtraEditors.TextEdit txtEndText;
		private Wizard.ChartLabelControl lblNameSuffix;
		private XtraEditors.GroupControl grSeriesProperties;
		private XtraEditors.GroupControl grFamiliarDataSourceOptions;
		private XtraEditors.CheckEdit cheAutoLayoutSettings;
		private Wizard.ChartPanelControl chartPanelControl2;
		private XtraEditors.CheckEdit cheAutoBindingSettings;
		private XtraEditors.GroupControl grSort;
		private Wizard.ChartPanelControl pnlDataFilters;
		private XtraEditors.ButtonEdit beFilters;
		private Wizard.ChartLabelControl lblDataFilters;
		private Wizard.ChartPanelControl pnlDataFiltersSplitter;
		private Wizard.ChartPanelControl pnlSortBy;
		private XtraEditors.ComboBoxEdit cbPointSortingKey;
		private Wizard.ChartLabelControl lblSortBy;
		private Wizard.ChartPanelControl pnlSortungSplitter;
		private Wizard.ChartPanelControl pnlPointSortOrder;
		private XtraEditors.ComboBoxEdit cbPointSorting;
		private Wizard.ChartLabelControl lblPointSortOrder;
		private Wizard.ChartPanelControl pnlSortOrderSplitter;
		private Wizard.ChartPanelControl pnlSeriesSortOrder;
		private XtraEditors.ComboBoxEdit cbSeriesSorting;
		private Wizard.ChartLabelControl lblSeriesSortOrder;
		private XtraEditors.GroupControl grArgumentSettings;
		private Wizard.ChartPanelControl pnlArgument;
		private XtraEditors.PopupContainerEdit cbArgument;
		private Wizard.ChartLabelControl lblArgument;
		private Wizard.ChartPanelControl pnlArgumentSplitter;
		private Wizard.ChartPanelControl pnlArgumentScaleType;
		private XtraEditors.ComboBoxEdit cbArgumentScaleType;
		private Wizard.ChartLabelControl lblArgumentScaleType;
		private XtraEditors.GroupControl grValueSettings;
		private Wizard.ChartPanelControl pnlSummaryFunction;
		private XtraEditors.ButtonEdit beSummaryFunction;
		private Wizard.ChartLabelControl lblSummaryFunction;
		private Wizard.ChartPanelControl pnlValue4;
		private XtraEditors.PopupContainerEdit cbValue4;
		private Wizard.ChartLabelControl lblValue4;
		private Wizard.ChartPanelControl lblDockOffset4;
		private Wizard.ChartPanelControl pnlValue3;
		private XtraEditors.PopupContainerEdit cbValue3;
		private Wizard.ChartLabelControl lblValue3;
		private Wizard.ChartPanelControl lblDockOffset3;
		private Wizard.ChartPanelControl pnlValue2;
		private XtraEditors.PopupContainerEdit cbValue2;
		private Wizard.ChartLabelControl lblValue2;
		private Wizard.ChartPanelControl lblDockOffset2;
		private Wizard.ChartPanelControl pnlValue1;
		private XtraEditors.PopupContainerEdit cbValue1;
		private Wizard.ChartLabelControl lblValue1;
		private Wizard.ChartPanelControl chartPanelControl1;
		private Wizard.ChartPanelControl pnlBindingMode;
		private XtraEditors.ComboBoxEdit cbBindingMode;
		private Wizard.ChartLabelControl lblBindingMode;
		private Wizard.ChartPanelControl lblDockOffset1;
		private Wizard.ChartPanelControl pnlValueScaleType;
		private XtraEditors.ComboBoxEdit cbValueScaleType;
		private Wizard.ChartLabelControl lblValueScaleType;
		private XtraEditors.GroupControl grColorSettings;
		private Wizard.ChartPanelControl chartPanelControl3;
		private XtraEditors.PopupContainerEdit cbColor;
		private Wizard.ChartLabelControl lblColor;
		private XtraEditors.SimpleButton btnOK;
		private XtraEditors.SimpleButton btnCancel;
	}
}
