#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
namespace DevExpress.Xpf.Printing {
	public enum PrintingStringId {
		OK,
		Cancel,
		ToolBarCaption,
		StatusBarCaption,
		Print,
		Print_Hint,
		PrintPdf,
		PrintPdf_Hint,
		PrintDirect,
		PrintDirect_Hint,
		Zoom,
		Zoom_Hint,
		DecreaseZoom,
		DecreaseZoom_Hint,
		IncreaseZoom,
		IncreaseZoom_Hint,
		ZoomToPageWidth,
		ZoomToPageHeight,
		ZoomToWholePage,
		ZoomToTwoPages,
		FirstPage,
		FirstPage_Hint,
		PreviousPage,
		PreviousPage_Hint,
		NextPage,
		NextPage_Hint,
		LastPage,
		LastPage_Hint,
		Watermark,
		Watermark_Hint,
		WatermarkTitle,
		TextWatermarkTitle,
		PictureWatermarkTitle,
		WatermarkText,
		WatermarkTextDirection,
		WatermarkTextColor,
		WatermarkFontName,
		WatermarkFontSize,
		WatermarkFontBold,
		WatermarkFontItalic,
		WatermarkPosition,
		WatermarkPositionInFront,
		WatermarkPositionBehind,
		WatermarkPageRange,
		WatermarkPageRangeAllPages,
		WatermarkPageRangePages,
		WatermarkPageRangeHint,
		WatermarkLoadImage,
		WatermarkImageSizeMode,
		WatermarkImageHorizontalAlignment,
		WatermarkImageVerticalAlignment,
		WatermarkImageTiling,
		WatermarkTransparency,
		WatermarkClearAll,
		WatermarkImageLoadError,
		ExportPdf,
		ExportHtm,
		ExportMht,
		ExportRtf,
		ExportXls,
		ExportXlsx,
		ExportCsv,
		ExportTxt,
		ExportImage,
		ExportXps,
		ExportFile,
		ExportFile_Hint,
		ExportFormat,
		Scaling,
		Scaling_Hint,
		Scaling_Adjust_Start_Label,
		Scaling_Adjust_End_Label,
		Scaling_Fit_Start_Label,
		Scaling_Fit_End_Label,
		Scaling_ComboBoxEdit_Validation_Error,
		Scaling_ComboBoxEdit_Validation_OutOfRange_Error,
		Search,
		Search_Hint,
		SendPdf,
		SendMht,
		SendRtf,
		SendXls,
		SendXlsx,
		SendCsv,
		SendTxt,
		SendImage,
		SendXps,
		SendFile,
		SendFile_Hint,
		StopPageBuilding,
		CurrentPageDisplayFormat,
		ZoomDisplayFormat,
		MsgCaption,
		PageSetup,
		PageSetup_Hint,
		GoToPage,
		PrintPreviewWindowCaption,
		DefaultPrintJobDescription,
		PdfPasswordSecurityOptions_Title,
		PdfPasswordSecurityOptions_RequireOpenPassword,
		PdfPasswordSecurityOptions_OpenPassword,
		PdfPasswordSecurityOptions_RestrictPermissions,
		PdfPasswordSecurityOptions_PermissionsPassword,
		PdfPasswordSecurityOptions_PrintingPermissions,
		PdfPasswordSecurityOptions_ChangingPermissions,
		PdfPasswordSecurityOptions_EnableCopying,
		PdfPasswordSecurityOptions_EnableScreenReaders,
		RepeatPassword_OpenPassword_Title,
		RepeatPassword_OpenPassword_Note,
		RepeatPassword_OpenPassword,
		RepeatPassword_PermissionsPassword_Title,
		RepeatPassword_PermissionsPassword_Note,
		RepeatPassword_PermissionsPassword,
		RepeatPassword_ConfirmationPasswordDoesNotMatch,
		PageSetupWindowTitle,
		PageSetupMarginsCaptionFormat,
		PageSetupPrinterCaption,
		PageSetupPrinter,
		PageSetupPrinterType,
		PageSetupPrinterPort,
		PageSetupPrinterComment,
		PageSetupPaperCaption,
		PageSetupPaperSize,
		PageSetupOrientationCaption,
		PageSetupOrientationPortrait,
		PageSetupOrientationLandscape,
		PageSetupMarginsLeft,
		PageSetupMarginsTop,
		PageSetupMarginsRight,
		PageSetupMarginsBottom,
		PageSetupMillimeters,
		PageSetupInches,
		ZoomValueItemFormat,
		Open,
		Open_Hint,
		Save,
		Save_Hint,
		Error,
		DocumentMap,
		DocumentMap_Hint,
		Refresh,
		Information,
		Parameters,
		Parameters_Hint,
		ParametersReset,
		ParametersSubmit,
		PdfPasswordSecurityOptions_Permissions,
		PdfPasswordSecurityOptions_OpenPasswordHeader,
		Search_EmptyResult,
		PreparingPages,
		PagesArePrepared,
		ExportPdfToWindow,
		ExportHtmToWindow,
		ExportMhtToWindow,
		ExportRtfToWindow,
		ExportXlsToWindow,
		ExportXlsxToWindow,
		ExportCsvToWindow,
		ExportTxtToWindow,
		ExportImageToWindow,
		ExportXpsToWindow,
		ExportFileToWindow,
		ExportFileToWindow_Hint,
		ClosePreview,
		Exception_NoPrinterFound,
		Msg_EmptyDocument,
		PdfSignatureEditorWindow_Certificate,
		PdfSignatureEditorWindow_Reason,
		PdfSignatureEditorWindow_Location,
		PdfSignatureEditorWindow_ContactInformation,
		PdfSignatureEditorWindow_Title,
		PaperKind_Custom,
		PaperKind_Letter,
		PaperKind_LetterSmall,
		PaperKind_Tabloid,
		PaperKind_Ledger,
		PaperKind_Legal,
		PaperKind_Statement,
		PaperKind_Executive,
		PaperKind_A3,
		PaperKind_A4,
		PaperKind_A4Small,
		PaperKind_A5,
		PaperKind_B4,
		PaperKind_B5,
		PaperKind_Folio,
		PaperKind_Quarto,
		PaperKind_Standard10x14,
		PaperKind_Standard11x17,
		PaperKind_Note,
		PaperKind_Number9Envelope,
		PaperKind_Number10Envelope,
		PaperKind_Number11Envelope,
		PaperKind_Number12Envelope,
		PaperKind_Number14Envelope,
		PaperKind_CSheet,
		PaperKind_DSheet,
		PaperKind_ESheet,
		PaperKind_DLEnvelope,
		PaperKind_C5Envelope,
		PaperKind_C3Envelope,
		PaperKind_C4Envelope,
		PaperKind_C6Envelope,
		PaperKind_C65Envelope,
		PaperKind_B4Envelope,
		PaperKind_B5Envelope,
		PaperKind_B6Envelope,
		PaperKind_ItalyEnvelope,
		PaperKind_MonarchEnvelope,
		PaperKind_PersonalEnvelope,
		PaperKind_USStandardFanfold,
		PaperKind_GermanStandardFanfold,
		PaperKind_GermanLegalFanfold,
		PaperKind_IsoB4,
		PaperKind_JapanesePostcard,
		PaperKind_Standard9x11,
		PaperKind_Standard10x11,
		PaperKind_Standard15x11,
		PaperKind_InviteEnvelope,
		PaperKind_LetterExtra,
		PaperKind_LegalExtra,
		PaperKind_TabloidExtra,
		PaperKind_A4Extra,
		PaperKind_LetterTransverse,
		PaperKind_A4Transverse,
		PaperKind_LetterExtraTransverse,
		PaperKind_APlus,
		PaperKind_BPlus,
		PaperKind_LetterPlus,
		PaperKind_A4Plus,
		PaperKind_A5Transverse,
		PaperKind_B5Transverse,
		PaperKind_A3Extra,
		PaperKind_A5Extra,
		PaperKind_B5Extra,
		PaperKind_A2,
		PaperKind_A3Transverse,
		PaperKind_A3ExtraTransverse,
		PaperKind_JapaneseDoublePostcard,
		PaperKind_A6,
		PaperKind_JapaneseEnvelopeKakuNumber2,
		PaperKind_JapaneseEnvelopeKakuNumber3,
		PaperKind_JapaneseEnvelopeChouNumber3,
		PaperKind_JapaneseEnvelopeChouNumber4,
		PaperKind_LetterRotated,
		PaperKind_A3Rotated,
		PaperKind_A4Rotated,
		PaperKind_A5Rotated,
		PaperKind_B4JisRotated,
		PaperKind_B5JisRotated,
		PaperKind_JapanesePostcardRotated,
		PaperKind_JapaneseDoublePostcardRotated,
		PaperKind_A6Rotated,
		PaperKind_JapaneseEnvelopeKakuNumber2Rotated,
		PaperKind_JapaneseEnvelopeKakuNumber3Rotated,
		PaperKind_JapaneseEnvelopeChouNumber3Rotated,
		PaperKind_JapaneseEnvelopeChouNumber4Rotated,
		PaperKind_B6Jis,
		PaperKind_B6JisRotated,
		PaperKind_Standard12x11,
		PaperKind_JapaneseEnvelopeYouNumber4,
		PaperKind_JapaneseEnvelopeYouNumber4Rotated,
		PaperKind_Prc16K,
		PaperKind_Prc32K,
		PaperKind_Prc32KBig,
		PaperKind_PrcEnvelopeNumber1,
		PaperKind_PrcEnvelopeNumber2,
		PaperKind_PrcEnvelopeNumber3,
		PaperKind_PrcEnvelopeNumber4,
		PaperKind_PrcEnvelopeNumber5,
		PaperKind_PrcEnvelopeNumber6,
		PaperKind_PrcEnvelopeNumber7,
		PaperKind_PrcEnvelopeNumber8,
		PaperKind_PrcEnvelopeNumber9,
		PaperKind_PrcEnvelopeNumber10,
		PaperKind_Prc16KRotated,
		PaperKind_Prc32KRotated,
		PaperKind_Prc32KBigRotated,
		PaperKind_PrcEnvelopeNumber1Rotated,
		PaperKind_PrcEnvelopeNumber2Rotated,
		PaperKind_PrcEnvelopeNumber3Rotated,
		PaperKind_PrcEnvelopeNumber4Rotated,
		PaperKind_PrcEnvelopeNumber5Rotated,
		PaperKind_PrcEnvelopeNumber6Rotated,
		PaperKind_PrcEnvelopeNumber7Rotated,
		PaperKind_PrcEnvelopeNumber8Rotated,
		PaperKind_PrcEnvelopeNumber9Rotated,
		PaperKind_PrcEnvelopeNumber10Rotated,
		RibbonPageGroup_File,
		RibbonPageGroup_Print,
		RibbonPageGroup_Navigation,
		RibbonPageGroup_Zoom,
		RibbonPageGroup_Export,
		RibbonPageGroup_Document,
		RibbonPageGroup_Watermark,
		RibbonPageCaption,
		True,
		False,
		HandTool,
		SelectTool,
		Copy,
		FilePath,
		OpenFileAfterExport,
		MoreOptions,
		#region printDialog
		Printer,
		Preferences,
		PrinterStatus,
		PrinterLocation,
		PrinterComment,
		PrinterQueue,
		Copies,
		Collate,
		PageRange,
		AllPages,
		CurrentPage,
		SomePages,
		PageRangeHint,
		PaperSource,
		PrintFilePath,
		PrintToFile,
		#endregion
		DocumentSourceNotSupported,
		ReportBehavior_RibbonReportsCaption,
		ReportBehavior_MenuPrintPreview,
		ReportBehavior_MenuDesignReport,
		ReportBehavior_MenuPrint,
		ReportBehavior_MenuEdit,
		ReportBehavior_MenuRename,
		ReportBehavior_MenuDelete,
		ReportBehavior_DeleteDialogCaption,
		ReportBehavior_DeleteDialogMessage,
		ReportBehavior_RenameDialogCaption,
		ReportBehavior_RenameDialogNameLabel,
		ReportBehavior_SaveDialogCaption,
		ReportManagerServiceWizard_SelectTheme,
		ReportManagerServiceWizard_WindowTitle,
		ReportManagerServiceWizard_SelectPageOptions,
		ReportManagerServiceWizard_Paper,
		ReportManagerServiceWizard_PaperSize,
		ReportManagerServiceWizard_ReportUnits,
		ReportManagerServiceWizard_PageOrientation,
		ReportManagerServiceWizard_PageSetup
	}
}
