#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System.Collections.Generic;
namespace DevExpress.Charts.Native {
	public class DetrendedPriceOscillatorCalculator {
		const int DesignTimePointsCount = 3;
		public bool Calculated { get; private set; }
		public double MinY { get; private set; }
		public double MaxY { get; private set; }
		public DetrendedPriceOscillatorCalculator() {
			Calculated = false;
			MinY = 0.0;
			MaxY = 1.0;
		}
		bool IsParametersCorrect(IRefinedSeries refinedSeries, int pointsCount, ValueLevelInternal valueLevel) {
			return
				refinedSeries != null &&
				refinedSeries.Points != null &&
				pointsCount > 0 &&
				refinedSeries.Points.Count >= pointsCount &&
				refinedSeries.SeriesView != null &&
				refinedSeries.SeriesView.IsCorrectValueLevel(valueLevel);
		}
		public List<GRealPoint2D> Calculate(IRefinedSeries refinedSeries, int pointsCount, ValueLevelInternal valueLevel) { 
			Calculated = false;
			int actualPointsCount = pointsCount;
			if (refinedSeries != null && refinedSeries.IsPointsAutoGenerated)
				actualPointsCount = DesignTimePointsCount;
			if (!IsParametersCorrect(refinedSeries, actualPointsCount, valueLevel))
				return new List<GRealPoint2D>(0);
			int period = actualPointsCount / 2 + 1;
			IList<RefinedPoint> refinedPoints = refinedSeries.Points;
			SimpleMovingAverageCalculator smaCalculator = new SimpleMovingAverageCalculator();
			smaCalculator.Calculate(refinedSeries, actualPointsCount, valueLevel, MovingAverageKindInternal.MovingAverage, 0.0);
			List<GRealPoint2D> sma = smaCalculator.MovingAverageData;
			double minIndicatorValue = refinedPoints[0].GetValue(valueLevel) - sma[period].Y; 
			double maxIndicatorValue = minIndicatorValue;
			var indicatorPoints = new List<GRealPoint2D>(refinedPoints.Count);
			for (int i = 0; i < refinedPoints.Count- period; i++) {
				RefinedPoint refinedPoint = refinedPoints[i];
				double indicatorValue = refinedPoint.GetValue(valueLevel) - sma[i+period].Y;
				indicatorPoints.Add(new GRealPoint2D(refinedPoint.Argument, indicatorValue));
				if (indicatorValue > maxIndicatorValue)
					maxIndicatorValue = indicatorValue;
				if (indicatorValue < minIndicatorValue) {
					minIndicatorValue = indicatorValue;
				}
			}
			MaxY = maxIndicatorValue;
			MinY = minIndicatorValue;
			Calculated = true;
			return indicatorPoints;
		}
	}
}
