#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
using System.Collections.Generic;
namespace DevExpress.Charts.Native {
	public class RateOfChangeCalculator {
		const int DesignTimePointsCount = 3;
		public bool Calculated { get; private set; }
		public double MinY { get; private set; }
		public double MaxY { get; private set; }
		public RateOfChangeCalculator() {
			Calculated = false;
			MinY = 0.0;
			MaxY = 1.0;
		}
		double CalculateRoC(IList<RefinedPoint> refinedPoints, int currIndex, int usingPointsCount, ValueLevelInternal valueLevel) {
			double currValue = refinedPoints[currIndex].GetValue(valueLevel);
			double oldValue = refinedPoints[currIndex - usingPointsCount].GetValue(valueLevel);
			return (currValue - oldValue) / oldValue * 100;
		}
		bool IsParametersCorrect(IRefinedSeries refinedSeries, int pointCount, ValueLevelInternal valueLevel) {
			return
				pointCount > 1 &&
				refinedSeries != null &&
				refinedSeries.Points != null &&
				refinedSeries.Points.Count > pointCount+1 &&
				refinedSeries.SeriesView != null &&
				refinedSeries.SeriesView.IsCorrectValueLevel(valueLevel);
		}
		public List<GRealPoint2D> Calculate(IRefinedSeries refinedSeries, int pointCount, ValueLevelInternal valueLevel) { 
			Calculated = false;
			IList<RefinedPoint> refinedPoints = refinedSeries.Points;
			int actualPointsCount = pointCount;
			if (refinedSeries != null && refinedSeries.IsPointsAutoGenerated)
				actualPointsCount = DesignTimePointsCount;
			if (!IsParametersCorrect(refinedSeries, actualPointsCount, valueLevel))
				return new List<GRealPoint2D>();
			var indicatorPoints = new List<GRealPoint2D>(refinedPoints.Count);
			double roc0 = CalculateRoC(refinedPoints, actualPointsCount, actualPointsCount, valueLevel);
			double minIndicatorValue = roc0;
			double maxIndicatorValue = roc0;
			for (int i = actualPointsCount; i<refinedPoints.Count; i++) {
				double roc = CalculateRoC(refinedPoints, i, actualPointsCount, valueLevel);
				indicatorPoints.Add(new GRealPoint2D(refinedPoints[i].Argument, roc));
				if (roc > maxIndicatorValue)
					maxIndicatorValue = roc;
				if (roc < minIndicatorValue) {
					minIndicatorValue = roc;
				}
			}
			Calculated = true;
			MaxY = maxIndicatorValue;
			MinY = minIndicatorValue;
			return indicatorPoints;
		}
	}
}
