#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System.Collections.Generic;
namespace DevExpress.Charts.Native {
	public class RelativeStrengthIndexCalculator {
		const int DesignTimePointsCount = 3;
		public bool Calculated { get; private set; }
		public double MinY { get; private set; }
		public double MaxY { get; private set; }
		public RelativeStrengthIndexCalculator() {
			Calculated = false;
			MinY = 0.0;
			MaxY = 1.0;
		}
		bool IsParametersCorrect(IRefinedSeries refinedSeries, int pointsCount, ValueLevelInternal valueLevel) {
			return
				refinedSeries != null &&
				refinedSeries.Points != null &&
				pointsCount > 0 &&
				refinedSeries.Points.Count > pointsCount + 1 &&
				refinedSeries.SeriesView != null &&
				refinedSeries.SeriesView.IsCorrectValueLevel(valueLevel);
		}
		double CalcNextEma(double value, double preEma, double smoothingFactor) {
			return smoothingFactor * value + (1 - smoothingFactor) * preEma;
		}
		public List<GRealPoint2D> Calculate(IRefinedSeries refinedSeries, int pointCount, ValueLevelInternal valueLevel) { 
			Calculated = false;
			int actualPointsCount = pointCount;
			if (refinedSeries != null && refinedSeries.IsPointsAutoGenerated)
				actualPointsCount = DesignTimePointsCount;
			if (!IsParametersCorrect(refinedSeries, actualPointsCount, valueLevel))
				return new List<GRealPoint2D>(0);
			IList<RefinedPoint> refinedPoints = refinedSeries.Points;
			var indicatorPoints = new List<GRealPoint2D>(refinedPoints.Count);
			var upList = new List<double>(refinedPoints.Count);
			upList.Add(double.NaN); 
			var downList = new List<double>(refinedPoints.Count);
			downList.Add(double.NaN);
			for (int i = 1; i < refinedPoints.Count; i++) {
				double nowValue = refinedPoints[i].GetValue(valueLevel);
				double preValue = refinedPoints[i-1].GetValue(valueLevel);
				double diff = nowValue - preValue;
				if (diff > 0) {
					upList.Add(diff);
					downList.Add(0);
				}
				else {
					upList.Add(0);
					downList.Add(-diff);
				}
			}
			double smoothingFactor = 1.0 / actualPointsCount;
			double upEma = upList[1];
			double downEma = downList[1];
			for (int i = 2; i < actualPointsCount + 1; i++) {
				upEma = CalcNextEma(upList[i], upEma, smoothingFactor);
				downEma = CalcNextEma(downList[i], downEma, smoothingFactor);
			}
			double rsi0 = double.NaN;
			if (downEma == 0)
				rsi0 = 100;
			else {
				double rs0 = upEma / downEma;
				rsi0 = 100 - (100 / (1 + rs0));
			}
			indicatorPoints.Add(new GRealPoint2D(refinedPoints[actualPointsCount].Argument, rsi0));
			double minIndicatorValue = rsi0;
			double maxIndicatorValue = rsi0;
			for (int i = actualPointsCount + 1; i < refinedPoints.Count; i++) {
				upEma = CalcNextEma(upList[i], upEma, smoothingFactor);
				downEma = CalcNextEma(downList[i], downEma, smoothingFactor);
				double rsi = double.NaN;
				if (downEma == 0.0)
					rsi = 100;
				else {
					double rs = upEma / downEma;
					rsi = 100 - (100 / (1 + rs));
				}
				indicatorPoints.Add(new GRealPoint2D(refinedPoints[i].Argument, rsi));
				if (rsi > maxIndicatorValue)
					maxIndicatorValue = rsi;
				if (rsi < minIndicatorValue) {
					minIndicatorValue = rsi;
				}
			}
			Calculated = true;
			MaxY = maxIndicatorValue;
			MinY = minIndicatorValue;
			return indicatorPoints;
		}
	}
}
