#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

namespace DevExpress.XtraSpreadsheet.Forms {
	partial class DocumentPropertiesForm {
		private System.ComponentModel.IContainer components = null;
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		#region Windows Form Designer generated code
		private void InitializeComponent() {
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DocumentPropertiesForm));
			this.btnCancel = new DevExpress.XtraEditors.SimpleButton();
			this.btnOk = new DevExpress.XtraEditors.SimpleButton();
			this.tabStatistics = new DevExpress.XtraTab.XtraTabControl();
			this.pageGeneral = new DevExpress.XtraTab.XtraTabPage();
			this.panelControl2 = new DevExpress.XtraEditors.PanelControl();
			this.chkSystem = new DevExpress.XtraEditors.CheckEdit();
			this.chkHidden = new DevExpress.XtraEditors.CheckEdit();
			this.chkArchive = new DevExpress.XtraEditors.CheckEdit();
			this.chkReadOnly = new DevExpress.XtraEditors.CheckEdit();
			this.lblAttributes = new DevExpress.XtraEditors.LabelControl();
			this.edtFileAccessed = new DevExpress.XtraEditors.TextEdit();
			this.lblFileAccessed = new DevExpress.XtraEditors.LabelControl();
			this.edtFileModified = new DevExpress.XtraEditors.TextEdit();
			this.lblFileModified = new DevExpress.XtraEditors.LabelControl();
			this.edtFileCreated = new DevExpress.XtraEditors.TextEdit();
			this.lblFileCreated = new DevExpress.XtraEditors.LabelControl();
			this.labelControl6 = new DevExpress.XtraEditors.LabelControl();
			this.labelControl13 = new DevExpress.XtraEditors.LabelControl();
			this.edtShortName = new DevExpress.XtraEditors.TextEdit();
			this.lblShortName = new DevExpress.XtraEditors.LabelControl();
			this.edtSize = new DevExpress.XtraEditors.TextEdit();
			this.lblSize = new DevExpress.XtraEditors.LabelControl();
			this.edtLocation = new DevExpress.XtraEditors.TextEdit();
			this.lblLocation = new DevExpress.XtraEditors.LabelControl();
			this.edtFileName = new DevExpress.XtraEditors.TextEdit();
			this.labelControl11 = new DevExpress.XtraEditors.LabelControl();
			this.lblFileName = new DevExpress.XtraEditors.LabelControl();
			this.pageSummary = new DevExpress.XtraTab.XtraTabPage();
			this.panel = new DevExpress.XtraEditors.PanelControl();
			this.lblComments = new DevExpress.XtraEditors.LabelControl();
			this.edtComments = new DevExpress.XtraEditors.MemoEdit();
			this.lblKeywords = new DevExpress.XtraEditors.LabelControl();
			this.edtKeywords = new DevExpress.XtraEditors.TextEdit();
			this.lblCategory = new DevExpress.XtraEditors.LabelControl();
			this.edtCategory = new DevExpress.XtraEditors.TextEdit();
			this.lblSeparator = new DevExpress.XtraEditors.LabelControl();
			this.lblCompany = new DevExpress.XtraEditors.LabelControl();
			this.edtCompany = new DevExpress.XtraEditors.TextEdit();
			this.lblManager = new DevExpress.XtraEditors.LabelControl();
			this.edtManager = new DevExpress.XtraEditors.TextEdit();
			this.lblAuthor = new DevExpress.XtraEditors.LabelControl();
			this.edtAuthor = new DevExpress.XtraEditors.TextEdit();
			this.lblTitle = new DevExpress.XtraEditors.LabelControl();
			this.edtTitle = new DevExpress.XtraEditors.TextEdit();
			this.lblSubject = new DevExpress.XtraEditors.LabelControl();
			this.edtSubject = new DevExpress.XtraEditors.TextEdit();
			this.pageStatistics = new DevExpress.XtraTab.XtraTabPage();
			this.panelControl1 = new DevExpress.XtraEditors.PanelControl();
			this.edtLastSavedBy = new DevExpress.XtraEditors.TextEdit();
			this.lblLastSavedBy = new DevExpress.XtraEditors.LabelControl();
			this.edtPrinted = new DevExpress.XtraEditors.TextEdit();
			this.lblPrinted = new DevExpress.XtraEditors.LabelControl();
			this.edtAccessed = new DevExpress.XtraEditors.TextEdit();
			this.lblAccessed = new DevExpress.XtraEditors.LabelControl();
			this.edtModified = new DevExpress.XtraEditors.TextEdit();
			this.lblModified = new DevExpress.XtraEditors.LabelControl();
			this.edtCreated = new DevExpress.XtraEditors.TextEdit();
			this.labelControl4 = new DevExpress.XtraEditors.LabelControl();
			this.lblCreated = new DevExpress.XtraEditors.LabelControl();
			this.tabCustom = new DevExpress.XtraTab.XtraTabPage();
			this.panelControl4 = new DevExpress.XtraEditors.PanelControl();
			this.lblProperties = new DevExpress.XtraEditors.LabelControl();
			this.grid = new DevExpress.XtraGrid.GridControl();
			this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
			this.colName = new DevExpress.XtraGrid.Columns.GridColumn();
			this.colValue = new DevExpress.XtraGrid.Columns.GridColumn();
			this.colType = new DevExpress.XtraGrid.Columns.GridColumn();
			this.lblValue = new DevExpress.XtraEditors.LabelControl();
			this.edtValue = new DevExpress.XtraEditors.TextEdit();
			this.lblType = new DevExpress.XtraEditors.LabelControl();
			this.edtType = new DevExpress.XtraEditors.LookUpEdit();
			this.btnDelete = new DevExpress.XtraEditors.SimpleButton();
			this.btnModify = new DevExpress.XtraEditors.SimpleButton();
			this.btnAdd = new DevExpress.XtraEditors.SimpleButton();
			this.lstPredefinedProperties = new DevExpress.XtraEditors.ListBoxControl();
			this.lblName = new DevExpress.XtraEditors.LabelControl();
			this.edtName = new DevExpress.XtraEditors.TextEdit();
			this.rgrpYesNo = new DevExpress.XtraEditors.RadioGroup();
			((System.ComponentModel.ISupportInitialize)(this.tabStatistics)).BeginInit();
			this.tabStatistics.SuspendLayout();
			this.pageGeneral.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.panelControl2)).BeginInit();
			this.panelControl2.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkSystem.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkHidden.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkArchive.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkReadOnly.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileAccessed.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileModified.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileCreated.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtShortName.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSize.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtLocation.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileName.Properties)).BeginInit();
			this.pageSummary.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.panel)).BeginInit();
			this.panel.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtComments.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtKeywords.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCategory.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCompany.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtManager.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtAuthor.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTitle.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSubject.Properties)).BeginInit();
			this.pageStatistics.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.panelControl1)).BeginInit();
			this.panelControl1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtLastSavedBy.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPrinted.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtAccessed.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtModified.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCreated.Properties)).BeginInit();
			this.tabCustom.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.panelControl4)).BeginInit();
			this.panelControl4.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtValue.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtType.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lstPredefinedProperties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtName.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.rgrpYesNo.Properties)).BeginInit();
			this.SuspendLayout();
			resources.ApplyResources(this.btnCancel, "btnCancel");
			this.btnCancel.CausesValidation = false;
			this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.btnCancel.Name = "btnCancel";
			resources.ApplyResources(this.btnOk, "btnOk");
			this.btnOk.Name = "btnOk";
			this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
			resources.ApplyResources(this.tabStatistics, "tabStatistics");
			this.tabStatistics.Name = "tabStatistics";
			this.tabStatistics.SelectedTabPage = this.pageGeneral;
			this.tabStatistics.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
			this.pageGeneral,
			this.pageSummary,
			this.pageStatistics,
			this.tabCustom});
			this.tabStatistics.SelectedPageChanged += new DevExpress.XtraTab.TabPageChangedEventHandler(this.tabStatistics_SelectedPageChanged);
			this.tabStatistics.SelectedPageChanging += new DevExpress.XtraTab.TabPageChangingEventHandler(this.tabStatistics_SelectedPageChanging);
			this.pageGeneral.Controls.Add(this.panelControl2);
			this.pageGeneral.Name = "pageGeneral";
			resources.ApplyResources(this.pageGeneral, "pageGeneral");
			resources.ApplyResources(this.panelControl2, "panelControl2");
			this.panelControl2.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("panelControl2.Appearance.BackColor")));
			this.panelControl2.Appearance.Options.UseBackColor = true;
			this.panelControl2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.panelControl2.Controls.Add(this.chkSystem);
			this.panelControl2.Controls.Add(this.chkHidden);
			this.panelControl2.Controls.Add(this.chkArchive);
			this.panelControl2.Controls.Add(this.chkReadOnly);
			this.panelControl2.Controls.Add(this.lblAttributes);
			this.panelControl2.Controls.Add(this.edtFileAccessed);
			this.panelControl2.Controls.Add(this.lblFileAccessed);
			this.panelControl2.Controls.Add(this.edtFileModified);
			this.panelControl2.Controls.Add(this.lblFileModified);
			this.panelControl2.Controls.Add(this.edtFileCreated);
			this.panelControl2.Controls.Add(this.lblFileCreated);
			this.panelControl2.Controls.Add(this.labelControl6);
			this.panelControl2.Controls.Add(this.labelControl13);
			this.panelControl2.Controls.Add(this.edtShortName);
			this.panelControl2.Controls.Add(this.lblShortName);
			this.panelControl2.Controls.Add(this.edtSize);
			this.panelControl2.Controls.Add(this.lblSize);
			this.panelControl2.Controls.Add(this.edtLocation);
			this.panelControl2.Controls.Add(this.lblLocation);
			this.panelControl2.Controls.Add(this.edtFileName);
			this.panelControl2.Controls.Add(this.labelControl11);
			this.panelControl2.Controls.Add(this.lblFileName);
			this.panelControl2.Name = "panelControl2";
			resources.ApplyResources(this.chkSystem, "chkSystem");
			this.chkSystem.Name = "chkSystem";
			this.chkSystem.Properties.AutoWidth = true;
			this.chkSystem.Properties.Caption = resources.GetString("chkSystem.Properties.Caption");
			resources.ApplyResources(this.chkHidden, "chkHidden");
			this.chkHidden.Name = "chkHidden";
			this.chkHidden.Properties.AutoWidth = true;
			this.chkHidden.Properties.Caption = resources.GetString("chkHidden.Properties.Caption");
			resources.ApplyResources(this.chkArchive, "chkArchive");
			this.chkArchive.Name = "chkArchive";
			this.chkArchive.Properties.AutoWidth = true;
			this.chkArchive.Properties.Caption = resources.GetString("chkArchive.Properties.Caption");
			resources.ApplyResources(this.chkReadOnly, "chkReadOnly");
			this.chkReadOnly.Name = "chkReadOnly";
			this.chkReadOnly.Properties.AutoWidth = true;
			this.chkReadOnly.Properties.Caption = resources.GetString("chkReadOnly.Properties.Caption");
			resources.ApplyResources(this.lblAttributes, "lblAttributes");
			this.lblAttributes.Name = "lblAttributes";
			resources.ApplyResources(this.edtFileAccessed, "edtFileAccessed");
			this.edtFileAccessed.Name = "edtFileAccessed";
			this.edtFileAccessed.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtFileAccessed.Properties.ReadOnly = true;
			this.edtFileAccessed.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblFileAccessed, "lblFileAccessed");
			this.lblFileAccessed.Name = "lblFileAccessed";
			resources.ApplyResources(this.edtFileModified, "edtFileModified");
			this.edtFileModified.Name = "edtFileModified";
			this.edtFileModified.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtFileModified.Properties.ReadOnly = true;
			this.edtFileModified.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblFileModified, "lblFileModified");
			this.lblFileModified.Name = "lblFileModified";
			resources.ApplyResources(this.edtFileCreated, "edtFileCreated");
			this.edtFileCreated.Name = "edtFileCreated";
			this.edtFileCreated.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtFileCreated.Properties.ReadOnly = true;
			this.edtFileCreated.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblFileCreated, "lblFileCreated");
			this.lblFileCreated.Name = "lblFileCreated";
			resources.ApplyResources(this.labelControl6, "labelControl6");
			this.labelControl6.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.labelControl6.LineVisible = true;
			this.labelControl6.Name = "labelControl6";
			resources.ApplyResources(this.labelControl13, "labelControl13");
			this.labelControl13.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.labelControl13.LineVisible = true;
			this.labelControl13.Name = "labelControl13";
			resources.ApplyResources(this.edtShortName, "edtShortName");
			this.edtShortName.Name = "edtShortName";
			this.edtShortName.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtShortName.Properties.ReadOnly = true;
			this.edtShortName.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblShortName, "lblShortName");
			this.lblShortName.Name = "lblShortName";
			resources.ApplyResources(this.edtSize, "edtSize");
			this.edtSize.Name = "edtSize";
			this.edtSize.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtSize.Properties.ReadOnly = true;
			this.edtSize.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblSize, "lblSize");
			this.lblSize.Name = "lblSize";
			resources.ApplyResources(this.edtLocation, "edtLocation");
			this.edtLocation.Name = "edtLocation";
			this.edtLocation.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtLocation.Properties.ReadOnly = true;
			this.edtLocation.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblLocation, "lblLocation");
			this.lblLocation.Name = "lblLocation";
			resources.ApplyResources(this.edtFileName, "edtFileName");
			this.edtFileName.Name = "edtFileName";
			this.edtFileName.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtFileName.Properties.ReadOnly = true;
			this.edtFileName.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.labelControl11, "labelControl11");
			this.labelControl11.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.labelControl11.LineVisible = true;
			this.labelControl11.Name = "labelControl11";
			resources.ApplyResources(this.lblFileName, "lblFileName");
			this.lblFileName.Name = "lblFileName";
			this.pageSummary.Controls.Add(this.panel);
			this.pageSummary.Name = "pageSummary";
			resources.ApplyResources(this.pageSummary, "pageSummary");
			resources.ApplyResources(this.panel, "panel");
			this.panel.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("panel.Appearance.BackColor")));
			this.panel.Appearance.Options.UseBackColor = true;
			this.panel.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.panel.Controls.Add(this.lblComments);
			this.panel.Controls.Add(this.edtComments);
			this.panel.Controls.Add(this.lblKeywords);
			this.panel.Controls.Add(this.edtKeywords);
			this.panel.Controls.Add(this.lblCategory);
			this.panel.Controls.Add(this.edtCategory);
			this.panel.Controls.Add(this.lblSeparator);
			this.panel.Controls.Add(this.lblCompany);
			this.panel.Controls.Add(this.edtCompany);
			this.panel.Controls.Add(this.lblManager);
			this.panel.Controls.Add(this.edtManager);
			this.panel.Controls.Add(this.lblAuthor);
			this.panel.Controls.Add(this.edtAuthor);
			this.panel.Controls.Add(this.lblTitle);
			this.panel.Controls.Add(this.edtTitle);
			this.panel.Controls.Add(this.lblSubject);
			this.panel.Controls.Add(this.edtSubject);
			this.panel.Name = "panel";
			resources.ApplyResources(this.lblComments, "lblComments");
			this.lblComments.Name = "lblComments";
			resources.ApplyResources(this.edtComments, "edtComments");
			this.edtComments.Name = "edtComments";
			resources.ApplyResources(this.lblKeywords, "lblKeywords");
			this.lblKeywords.Name = "lblKeywords";
			resources.ApplyResources(this.edtKeywords, "edtKeywords");
			this.edtKeywords.Name = "edtKeywords";
			resources.ApplyResources(this.lblCategory, "lblCategory");
			this.lblCategory.Name = "lblCategory";
			resources.ApplyResources(this.edtCategory, "edtCategory");
			this.edtCategory.Name = "edtCategory";
			resources.ApplyResources(this.lblSeparator, "lblSeparator");
			this.lblSeparator.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblSeparator.LineVisible = true;
			this.lblSeparator.Name = "lblSeparator";
			resources.ApplyResources(this.lblCompany, "lblCompany");
			this.lblCompany.Name = "lblCompany";
			resources.ApplyResources(this.edtCompany, "edtCompany");
			this.edtCompany.Name = "edtCompany";
			resources.ApplyResources(this.lblManager, "lblManager");
			this.lblManager.Name = "lblManager";
			resources.ApplyResources(this.edtManager, "edtManager");
			this.edtManager.Name = "edtManager";
			resources.ApplyResources(this.lblAuthor, "lblAuthor");
			this.lblAuthor.Name = "lblAuthor";
			resources.ApplyResources(this.edtAuthor, "edtAuthor");
			this.edtAuthor.Name = "edtAuthor";
			resources.ApplyResources(this.lblTitle, "lblTitle");
			this.lblTitle.Name = "lblTitle";
			resources.ApplyResources(this.edtTitle, "edtTitle");
			this.edtTitle.Name = "edtTitle";
			resources.ApplyResources(this.lblSubject, "lblSubject");
			this.lblSubject.Name = "lblSubject";
			resources.ApplyResources(this.edtSubject, "edtSubject");
			this.edtSubject.Name = "edtSubject";
			this.pageStatistics.Controls.Add(this.panelControl1);
			this.pageStatistics.Name = "pageStatistics";
			resources.ApplyResources(this.pageStatistics, "pageStatistics");
			resources.ApplyResources(this.panelControl1, "panelControl1");
			this.panelControl1.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("panelControl1.Appearance.BackColor")));
			this.panelControl1.Appearance.Options.UseBackColor = true;
			this.panelControl1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.panelControl1.Controls.Add(this.edtLastSavedBy);
			this.panelControl1.Controls.Add(this.lblLastSavedBy);
			this.panelControl1.Controls.Add(this.edtPrinted);
			this.panelControl1.Controls.Add(this.lblPrinted);
			this.panelControl1.Controls.Add(this.edtAccessed);
			this.panelControl1.Controls.Add(this.lblAccessed);
			this.panelControl1.Controls.Add(this.edtModified);
			this.panelControl1.Controls.Add(this.lblModified);
			this.panelControl1.Controls.Add(this.edtCreated);
			this.panelControl1.Controls.Add(this.labelControl4);
			this.panelControl1.Controls.Add(this.lblCreated);
			this.panelControl1.Name = "panelControl1";
			resources.ApplyResources(this.edtLastSavedBy, "edtLastSavedBy");
			this.edtLastSavedBy.Name = "edtLastSavedBy";
			this.edtLastSavedBy.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtLastSavedBy.Properties.ReadOnly = true;
			this.edtLastSavedBy.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblLastSavedBy, "lblLastSavedBy");
			this.lblLastSavedBy.Name = "lblLastSavedBy";
			resources.ApplyResources(this.edtPrinted, "edtPrinted");
			this.edtPrinted.Name = "edtPrinted";
			this.edtPrinted.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtPrinted.Properties.ReadOnly = true;
			this.edtPrinted.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblPrinted, "lblPrinted");
			this.lblPrinted.Name = "lblPrinted";
			resources.ApplyResources(this.edtAccessed, "edtAccessed");
			this.edtAccessed.Name = "edtAccessed";
			this.edtAccessed.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtAccessed.Properties.ReadOnly = true;
			this.edtAccessed.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblAccessed, "lblAccessed");
			this.lblAccessed.Name = "lblAccessed";
			resources.ApplyResources(this.edtModified, "edtModified");
			this.edtModified.Name = "edtModified";
			this.edtModified.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtModified.Properties.ReadOnly = true;
			this.edtModified.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.lblModified, "lblModified");
			this.lblModified.Name = "lblModified";
			resources.ApplyResources(this.edtCreated, "edtCreated");
			this.edtCreated.Name = "edtCreated";
			this.edtCreated.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.edtCreated.Properties.ReadOnly = true;
			this.edtCreated.Properties.UseReadOnlyAppearance = false;
			resources.ApplyResources(this.labelControl4, "labelControl4");
			this.labelControl4.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.labelControl4.LineVisible = true;
			this.labelControl4.Name = "labelControl4";
			resources.ApplyResources(this.lblCreated, "lblCreated");
			this.lblCreated.Name = "lblCreated";
			this.tabCustom.Controls.Add(this.panelControl4);
			this.tabCustom.Name = "tabCustom";
			resources.ApplyResources(this.tabCustom, "tabCustom");
			resources.ApplyResources(this.panelControl4, "panelControl4");
			this.panelControl4.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("panelControl4.Appearance.BackColor")));
			this.panelControl4.Appearance.Options.UseBackColor = true;
			this.panelControl4.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.panelControl4.Controls.Add(this.lblProperties);
			this.panelControl4.Controls.Add(this.grid);
			this.panelControl4.Controls.Add(this.lblValue);
			this.panelControl4.Controls.Add(this.edtValue);
			this.panelControl4.Controls.Add(this.lblType);
			this.panelControl4.Controls.Add(this.edtType);
			this.panelControl4.Controls.Add(this.btnDelete);
			this.panelControl4.Controls.Add(this.btnModify);
			this.panelControl4.Controls.Add(this.btnAdd);
			this.panelControl4.Controls.Add(this.lstPredefinedProperties);
			this.panelControl4.Controls.Add(this.lblName);
			this.panelControl4.Controls.Add(this.edtName);
			this.panelControl4.Controls.Add(this.rgrpYesNo);
			this.panelControl4.Name = "panelControl4";
			resources.ApplyResources(this.lblProperties, "lblProperties");
			this.lblProperties.Name = "lblProperties";
			resources.ApplyResources(this.grid, "grid");
			this.grid.Cursor = System.Windows.Forms.Cursors.Default;
			this.grid.MainView = this.gridView1;
			this.grid.Name = "grid";
			this.grid.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
			this.gridView1});
			this.gridView1.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
			this.colName,
			this.colValue,
			this.colType});
			this.gridView1.GridControl = this.grid;
			this.gridView1.Name = "gridView1";
			this.gridView1.OptionsBehavior.Editable = false;
			this.gridView1.OptionsCustomization.AllowFilter = false;
			this.gridView1.OptionsCustomization.AllowGroup = false;
			this.gridView1.OptionsCustomization.AllowSort = false;
			this.gridView1.OptionsMenu.EnableColumnMenu = false;
			this.gridView1.OptionsMenu.EnableFooterMenu = false;
			this.gridView1.OptionsMenu.EnableGroupPanelMenu = false;
			this.gridView1.OptionsSelection.EnableAppearanceFocusedCell = false;
			this.gridView1.OptionsView.ShowGroupPanel = false;
			this.gridView1.OptionsView.ShowIndicator = false;
			this.gridView1.FocusedRowChanged += new DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventHandler(this.gridView1_FocusedRowChanged);
			this.gridView1.Click += new System.EventHandler(this.gridView1_Click);
			resources.ApplyResources(this.colName, "colName");
			this.colName.FieldName = "Name";
			this.colName.Name = "colName";
			this.colName.OptionsColumn.AllowGroup = DevExpress.Utils.DefaultBoolean.False;
			resources.ApplyResources(this.colValue, "colValue");
			this.colValue.FieldName = "Text";
			this.colValue.Name = "colValue";
			this.colValue.OptionsColumn.AllowGroup = DevExpress.Utils.DefaultBoolean.False;
			resources.ApplyResources(this.colType, "colType");
			this.colType.FieldName = "TypeText";
			this.colType.Name = "colType";
			this.colType.OptionsColumn.AllowGroup = DevExpress.Utils.DefaultBoolean.False;
			resources.ApplyResources(this.lblValue, "lblValue");
			this.lblValue.Name = "lblValue";
			resources.ApplyResources(this.edtValue, "edtValue");
			this.edtValue.Name = "edtValue";
			resources.ApplyResources(this.lblType, "lblType");
			this.lblType.Name = "lblType";
			resources.ApplyResources(this.edtType, "edtType");
			this.edtType.Name = "edtType";
			this.edtType.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtType.Properties.Buttons"))))});
			this.edtType.Properties.ShowFooter = false;
			this.edtType.Properties.ShowHeader = false;
			resources.ApplyResources(this.btnDelete, "btnDelete");
			this.btnDelete.CausesValidation = false;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
			resources.ApplyResources(this.btnModify, "btnModify");
			this.btnModify.CausesValidation = false;
			this.btnModify.Name = "btnModify";
			this.btnModify.Click += new System.EventHandler(this.btnModify_Click);
			resources.ApplyResources(this.btnAdd, "btnAdd");
			this.btnAdd.CausesValidation = false;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
			resources.ApplyResources(this.lstPredefinedProperties, "lstPredefinedProperties");
			this.lstPredefinedProperties.Name = "lstPredefinedProperties";
			this.lstPredefinedProperties.SelectedIndexChanged += new System.EventHandler(this.lstPredefinedProperties_SelectedIndexChanged);
			resources.ApplyResources(this.lblName, "lblName");
			this.lblName.Name = "lblName";
			resources.ApplyResources(this.edtName, "edtName");
			this.edtName.Name = "edtName";
			resources.ApplyResources(this.rgrpYesNo, "rgrpYesNo");
			this.rgrpYesNo.Name = "rgrpYesNo";
			this.rgrpYesNo.Properties.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("rgrpYesNo.Properties.Appearance.BackColor")));
			this.rgrpYesNo.Properties.Appearance.Options.UseBackColor = true;
			this.rgrpYesNo.Properties.Columns = 2;
			this.rgrpYesNo.Properties.Items.AddRange(new DevExpress.XtraEditors.Controls.RadioGroupItem[] {
			new DevExpress.XtraEditors.Controls.RadioGroupItem(((object)(resources.GetObject("rgrpYesNo.Properties.Items"))), resources.GetString("rgrpYesNo.Properties.Items1")),
			new DevExpress.XtraEditors.Controls.RadioGroupItem(((object)(resources.GetObject("rgrpYesNo.Properties.Items2"))), resources.GetString("rgrpYesNo.Properties.Items3"))});
			this.AcceptButton = this.btnOk;
			this.AccessibleRole = System.Windows.Forms.AccessibleRole.Window;
			resources.ApplyResources(this, "$this");
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.btnCancel;
			this.Controls.Add(this.tabStatistics);
			this.Controls.Add(this.btnOk);
			this.Controls.Add(this.btnCancel);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "DocumentPropertiesForm";
			this.ShowInTaskbar = false;
			this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
			((System.ComponentModel.ISupportInitialize)(this.tabStatistics)).EndInit();
			this.tabStatistics.ResumeLayout(false);
			this.pageGeneral.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.panelControl2)).EndInit();
			this.panelControl2.ResumeLayout(false);
			this.panelControl2.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkSystem.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkHidden.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkArchive.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkReadOnly.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileAccessed.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileModified.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileCreated.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtShortName.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSize.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtLocation.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFileName.Properties)).EndInit();
			this.pageSummary.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.panel)).EndInit();
			this.panel.ResumeLayout(false);
			this.panel.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtComments.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtKeywords.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCategory.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCompany.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtManager.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtAuthor.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTitle.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSubject.Properties)).EndInit();
			this.pageStatistics.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.panelControl1)).EndInit();
			this.panelControl1.ResumeLayout(false);
			this.panelControl1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtLastSavedBy.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPrinted.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtAccessed.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtModified.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtCreated.Properties)).EndInit();
			this.tabCustom.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.panelControl4)).EndInit();
			this.panelControl4.ResumeLayout(false);
			this.panelControl4.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtValue.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtType.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lstPredefinedProperties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtName.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.rgrpYesNo.Properties)).EndInit();
			this.ResumeLayout(false);
		}
		#endregion
		private XtraEditors.SimpleButton btnCancel;
		private XtraEditors.SimpleButton btnOk;
		private XtraTab.XtraTabControl tabStatistics;
		private XtraTab.XtraTabPage pageSummary;
		private XtraEditors.PanelControl panel;
		private XtraEditors.LabelControl lblTitle;
		private XtraEditors.TextEdit edtTitle;
		private XtraEditors.LabelControl lblSubject;
		private XtraEditors.TextEdit edtSubject;
		private XtraEditors.LabelControl lblCompany;
		private XtraEditors.TextEdit edtCompany;
		private XtraEditors.LabelControl lblManager;
		private XtraEditors.TextEdit edtManager;
		private XtraEditors.LabelControl lblAuthor;
		private XtraEditors.TextEdit edtAuthor;
		private XtraEditors.LabelControl lblComments;
		private XtraEditors.MemoEdit edtComments;
		private XtraEditors.LabelControl lblKeywords;
		private XtraEditors.TextEdit edtKeywords;
		private XtraEditors.LabelControl lblCategory;
		private XtraEditors.TextEdit edtCategory;
		private XtraEditors.LabelControl lblSeparator;
		private XtraTab.XtraTabPage pageStatistics;
		private XtraEditors.PanelControl panelControl1;
		private XtraEditors.TextEdit edtLastSavedBy;
		private XtraEditors.LabelControl lblLastSavedBy;
		private XtraEditors.TextEdit edtPrinted;
		private XtraEditors.LabelControl lblPrinted;
		private XtraEditors.TextEdit edtAccessed;
		private XtraEditors.LabelControl lblAccessed;
		private XtraEditors.TextEdit edtModified;
		private XtraEditors.LabelControl lblModified;
		private XtraEditors.TextEdit edtCreated;
		private XtraEditors.LabelControl labelControl4;
		private XtraEditors.LabelControl lblCreated;
		private XtraTab.XtraTabPage pageGeneral;
		private XtraEditors.PanelControl panelControl2;
		private XtraEditors.TextEdit edtFileAccessed;
		private XtraEditors.LabelControl lblFileAccessed;
		private XtraEditors.TextEdit edtFileModified;
		private XtraEditors.LabelControl lblFileModified;
		private XtraEditors.TextEdit edtFileCreated;
		private XtraEditors.LabelControl lblFileCreated;
		private XtraEditors.LabelControl labelControl6;
		private XtraEditors.LabelControl labelControl13;
		private XtraEditors.TextEdit edtShortName;
		private XtraEditors.LabelControl lblShortName;
		private XtraEditors.TextEdit edtSize;
		private XtraEditors.LabelControl lblSize;
		private XtraEditors.TextEdit edtLocation;
		private XtraEditors.LabelControl lblLocation;
		private XtraEditors.TextEdit edtFileName;
		private XtraEditors.LabelControl labelControl11;
		private XtraEditors.LabelControl lblFileName;
		private XtraEditors.LabelControl lblAttributes;
		private XtraEditors.CheckEdit chkSystem;
		private XtraEditors.CheckEdit chkHidden;
		private XtraEditors.CheckEdit chkArchive;
		private XtraEditors.CheckEdit chkReadOnly;
		private XtraTab.XtraTabPage tabCustom;
		private XtraEditors.PanelControl panelControl4;
		private XtraEditors.LabelControl lblName;
		private XtraEditors.TextEdit edtName;
		private XtraEditors.SimpleButton btnDelete;
		private XtraEditors.SimpleButton btnModify;
		private XtraEditors.SimpleButton btnAdd;
		private XtraEditors.ListBoxControl lstPredefinedProperties;
		private XtraEditors.LabelControl lblValue;
		private XtraEditors.TextEdit edtValue;
		private XtraEditors.LabelControl lblType;
		private XtraEditors.LookUpEdit edtType;
		private XtraEditors.LabelControl lblProperties;
		private XtraGrid.GridControl grid;
		private XtraGrid.Views.Grid.GridView gridView1;
		private XtraGrid.Columns.GridColumn colName;
		private XtraGrid.Columns.GridColumn colValue;
		private XtraGrid.Columns.GridColumn colType;
		private XtraEditors.RadioGroup rgrpYesNo;
	}
}
