#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using DevExpress.XtraEditors.Controls;
using DevExpress.XtraRichEdit;
using DevExpress.XtraSpreadsheet.Forms.Design;
using System.Drawing;
using System.Windows.Forms;
namespace DevExpress.XtraSpreadsheet.Forms {
	partial class FormatCellsForm {
		private System.ComponentModel.IContainer components = null;
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		#region Windows Form Designer generated code
		private void InitializeComponent() {
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormatCellsForm));
			this.tabControl = new DevExpress.XtraTab.XtraTabControl();
			this.xtraTabNumber = new DevExpress.XtraTab.XtraTabPage();
			this.formatNumberCustomControl = new DevExpress.XtraSpreadsheet.Forms.Design.FormatNumberCustomControl();
			this.lblCategoryDescription = new DevExpress.XtraEditors.LabelControl();
			this.lblNumberDescription = new DevExpress.XtraEditors.LabelControl();
			this.formatNumberTypeControl = new DevExpress.XtraSpreadsheet.Forms.Design.FormatNumberTypeControl();
			this.formatNumberDecimalControl = new DevExpress.XtraSpreadsheet.Forms.Design.FormatNumberDecimalControl();
			this.grpNumberSample = new DevExpress.XtraEditors.GroupControl();
			this.lblNumberSample = new DevExpress.XtraEditors.LabelControl();
			this.lbCategory = new DevExpress.XtraEditors.LabelControl();
			this.lBoxNumberCategory = new DevExpress.XtraEditors.ListBoxControl();
			this.xtraTabAlignment = new DevExpress.XtraTab.XtraTabPage();
			this.edtVerticalAlignment = new DevExpress.XtraEditors.LookUpEdit();
			this.edtHorizontalAlignment = new DevExpress.XtraEditors.LookUpEdit();
			this.edtTextDirection = new DevExpress.XtraEditors.LookUpEdit();
			this.grpOrientation = new DevExpress.XtraEditors.GroupControl();
			this.edtDegrees = new DevExpress.XtraEditors.SpinEdit();
			this.lblDegrees = new DevExpress.XtraEditors.LabelControl();
			this.chkWrapText = new DevExpress.XtraEditors.CheckEdit();
			this.chkShrinkToFit = new DevExpress.XtraEditors.CheckEdit();
			this.chkMergeCells = new DevExpress.XtraEditors.CheckEdit();
			this.chkJustifyDistributed = new DevExpress.XtraEditors.CheckEdit();
			this.lblTextDirectoin = new DevExpress.XtraEditors.LabelControl();
			this.lblIndent = new DevExpress.XtraEditors.LabelControl();
			this.lblVertical = new DevExpress.XtraEditors.LabelControl();
			this.lblHorizontal = new DevExpress.XtraEditors.LabelControl();
			this.lblRightToLeft = new DevExpress.XtraEditors.LabelControl();
			this.lblTextControl = new DevExpress.XtraEditors.LabelControl();
			this.lblTextAlignmet = new DevExpress.XtraEditors.LabelControl();
			this.edtIndent = new DevExpress.XtraEditors.SpinEdit();
			this.xtraTabFont = new DevExpress.XtraTab.XtraTabPage();
			this.lblFontDescription = new DevExpress.XtraEditors.LabelControl();
			this.edtColorFont = new DevExpress.XtraEditors.ColorPickEdit();
			this.grpPreview = new DevExpress.XtraEditors.GroupControl();
			this.edtFontPreview = new DevExpress.XtraRichEdit.Forms.SimpleRichEditControl();
			this.chkNormalFont = new DevExpress.XtraEditors.CheckEdit();
			this.lblColorFont = new DevExpress.XtraEditors.LabelControl();
			this.grpEffects = new DevExpress.XtraEditors.GroupControl();
			this.chkSubscript = new DevExpress.XtraEditors.CheckEdit();
			this.chkSuperscript = new DevExpress.XtraEditors.CheckEdit();
			this.chkStrikeThrough = new DevExpress.XtraEditors.CheckEdit();
			this.edtUnderline = new DevExpress.XtraEditors.LookUpEdit();
			this.lblUnderline = new DevExpress.XtraEditors.LabelControl();
			this.lBoxSize = new DevExpress.XtraEditors.ListBoxControl();
			this.lBoxFontStyle = new DevExpress.XtraEditors.ListBoxControl();
			this.lBoxFont = new DevExpress.XtraEditors.ListBoxControl();
			this.edtSize = new DevExpress.XtraEditors.TextEdit();
			this.lblSize = new DevExpress.XtraEditors.LabelControl();
			this.edtFontStyle = new DevExpress.XtraEditors.TextEdit();
			this.lblFontStyle = new DevExpress.XtraEditors.LabelControl();
			this.edtFont = new DevExpress.XtraEditors.TextEdit();
			this.lblFont = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabBorder = new DevExpress.XtraTab.XtraTabPage();
			this.formatBorderControl = new DevExpress.XtraSpreadsheet.Forms.Design.FormatBorderControl();
			this.lblBorderDescription = new DevExpress.XtraEditors.LabelControl();
			this.btnInside = new DevExpress.XtraEditors.SimpleButton();
			this.btnNone = new DevExpress.XtraEditors.SimpleButton();
			this.btnOutline = new DevExpress.XtraEditors.SimpleButton();
			this.lblBorder = new DevExpress.XtraEditors.LabelControl();
			this.lblInside = new DevExpress.XtraEditors.LabelControl();
			this.lblOutline = new DevExpress.XtraEditors.LabelControl();
			this.lblNone = new DevExpress.XtraEditors.LabelControl();
			this.lblPresets = new DevExpress.XtraEditors.LabelControl();
			this.grpLine = new DevExpress.XtraEditors.GroupControl();
			this.edtColorBorder = new DevExpress.XtraEditors.ColorPickEdit();
			this.lblColorBorder = new DevExpress.XtraEditors.LabelControl();
			this.lblStyle = new DevExpress.XtraEditors.LabelControl();
			this.lbBorderLineStyle = new DevExpress.XtraSpreadsheet.Forms.Design.BorderLineStyleListBox();
			this.xtraTabFill = new DevExpress.XtraTab.XtraTabPage();
			this.chkNoColor = new DevExpress.XtraEditors.CheckButton();
			this.lblBackgroundColor = new DevExpress.XtraEditors.LabelControl();
			this.edtPatternColor = new DevExpress.XtraEditors.ColorPickEdit();
			this.lblPatternColor = new DevExpress.XtraEditors.LabelControl();
			this.edtPatternStyle = new DevExpress.XtraSpreadsheet.Forms.Design.PatternStyleImageComboBoxEdit();
			this.lblPatternStyle = new DevExpress.XtraEditors.LabelControl();
			this.grpFillSample = new DevExpress.XtraEditors.GroupControl();
			this.drawPatternType = new DevExpress.XtraEditors.PanelControl();
			this.edtBackColor = new DevExpress.XtraEditors.ColorPickEdit();
			this.xtraTabProtection = new DevExpress.XtraTab.XtraTabPage();
			this.lblProtection = new DevExpress.XtraEditors.LabelControl();
			this.chkHidden = new DevExpress.XtraEditors.CheckEdit();
			this.chkLocked = new DevExpress.XtraEditors.CheckEdit();
			this.btnOk = new DevExpress.XtraEditors.SimpleButton();
			this.btnCancel = new DevExpress.XtraEditors.SimpleButton();
			((System.ComponentModel.ISupportInitialize)(this.tabControl)).BeginInit();
			this.tabControl.SuspendLayout();
			this.xtraTabNumber.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grpNumberSample)).BeginInit();
			this.grpNumberSample.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.lBoxNumberCategory)).BeginInit();
			this.xtraTabAlignment.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtVerticalAlignment.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtHorizontalAlignment.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTextDirection.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grpOrientation)).BeginInit();
			this.grpOrientation.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtDegrees.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkWrapText.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShrinkToFit.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMergeCells.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkJustifyDistributed.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtIndent.Properties)).BeginInit();
			this.xtraTabFont.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtColorFont.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grpPreview)).BeginInit();
			this.grpPreview.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkNormalFont.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grpEffects)).BeginInit();
			this.grpEffects.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkSubscript.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSuperscript.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkStrikeThrough.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtUnderline.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxSize)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxFontStyle)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxFont)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSize.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFontStyle.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFont.Properties)).BeginInit();
			this.xtraTabBorder.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.grpLine)).BeginInit();
			this.grpLine.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtColorBorder.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.lbBorderLineStyle)).BeginInit();
			this.xtraTabFill.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtPatternColor.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPatternStyle.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.grpFillSample)).BeginInit();
			this.grpFillSample.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.drawPatternType)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtBackColor.Properties)).BeginInit();
			this.xtraTabProtection.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkHidden.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkLocked.Properties)).BeginInit();
			this.SuspendLayout();
			resources.ApplyResources(this.tabControl, "tabControl");
			this.tabControl.Name = "tabControl";
			this.tabControl.SelectedTabPage = this.xtraTabNumber;
			this.tabControl.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
			this.xtraTabNumber,
			this.xtraTabAlignment,
			this.xtraTabFont,
			this.xtraTabBorder,
			this.xtraTabFill,
			this.xtraTabProtection});
			this.xtraTabNumber.Controls.Add(this.formatNumberCustomControl);
			this.xtraTabNumber.Controls.Add(this.lblCategoryDescription);
			this.xtraTabNumber.Controls.Add(this.lblNumberDescription);
			this.xtraTabNumber.Controls.Add(this.formatNumberTypeControl);
			this.xtraTabNumber.Controls.Add(this.formatNumberDecimalControl);
			this.xtraTabNumber.Controls.Add(this.grpNumberSample);
			this.xtraTabNumber.Controls.Add(this.lbCategory);
			this.xtraTabNumber.Controls.Add(this.lBoxNumberCategory);
			this.xtraTabNumber.Name = "xtraTabNumber";
			resources.ApplyResources(this.xtraTabNumber, "xtraTabNumber");
			this.formatNumberCustomControl.CustomFormatCode = null;
			resources.ApplyResources(this.formatNumberCustomControl, "formatNumberCustomControl");
			this.formatNumberCustomControl.Name = "formatNumberCustomControl";
			resources.ApplyResources(this.lblCategoryDescription, "lblCategoryDescription");
			this.lblCategoryDescription.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblCategoryDescription.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Top;
			this.lblCategoryDescription.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
			this.lblCategoryDescription.Name = "lblCategoryDescription";
			this.lblNumberDescription.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Top;
			this.lblNumberDescription.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
			resources.ApplyResources(this.lblNumberDescription, "lblNumberDescription");
			this.lblNumberDescription.Name = "lblNumberDescription";
			resources.ApplyResources(this.formatNumberTypeControl, "formatNumberTypeControl");
			this.formatNumberTypeControl.Name = "formatNumberTypeControl";
			this.formatNumberTypeControl.SelectedTypeIndex = 0;
			this.formatNumberDecimalControl.DecimalPlaces = 0;
			resources.ApplyResources(this.formatNumberDecimalControl, "formatNumberDecimalControl");
			this.formatNumberDecimalControl.Name = "formatNumberDecimalControl";
			this.formatNumberDecimalControl.NegativeNumbersVisible = false;
			this.formatNumberDecimalControl.SymbolListVisible = false;
			this.formatNumberDecimalControl.UseThousandSeparatorVisible = false;
			resources.ApplyResources(this.grpNumberSample, "grpNumberSample");
			this.grpNumberSample.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
			this.grpNumberSample.Controls.Add(this.lblNumberSample);
			this.grpNumberSample.Name = "grpNumberSample";
			resources.ApplyResources(this.lblNumberSample, "lblNumberSample");
			this.lblNumberSample.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			this.lblNumberSample.Name = "lblNumberSample";
			resources.ApplyResources(this.lbCategory, "lbCategory");
			this.lbCategory.Name = "lbCategory";
			resources.ApplyResources(this.lBoxNumberCategory, "lBoxNumberCategory");
			this.lBoxNumberCategory.AccessibleRole = System.Windows.Forms.AccessibleRole.List;
			this.lBoxNumberCategory.Name = "lBoxNumberCategory";
			this.xtraTabAlignment.Controls.Add(this.edtVerticalAlignment);
			this.xtraTabAlignment.Controls.Add(this.edtHorizontalAlignment);
			this.xtraTabAlignment.Controls.Add(this.edtTextDirection);
			this.xtraTabAlignment.Controls.Add(this.grpOrientation);
			this.xtraTabAlignment.Controls.Add(this.chkWrapText);
			this.xtraTabAlignment.Controls.Add(this.chkShrinkToFit);
			this.xtraTabAlignment.Controls.Add(this.chkMergeCells);
			this.xtraTabAlignment.Controls.Add(this.chkJustifyDistributed);
			this.xtraTabAlignment.Controls.Add(this.lblTextDirectoin);
			this.xtraTabAlignment.Controls.Add(this.lblIndent);
			this.xtraTabAlignment.Controls.Add(this.lblVertical);
			this.xtraTabAlignment.Controls.Add(this.lblHorizontal);
			this.xtraTabAlignment.Controls.Add(this.lblRightToLeft);
			this.xtraTabAlignment.Controls.Add(this.lblTextControl);
			this.xtraTabAlignment.Controls.Add(this.lblTextAlignmet);
			this.xtraTabAlignment.Controls.Add(this.edtIndent);
			this.xtraTabAlignment.Name = "xtraTabAlignment";
			resources.ApplyResources(this.xtraTabAlignment, "xtraTabAlignment");
			resources.ApplyResources(this.edtVerticalAlignment, "edtVerticalAlignment");
			this.edtVerticalAlignment.Name = "edtVerticalAlignment";
			this.edtVerticalAlignment.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtVerticalAlignment.Properties.Buttons"))))});
			this.edtVerticalAlignment.Properties.DropDownRows = 5;
			this.edtVerticalAlignment.Properties.NullText = resources.GetString("edtVerticalAlignment.Properties.NullText");
			this.edtVerticalAlignment.Properties.ShowFooter = false;
			this.edtVerticalAlignment.Properties.ShowHeader = false;
			resources.ApplyResources(this.edtHorizontalAlignment, "edtHorizontalAlignment");
			this.edtHorizontalAlignment.Name = "edtHorizontalAlignment";
			this.edtHorizontalAlignment.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtHorizontalAlignment.Properties.Buttons"))))});
			this.edtHorizontalAlignment.Properties.DropDownRows = 8;
			this.edtHorizontalAlignment.Properties.NullText = resources.GetString("edtHorizontalAlignment.Properties.NullText");
			this.edtHorizontalAlignment.Properties.ShowFooter = false;
			this.edtHorizontalAlignment.Properties.ShowHeader = false;
			resources.ApplyResources(this.edtTextDirection, "edtTextDirection");
			this.edtTextDirection.Name = "edtTextDirection";
			this.edtTextDirection.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtTextDirection.Properties.Buttons"))))});
			this.edtTextDirection.Properties.DropDownRows = 3;
			this.edtTextDirection.Properties.NullText = resources.GetString("edtTextDirection.Properties.NullText");
			this.edtTextDirection.Properties.ShowFooter = false;
			this.edtTextDirection.Properties.ShowHeader = false;
			resources.ApplyResources(this.grpOrientation, "grpOrientation");
			this.grpOrientation.Controls.Add(this.edtDegrees);
			this.grpOrientation.Controls.Add(this.lblDegrees);
			this.grpOrientation.Name = "grpOrientation";
			resources.ApplyResources(this.edtDegrees, "edtDegrees");
			this.edtDegrees.Name = "edtDegrees";
			this.edtDegrees.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton()});
			this.edtDegrees.Properties.Mask.EditMask = resources.GetString("edtDegrees.Properties.Mask.EditMask");
			this.edtDegrees.Properties.MaxValue = new decimal(new int[] {
			90,
			0,
			0,
			0});
			this.edtDegrees.Properties.MinValue = new decimal(new int[] {
			90,
			0,
			0,
			-2147483648});
			resources.ApplyResources(this.lblDegrees, "lblDegrees");
			this.lblDegrees.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblDegrees.Name = "lblDegrees";
			this.lblDegrees.ShowLineShadow = false;
			this.chkWrapText.CausesValidation = false;
			resources.ApplyResources(this.chkWrapText, "chkWrapText");
			this.chkWrapText.Name = "chkWrapText";
			this.chkWrapText.Properties.AutoWidth = true;
			this.chkWrapText.Properties.Caption = resources.GetString("chkWrapText.Properties.Caption");
			this.chkShrinkToFit.CausesValidation = false;
			resources.ApplyResources(this.chkShrinkToFit, "chkShrinkToFit");
			this.chkShrinkToFit.Name = "chkShrinkToFit";
			this.chkShrinkToFit.Properties.AutoWidth = true;
			this.chkShrinkToFit.Properties.Caption = resources.GetString("chkShrinkToFit.Properties.Caption");
			this.chkMergeCells.CausesValidation = false;
			resources.ApplyResources(this.chkMergeCells, "chkMergeCells");
			this.chkMergeCells.Name = "chkMergeCells";
			this.chkMergeCells.Properties.AutoWidth = true;
			this.chkMergeCells.Properties.Caption = resources.GetString("chkMergeCells.Properties.Caption");
			resources.ApplyResources(this.chkJustifyDistributed, "chkJustifyDistributed");
			this.chkJustifyDistributed.Name = "chkJustifyDistributed";
			this.chkJustifyDistributed.Properties.AutoWidth = true;
			this.chkJustifyDistributed.Properties.Caption = resources.GetString("chkJustifyDistributed.Properties.Caption");
			resources.ApplyResources(this.lblTextDirectoin, "lblTextDirectoin");
			this.lblTextDirectoin.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblTextDirectoin.Name = "lblTextDirectoin";
			this.lblTextDirectoin.ShowLineShadow = false;
			resources.ApplyResources(this.lblIndent, "lblIndent");
			this.lblIndent.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblIndent.Name = "lblIndent";
			this.lblIndent.ShowLineShadow = false;
			resources.ApplyResources(this.lblVertical, "lblVertical");
			this.lblVertical.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblVertical.Name = "lblVertical";
			resources.ApplyResources(this.lblHorizontal, "lblHorizontal");
			this.lblHorizontal.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblHorizontal.Name = "lblHorizontal";
			resources.ApplyResources(this.lblRightToLeft, "lblRightToLeft");
			this.lblRightToLeft.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblRightToLeft.LineVisible = true;
			this.lblRightToLeft.Name = "lblRightToLeft";
			resources.ApplyResources(this.lblTextControl, "lblTextControl");
			this.lblTextControl.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblTextControl.LineVisible = true;
			this.lblTextControl.Name = "lblTextControl";
			resources.ApplyResources(this.lblTextAlignmet, "lblTextAlignmet");
			this.lblTextAlignmet.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblTextAlignmet.LineVisible = true;
			this.lblTextAlignmet.Name = "lblTextAlignmet";
			resources.ApplyResources(this.edtIndent, "edtIndent");
			this.edtIndent.Name = "edtIndent";
			this.edtIndent.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton()});
			this.edtIndent.Properties.Mask.EditMask = resources.GetString("edtIndent.Properties.Mask.EditMask");
			this.edtIndent.Properties.MaxValue = new decimal(new int[] {
			250,
			0,
			0,
			0});
			this.xtraTabFont.Controls.Add(this.lblFontDescription);
			this.xtraTabFont.Controls.Add(this.edtColorFont);
			this.xtraTabFont.Controls.Add(this.grpPreview);
			this.xtraTabFont.Controls.Add(this.chkNormalFont);
			this.xtraTabFont.Controls.Add(this.lblColorFont);
			this.xtraTabFont.Controls.Add(this.grpEffects);
			this.xtraTabFont.Controls.Add(this.edtUnderline);
			this.xtraTabFont.Controls.Add(this.lblUnderline);
			this.xtraTabFont.Controls.Add(this.lBoxSize);
			this.xtraTabFont.Controls.Add(this.lBoxFontStyle);
			this.xtraTabFont.Controls.Add(this.lBoxFont);
			this.xtraTabFont.Controls.Add(this.edtSize);
			this.xtraTabFont.Controls.Add(this.lblSize);
			this.xtraTabFont.Controls.Add(this.edtFontStyle);
			this.xtraTabFont.Controls.Add(this.lblFontStyle);
			this.xtraTabFont.Controls.Add(this.edtFont);
			this.xtraTabFont.Controls.Add(this.lblFont);
			this.xtraTabFont.Name = "xtraTabFont";
			resources.ApplyResources(this.xtraTabFont, "xtraTabFont");
			resources.ApplyResources(this.lblFontDescription, "lblFontDescription");
			this.lblFontDescription.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFontDescription.Name = "lblFontDescription";
			resources.ApplyResources(this.edtColorFont, "edtColorFont");
			this.edtColorFont.Name = "edtColorFont";
			this.edtColorFont.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtColorFont.Properties.Buttons"))))});
			this.edtColorFont.Properties.ColorAlignment = DevExpress.Utils.HorzAlignment.Center;
			this.edtColorFont.Properties.ShowSystemColors = false;
			this.edtColorFont.Properties.ShowWebColors = false;
			resources.ApplyResources(this.grpPreview, "grpPreview");
			this.grpPreview.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
			this.grpPreview.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("grpPreview.Appearance.BackColor")));
			this.grpPreview.Appearance.Options.UseBackColor = true;
			this.grpPreview.Controls.Add(this.edtFontPreview);
			this.grpPreview.Name = "grpPreview";
			this.edtFontPreview.ActiveViewType = DevExpress.XtraRichEdit.RichEditViewType.Simple;
			this.edtFontPreview.Appearance.Text.Font = ((System.Drawing.Font)(resources.GetObject("edtFontPreview.Appearance.Text.Font")));
			this.edtFontPreview.Appearance.Text.Options.UseFont = true;
			resources.ApplyResources(this.edtFontPreview, "edtFontPreview");
			this.edtFontPreview.EnableToolTips = true;
			this.edtFontPreview.Name = "edtFontPreview";
			this.edtFontPreview.Options.Behavior.OfficeScrolling = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
			this.edtFontPreview.Options.Behavior.ShowPopupMenu = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
			this.edtFontPreview.Options.Behavior.Zooming = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
			this.edtFontPreview.Options.Comments.ShowAllAuthors = false;
			this.edtFontPreview.Options.Export.PlainText.ExportFinalParagraphMark = DevExpress.XtraRichEdit.Export.PlainText.ExportFinalParagraphMark.Never;
			this.edtFontPreview.Options.HorizontalRuler.Visibility = DevExpress.XtraRichEdit.RichEditRulerVisibility.Hidden;
			this.edtFontPreview.Options.HorizontalScrollbar.Visibility = DevExpress.XtraRichEdit.RichEditScrollbarVisibility.Hidden;
			this.edtFontPreview.Options.VerticalRuler.Visibility = DevExpress.XtraRichEdit.RichEditRulerVisibility.Hidden;
			this.edtFontPreview.Options.VerticalScrollbar.Visibility = DevExpress.XtraRichEdit.RichEditScrollbarVisibility.Hidden;
			this.edtFontPreview.ReadOnly = true;
			this.edtFontPreview.ShowCaretInReadOnly = false;
			this.edtFontPreview.Views.SimpleView.Padding = new System.Windows.Forms.Padding(-100);
			this.chkNormalFont.CausesValidation = false;
			resources.ApplyResources(this.chkNormalFont, "chkNormalFont");
			this.chkNormalFont.Name = "chkNormalFont";
			this.chkNormalFont.Properties.AutoWidth = true;
			this.chkNormalFont.Properties.Caption = resources.GetString("chkNormalFont.Properties.Caption");
			resources.ApplyResources(this.lblColorFont, "lblColorFont");
			this.lblColorFont.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblColorFont.Name = "lblColorFont";
			resources.ApplyResources(this.grpEffects, "grpEffects");
			this.grpEffects.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
			this.grpEffects.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("grpEffects.Appearance.BackColor")));
			this.grpEffects.Appearance.Options.UseBackColor = true;
			this.grpEffects.Controls.Add(this.chkSubscript);
			this.grpEffects.Controls.Add(this.chkSuperscript);
			this.grpEffects.Controls.Add(this.chkStrikeThrough);
			this.grpEffects.Name = "grpEffects";
			this.chkSubscript.CausesValidation = false;
			resources.ApplyResources(this.chkSubscript, "chkSubscript");
			this.chkSubscript.Name = "chkSubscript";
			this.chkSubscript.Properties.AutoWidth = true;
			this.chkSubscript.Properties.Caption = resources.GetString("chkSubscript.Properties.Caption");
			this.chkSuperscript.CausesValidation = false;
			resources.ApplyResources(this.chkSuperscript, "chkSuperscript");
			this.chkSuperscript.Name = "chkSuperscript";
			this.chkSuperscript.Properties.AutoWidth = true;
			this.chkSuperscript.Properties.Caption = resources.GetString("chkSuperscript.Properties.Caption");
			this.chkStrikeThrough.CausesValidation = false;
			resources.ApplyResources(this.chkStrikeThrough, "chkStrikeThrough");
			this.chkStrikeThrough.Name = "chkStrikeThrough";
			this.chkStrikeThrough.Properties.AutoWidth = true;
			this.chkStrikeThrough.Properties.Caption = resources.GetString("chkStrikeThrough.Properties.Caption");
			resources.ApplyResources(this.edtUnderline, "edtUnderline");
			this.edtUnderline.Name = "edtUnderline";
			this.edtUnderline.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtUnderline.Properties.Buttons"))))});
			this.edtUnderline.Properties.DropDownRows = 5;
			this.edtUnderline.Properties.NullText = resources.GetString("edtUnderline.Properties.NullText");
			this.edtUnderline.Properties.ShowFooter = false;
			this.edtUnderline.Properties.ShowHeader = false;
			resources.ApplyResources(this.lblUnderline, "lblUnderline");
			this.lblUnderline.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblUnderline.Name = "lblUnderline";
			resources.ApplyResources(this.lBoxSize, "lBoxSize");
			this.lBoxSize.AccessibleRole = System.Windows.Forms.AccessibleRole.List;
			this.lBoxSize.Name = "lBoxSize";
			this.lBoxSize.TabStop = false;
			resources.ApplyResources(this.lBoxFontStyle, "lBoxFontStyle");
			this.lBoxFontStyle.AccessibleRole = System.Windows.Forms.AccessibleRole.List;
			this.lBoxFontStyle.Name = "lBoxFontStyle";
			this.lBoxFontStyle.TabStop = false;
			resources.ApplyResources(this.lBoxFont, "lBoxFont");
			this.lBoxFont.AccessibleRole = System.Windows.Forms.AccessibleRole.List;
			this.lBoxFont.Name = "lBoxFont";
			this.lBoxFont.TabStop = false;
			resources.ApplyResources(this.edtSize, "edtSize");
			this.edtSize.Name = "edtSize";
			this.edtSize.Properties.Appearance.ForeColor = ((System.Drawing.Color)(resources.GetObject("edtSize.Properties.Appearance.ForeColor")));
			this.edtSize.Properties.Appearance.Options.UseForeColor = true;
			resources.ApplyResources(this.lblSize, "lblSize");
			this.lblSize.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblSize.Name = "lblSize";
			resources.ApplyResources(this.edtFontStyle, "edtFontStyle");
			this.edtFontStyle.Name = "edtFontStyle";
			resources.ApplyResources(this.lblFontStyle, "lblFontStyle");
			this.lblFontStyle.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFontStyle.Name = "lblFontStyle";
			resources.ApplyResources(this.edtFont, "edtFont");
			this.edtFont.Name = "edtFont";
			resources.ApplyResources(this.lblFont, "lblFont");
			this.lblFont.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFont.Name = "lblFont";
			this.xtraTabBorder.Controls.Add(this.formatBorderControl);
			this.xtraTabBorder.Controls.Add(this.lblBorderDescription);
			this.xtraTabBorder.Controls.Add(this.btnInside);
			this.xtraTabBorder.Controls.Add(this.btnNone);
			this.xtraTabBorder.Controls.Add(this.btnOutline);
			this.xtraTabBorder.Controls.Add(this.lblBorder);
			this.xtraTabBorder.Controls.Add(this.lblInside);
			this.xtraTabBorder.Controls.Add(this.lblOutline);
			this.xtraTabBorder.Controls.Add(this.lblNone);
			this.xtraTabBorder.Controls.Add(this.lblPresets);
			this.xtraTabBorder.Controls.Add(this.grpLine);
			this.xtraTabBorder.Name = "xtraTabBorder";
			resources.ApplyResources(this.xtraTabBorder, "xtraTabBorder");
			this.formatBorderControl.BottomColor = System.Drawing.Color.Empty;
			this.formatBorderControl.BottomLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.DiagonalColor = System.Drawing.Color.Empty;
			this.formatBorderControl.DiagonalDownLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.DiagonalUpLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.HorizontalColor = System.Drawing.Color.Empty;
			this.formatBorderControl.HorizontalLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.IsBottomBorderChecked = false;
			this.formatBorderControl.IsDiagonalDownBorderChecked = false;
			this.formatBorderControl.IsDiagonalUpBorderChecked = false;
			this.formatBorderControl.IsInsideHorizontalBorderChecked = false;
			this.formatBorderControl.IsInsideVerticalBorderChecked = false;
			this.formatBorderControl.IsLeftBorderChecked = false;
			this.formatBorderControl.IsRightBorderChecked = false;
			this.formatBorderControl.IsTopBorderChecked = false;
			this.formatBorderControl.LeftColor = System.Drawing.Color.Empty;
			this.formatBorderControl.LeftLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			resources.ApplyResources(this.formatBorderControl, "formatBorderControl");
			this.formatBorderControl.Name = "formatBorderControl";
			this.formatBorderControl.RangeType = DevExpress.XtraSpreadsheet.Model.SelectedRangeTypeForBorderPreview.Cell;
			this.formatBorderControl.RightColor = System.Drawing.Color.Empty;
			this.formatBorderControl.RightLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.TopColor = System.Drawing.Color.Empty;
			this.formatBorderControl.TopLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			this.formatBorderControl.VerticalColor = System.Drawing.Color.Empty;
			this.formatBorderControl.VerticalLineStyle = DevExpress.Export.Xl.XlBorderLineStyle.None;
			resources.ApplyResources(this.lblBorderDescription, "lblBorderDescription");
			this.lblBorderDescription.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblBorderDescription.Name = "lblBorderDescription";
			resources.ApplyResources(this.btnInside, "btnInside");
			this.btnInside.Image = ((System.Drawing.Image)(resources.GetObject("btnInside.Image")));
			this.btnInside.ImageLocation = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
			this.btnInside.Name = "btnInside";
			this.btnInside.Click += new System.EventHandler(this.InsideOnClick);
			resources.ApplyResources(this.btnNone, "btnNone");
			this.btnNone.Image = ((System.Drawing.Image)(resources.GetObject("btnNone.Image")));
			this.btnNone.ImageLocation = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
			this.btnNone.Name = "btnNone";
			this.btnNone.Click += new System.EventHandler(this.NoneOnClick);
			resources.ApplyResources(this.btnOutline, "btnOutline");
			this.btnOutline.Image = ((System.Drawing.Image)(resources.GetObject("btnOutline.Image")));
			this.btnOutline.ImageLocation = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
			this.btnOutline.Name = "btnOutline";
			this.btnOutline.Click += new System.EventHandler(this.OutlineOnClick);
			resources.ApplyResources(this.lblBorder, "lblBorder");
			this.lblBorder.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblBorder.LineVisible = true;
			this.lblBorder.Name = "lblBorder";
			resources.ApplyResources(this.lblInside, "lblInside");
			this.lblInside.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblInside.Name = "lblInside";
			resources.ApplyResources(this.lblOutline, "lblOutline");
			this.lblOutline.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblOutline.Name = "lblOutline";
			resources.ApplyResources(this.lblNone, "lblNone");
			this.lblNone.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblNone.Name = "lblNone";
			resources.ApplyResources(this.lblPresets, "lblPresets");
			this.lblPresets.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPresets.LineVisible = true;
			this.lblPresets.Name = "lblPresets";
			resources.ApplyResources(this.grpLine, "grpLine");
			this.grpLine.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
			this.grpLine.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("grpLine.Appearance.BackColor")));
			this.grpLine.Appearance.Options.UseBackColor = true;
			this.grpLine.Controls.Add(this.edtColorBorder);
			this.grpLine.Controls.Add(this.lblColorBorder);
			this.grpLine.Controls.Add(this.lblStyle);
			this.grpLine.Controls.Add(this.lbBorderLineStyle);
			this.grpLine.Name = "grpLine";
			resources.ApplyResources(this.edtColorBorder, "edtColorBorder");
			this.edtColorBorder.Name = "edtColorBorder";
			this.edtColorBorder.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
			this.edtColorBorder.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtColorBorder.Properties.Buttons"))))});
			this.edtColorBorder.Properties.ColorAlignment = DevExpress.Utils.HorzAlignment.Center;
			this.edtColorBorder.Properties.NullText = resources.GetString("edtColorBorder.Properties.NullText");
			this.edtColorBorder.Properties.ShowSystemColors = false;
			this.edtColorBorder.Properties.ShowWebColors = false;
			resources.ApplyResources(this.lblColorBorder, "lblColorBorder");
			this.lblColorBorder.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblColorBorder.Name = "lblColorBorder";
			resources.ApplyResources(this.lblStyle, "lblStyle");
			this.lblStyle.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblStyle.Name = "lblStyle";
			this.lbBorderLineStyle.ColumnWidth = 70;
			this.lbBorderLineStyle.DocumentModel = null;
			resources.ApplyResources(this.lbBorderLineStyle, "lbBorderLineStyle");
			this.lbBorderLineStyle.MultiColumn = true;
			this.lbBorderLineStyle.Name = "lbBorderLineStyle";
			this.xtraTabFill.Controls.Add(this.chkNoColor);
			this.xtraTabFill.Controls.Add(this.lblBackgroundColor);
			this.xtraTabFill.Controls.Add(this.edtPatternColor);
			this.xtraTabFill.Controls.Add(this.lblPatternColor);
			this.xtraTabFill.Controls.Add(this.edtPatternStyle);
			this.xtraTabFill.Controls.Add(this.lblPatternStyle);
			this.xtraTabFill.Controls.Add(this.grpFillSample);
			this.xtraTabFill.Controls.Add(this.edtBackColor);
			this.xtraTabFill.Name = "xtraTabFill";
			resources.ApplyResources(this.xtraTabFill, "xtraTabFill");
			resources.ApplyResources(this.chkNoColor, "chkNoColor");
			this.chkNoColor.Name = "chkNoColor";
			resources.ApplyResources(this.lblBackgroundColor, "lblBackgroundColor");
			this.lblBackgroundColor.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblBackgroundColor.Name = "lblBackgroundColor";
			resources.ApplyResources(this.edtPatternColor, "edtPatternColor");
			this.edtPatternColor.Name = "edtPatternColor";
			this.edtPatternColor.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtPatternColor.Properties.Buttons"))))});
			this.edtPatternColor.Properties.ColorAlignment = DevExpress.Utils.HorzAlignment.Center;
			this.edtPatternColor.Properties.ShowSystemColors = false;
			this.edtPatternColor.Properties.ShowWebColors = false;
			resources.ApplyResources(this.lblPatternColor, "lblPatternColor");
			this.lblPatternColor.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPatternColor.Name = "lblPatternColor";
			resources.ApplyResources(this.edtPatternStyle, "edtPatternStyle");
			this.edtPatternStyle.Name = "edtPatternStyle";
			this.edtPatternStyle.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtPatternStyle.Properties.Buttons"))))});
			this.edtPatternStyle.Properties.DropDownRows = 3;
			this.edtPatternStyle.Properties.ShowPopupShadow = false;
			resources.ApplyResources(this.lblPatternStyle, "lblPatternStyle");
			this.lblPatternStyle.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPatternStyle.Name = "lblPatternStyle";
			resources.ApplyResources(this.grpFillSample, "grpFillSample");
			this.grpFillSample.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
			this.grpFillSample.Controls.Add(this.drawPatternType);
			this.grpFillSample.Name = "grpFillSample";
			this.drawPatternType.Appearance.BackColor = ((System.Drawing.Color)(resources.GetObject("drawPatternType.Appearance.BackColor")));
			this.drawPatternType.Appearance.Options.UseBackColor = true;
			resources.ApplyResources(this.drawPatternType, "drawPatternType");
			this.drawPatternType.Name = "drawPatternType";
			resources.ApplyResources(this.edtBackColor, "edtBackColor");
			this.edtBackColor.Name = "edtBackColor";
			this.edtBackColor.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtBackColor.Properties.Buttons"))))});
			this.edtBackColor.Properties.ColorAlignment = DevExpress.Utils.HorzAlignment.Center;
			this.edtBackColor.Properties.ColorDialogOptions.AllowTransparency = false;
			this.edtBackColor.Properties.ShowSystemColors = false;
			this.edtBackColor.Properties.ShowWebColors = false;
			this.xtraTabProtection.Controls.Add(this.lblProtection);
			this.xtraTabProtection.Controls.Add(this.chkHidden);
			this.xtraTabProtection.Controls.Add(this.chkLocked);
			this.xtraTabProtection.Name = "xtraTabProtection";
			resources.ApplyResources(this.xtraTabProtection, "xtraTabProtection");
			resources.ApplyResources(this.lblProtection, "lblProtection");
			this.lblProtection.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblProtection.Name = "lblProtection";
			this.chkHidden.CausesValidation = false;
			resources.ApplyResources(this.chkHidden, "chkHidden");
			this.chkHidden.Name = "chkHidden";
			this.chkHidden.Properties.AutoWidth = true;
			this.chkHidden.Properties.Caption = resources.GetString("chkHidden.Properties.Caption");
			this.chkLocked.CausesValidation = false;
			resources.ApplyResources(this.chkLocked, "chkLocked");
			this.chkLocked.Name = "chkLocked";
			this.chkLocked.Properties.AutoWidth = true;
			this.chkLocked.Properties.Caption = resources.GetString("chkLocked.Properties.Caption");
			resources.ApplyResources(this.btnOk, "btnOk");
			this.btnOk.Name = "btnOk";
			this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
			this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			resources.ApplyResources(this.btnCancel, "btnCancel");
			this.btnCancel.Name = "btnCancel";
			this.AcceptButton = this.btnOk;
			resources.ApplyResources(this, "$this");
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.btnCancel;
			this.Controls.Add(this.btnCancel);
			this.Controls.Add(this.btnOk);
			this.Controls.Add(this.tabControl);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "FormatCellsForm";
			this.ShowInTaskbar = false;
			this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
			((System.ComponentModel.ISupportInitialize)(this.tabControl)).EndInit();
			this.tabControl.ResumeLayout(false);
			this.xtraTabNumber.ResumeLayout(false);
			this.xtraTabNumber.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grpNumberSample)).EndInit();
			this.grpNumberSample.ResumeLayout(false);
			this.grpNumberSample.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.lBoxNumberCategory)).EndInit();
			this.xtraTabAlignment.ResumeLayout(false);
			this.xtraTabAlignment.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtVerticalAlignment.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtHorizontalAlignment.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTextDirection.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grpOrientation)).EndInit();
			this.grpOrientation.ResumeLayout(false);
			this.grpOrientation.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtDegrees.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkWrapText.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShrinkToFit.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMergeCells.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkJustifyDistributed.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtIndent.Properties)).EndInit();
			this.xtraTabFont.ResumeLayout(false);
			this.xtraTabFont.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtColorFont.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grpPreview)).EndInit();
			this.grpPreview.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chkNormalFont.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grpEffects)).EndInit();
			this.grpEffects.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chkSubscript.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSuperscript.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkStrikeThrough.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtUnderline.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxSize)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxFontStyle)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lBoxFont)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtSize.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFontStyle.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtFont.Properties)).EndInit();
			this.xtraTabBorder.ResumeLayout(false);
			this.xtraTabBorder.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.grpLine)).EndInit();
			this.grpLine.ResumeLayout(false);
			this.grpLine.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtColorBorder.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.lbBorderLineStyle)).EndInit();
			this.xtraTabFill.ResumeLayout(false);
			this.xtraTabFill.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtPatternColor.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPatternStyle.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.grpFillSample)).EndInit();
			this.grpFillSample.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.drawPatternType)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtBackColor.Properties)).EndInit();
			this.xtraTabProtection.ResumeLayout(false);
			this.xtraTabProtection.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkHidden.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkLocked.Properties)).EndInit();
			this.ResumeLayout(false);
		}
		#endregion
		XtraEditors.SimpleButton btnOk;
		XtraEditors.SimpleButton btnCancel;
		DevExpress.XtraTab.XtraTabControl tabControl;
		DevExpress.XtraTab.XtraTabPage xtraTabNumber;
		DevExpress.XtraTab.XtraTabPage xtraTabAlignment;
		DevExpress.XtraTab.XtraTabPage xtraTabFont;
		DevExpress.XtraTab.XtraTabPage xtraTabBorder;
		DevExpress.XtraTab.XtraTabPage xtraTabFill;
		DevExpress.XtraTab.XtraTabPage xtraTabProtection;
		DevExpress.XtraEditors.ListBoxControl lBoxNumberCategory;
		DevExpress.XtraEditors.LabelControl lbCategory;
		private XtraEditors.CheckEdit chkWrapText;
		private XtraEditors.CheckEdit chkShrinkToFit;
		private XtraEditors.CheckEdit chkMergeCells;
		private XtraEditors.CheckEdit chkJustifyDistributed;
		private XtraEditors.SpinEdit edtDegrees;
		private XtraEditors.LabelControl lblTextDirectoin;
		private XtraEditors.LabelControl lblDegrees;
		private XtraEditors.LabelControl lblIndent;
		private XtraEditors.LabelControl lblVertical;
		private XtraEditors.LabelControl lblHorizontal;
		private XtraEditors.LabelControl lblRightToLeft;
		private XtraEditors.LabelControl lblTextControl;
		private XtraEditors.LabelControl lblTextAlignmet;
		private XtraEditors.SpinEdit edtIndent;
		private XtraEditors.LookUpEdit edtVerticalAlignment;
		private XtraEditors.LookUpEdit edtTextDirection;
		private XtraEditors.LabelControl lblFont;
		private XtraEditors.TextEdit edtSize;
		private XtraEditors.LabelControl lblSize;
		private XtraEditors.TextEdit edtFontStyle;
		private XtraEditors.LabelControl lblFontStyle;
		private XtraEditors.TextEdit edtFont;
		private XtraEditors.ListBoxControl lBoxSize;
		private XtraEditors.ListBoxControl lBoxFontStyle;
		private XtraEditors.ListBoxControl lBoxFont;
		private XtraEditors.LookUpEdit edtUnderline;
		private XtraEditors.LabelControl lblUnderline;
		private XtraEditors.GroupControl grpEffects;
		private XtraEditors.CheckEdit chkSubscript;
		private XtraEditors.CheckEdit chkSuperscript;
		private XtraEditors.CheckEdit chkStrikeThrough;
		private XtraEditors.GroupControl grpPreview;
		private XtraEditors.CheckEdit chkNormalFont;
		private XtraEditors.LabelControl lblColorFont;
		private XtraEditors.LookUpEdit edtHorizontalAlignment;
		private XtraEditors.ColorPickEdit edtColorFont;
		private XtraEditors.LabelControl lblPresets;
		private XtraEditors.LabelControl lblNone;
		private XtraEditors.LabelControl lblInside;
		private XtraEditors.LabelControl lblOutline;
		private XtraEditors.LabelControl lblBorder;
		private XtraEditors.SimpleButton btnOutline;
		private XtraEditors.SimpleButton btnNone;
		private XtraEditors.SimpleButton btnInside;
		private XtraEditors.CheckEdit chkHidden;
		private XtraEditors.CheckEdit chkLocked;
		private XtraEditors.LabelControl lblProtection;
		private XtraEditors.LabelControl lblBorderDescription;
		private XtraEditors.LabelControl lblFontDescription;
		private Design.FormatBorderControl formatBorderControl;
		private XtraEditors.GroupControl grpLine;
		private XtraEditors.ColorPickEdit edtColorBorder;
		private XtraEditors.LabelControl lblColorBorder;
		private XtraEditors.LabelControl lblStyle;
		private BorderLineStyleListBox lbBorderLineStyle;
		private XtraEditors.GroupControl grpFillSample;
		private XtraEditors.ColorPickEdit edtBackColor;
		private XtraEditors.LabelControl lblPatternStyle;
		private PatternStyleImageComboBoxEdit edtPatternStyle;
		private XtraEditors.LabelControl lblBackgroundColor;
		private XtraEditors.ColorPickEdit edtPatternColor;
		private XtraEditors.LabelControl lblPatternColor;
		private XtraEditors.GroupControl grpOrientation;
		private XtraEditors.CheckButton chkNoColor;
		private XtraRichEdit.Forms.SimpleRichEditControl edtFontPreview;
		private XtraEditors.GroupControl grpNumberSample;
		private XtraEditors.LabelControl lblNumberSample;
		private Design.FormatNumberDecimalControl formatNumberDecimalControl;
		private Design.FormatNumberTypeControl formatNumberTypeControl;
		private XtraEditors.LabelControl lblNumberDescription;
		private XtraEditors.LabelControl lblCategoryDescription;
		private Design.FormatNumberCustomControl formatNumberCustomControl;
		private XtraEditors.PanelControl drawPatternType;
	}
}
