#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

namespace DevExpress.XtraSpreadsheet.Forms {
	partial class OptionsPivotTableForm {
		private System.ComponentModel.IContainer components = null;
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		#region Windows Form Designer generated code
		private void InitializeComponent() {
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OptionsPivotTableForm));
			this.tabControl = new DevExpress.XtraTab.XtraTabControl();
			this.xtraTabLayoutAndFormat = new DevExpress.XtraTab.XtraTabPage();
			this.lblRow = new DevExpress.XtraEditors.LabelControl();
			this.lblColumn = new DevExpress.XtraEditors.LabelControl();
			this.edtFieldsReportFilterArea = new DevExpress.XtraEditors.LookUpEdit();
			this.chkPreserveCellFormatting = new DevExpress.XtraEditors.CheckEdit();
			this.chkAutofitColumnWidths = new DevExpress.XtraEditors.CheckEdit();
			this.lblSeparator2 = new DevExpress.XtraEditors.LabelControl();
			this.chkEmptyCellsShow = new DevExpress.XtraEditors.CheckEdit();
			this.chkErrorValuesShow = new DevExpress.XtraEditors.CheckEdit();
			this.edtEmptyCellsShow = new DevExpress.XtraEditors.TextEdit();
			this.edtErrorValuesShow = new DevExpress.XtraEditors.TextEdit();
			this.lblFormat = new DevExpress.XtraEditors.LabelControl();
			this.lblReportFilterFields = new DevExpress.XtraEditors.LabelControl();
			this.edtReportFilterFields = new DevExpress.XtraEditors.SpinEdit();
			this.lblFieldsReportFilterArea = new DevExpress.XtraEditors.LabelControl();
			this.lblSeparator1 = new DevExpress.XtraEditors.LabelControl();
			this.lblCharacters = new DevExpress.XtraEditors.LabelControl();
			this.edtIndentRowLabels = new DevExpress.XtraEditors.SpinEdit();
			this.lblIndentRowLabels = new DevExpress.XtraEditors.LabelControl();
			this.chkMergeAndCenterCells = new DevExpress.XtraEditors.CheckEdit();
			this.lblLayout = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabTotalsAndFilters = new DevExpress.XtraTab.XtraTabPage();
			this.chkUseCustomLists = new DevExpress.XtraEditors.CheckEdit();
			this.lblSorting = new DevExpress.XtraEditors.LabelControl();
			this.chkMultipleFiltersField = new DevExpress.XtraEditors.CheckEdit();
			this.chkSubtotalFilteredItems = new DevExpress.XtraEditors.CheckEdit();
			this.lblFilters = new DevExpress.XtraEditors.LabelControl();
			this.chkGrandTotalsColumns = new DevExpress.XtraEditors.CheckEdit();
			this.chkGrandTotalsRows = new DevExpress.XtraEditors.CheckEdit();
			this.lblGrandTotals = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabDisplay = new DevExpress.XtraTab.XtraTabPage();
			this.rgrpSort = new DevExpress.XtraEditors.RadioGroup();
			this.lblFieldList = new DevExpress.XtraEditors.LabelControl();
			this.chkDisplayItemLabels = new DevExpress.XtraEditors.CheckEdit();
			this.lblSeparator6 = new DevExpress.XtraEditors.LabelControl();
			this.chkShowItemsWithNoDataOnColumns = new DevExpress.XtraEditors.CheckEdit();
			this.chkShowItemsWithNoDataOnRows = new DevExpress.XtraEditors.CheckEdit();
			this.lblSeparator5 = new DevExpress.XtraEditors.LabelControl();
			this.chkShowTheValuesRow = new DevExpress.XtraEditors.CheckEdit();
			this.chkDisplayFieldAndFilter = new DevExpress.XtraEditors.CheckEdit();
			this.lblSeparator4 = new DevExpress.XtraEditors.LabelControl();
			this.chkShowPropertiesInTooltips = new DevExpress.XtraEditors.CheckEdit();
			this.chkShowContextualTooltips = new DevExpress.XtraEditors.CheckEdit();
			this.lblSeparator3 = new DevExpress.XtraEditors.LabelControl();
			this.chkShowExpandCollapseButtons = new DevExpress.XtraEditors.CheckEdit();
			this.lblDisplay = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabPrinting = new DevExpress.XtraTab.XtraTabPage();
			this.chkSetPrintTitles = new DevExpress.XtraEditors.CheckEdit();
			this.chkRepeatRowLabels = new DevExpress.XtraEditors.CheckEdit();
			this.chkPrintExpandColapseButtons = new DevExpress.XtraEditors.CheckEdit();
			this.lblPrint = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabData = new DevExpress.XtraTab.XtraTabPage();
			this.edtNumberOfItems = new DevExpress.XtraEditors.LookUpEdit();
			this.chkEnableCellEditing = new DevExpress.XtraEditors.CheckEdit();
			this.lblWhatIfAnalysis = new DevExpress.XtraEditors.LabelControl();
			this.lblNumberOfItems = new DevExpress.XtraEditors.LabelControl();
			this.lblRetainItemsDeletedFromTheDataSource = new DevExpress.XtraEditors.LabelControl();
			this.chkRerfeshData = new DevExpress.XtraEditors.CheckEdit();
			this.chkEnableShowDetails = new DevExpress.XtraEditors.CheckEdit();
			this.chkSaveSourceDataWithFile = new DevExpress.XtraEditors.CheckEdit();
			this.lblPivotTableData = new DevExpress.XtraEditors.LabelControl();
			this.xtraTabAltText = new DevExpress.XtraTab.XtraTabPage();
			this.lblAltText = new DevExpress.XtraEditors.LabelControl();
			this.edtDecsription = new DevExpress.XtraEditors.MemoEdit();
			this.lblDescription = new DevExpress.XtraEditors.LabelControl();
			this.edtTitle = new DevExpress.XtraEditors.TextEdit();
			this.lblTitle = new DevExpress.XtraEditors.LabelControl();
			this.btnCancel = new DevExpress.XtraEditors.SimpleButton();
			this.btnOk = new DevExpress.XtraEditors.SimpleButton();
			this.lblPivotTableName = new DevExpress.XtraEditors.LabelControl();
			this.edtPivotTableName = new DevExpress.XtraEditors.TextEdit();
			((System.ComponentModel.ISupportInitialize)(this.tabControl)).BeginInit();
			this.tabControl.SuspendLayout();
			this.xtraTabLayoutAndFormat.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtFieldsReportFilterArea.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkPreserveCellFormatting.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkAutofitColumnWidths.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEmptyCellsShow.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkErrorValuesShow.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtEmptyCellsShow.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtErrorValuesShow.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtReportFilterFields.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtIndentRowLabels.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMergeAndCenterCells.Properties)).BeginInit();
			this.xtraTabTotalsAndFilters.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkUseCustomLists.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMultipleFiltersField.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSubtotalFilteredItems.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkGrandTotalsColumns.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkGrandTotalsRows.Properties)).BeginInit();
			this.xtraTabDisplay.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.rgrpSort.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkDisplayItemLabels.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowItemsWithNoDataOnColumns.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowItemsWithNoDataOnRows.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowTheValuesRow.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkDisplayFieldAndFilter.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowPropertiesInTooltips.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowContextualTooltips.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowExpandCollapseButtons.Properties)).BeginInit();
			this.xtraTabPrinting.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chkSetPrintTitles.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkRepeatRowLabels.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkPrintExpandColapseButtons.Properties)).BeginInit();
			this.xtraTabData.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtNumberOfItems.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEnableCellEditing.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkRerfeshData.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEnableShowDetails.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSaveSourceDataWithFile.Properties)).BeginInit();
			this.xtraTabAltText.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtDecsription.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTitle.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPivotTableName.Properties)).BeginInit();
			this.SuspendLayout();
			resources.ApplyResources(this.tabControl, "tabControl");
			this.tabControl.Name = "tabControl";
			this.tabControl.SelectedTabPage = this.xtraTabLayoutAndFormat;
			this.tabControl.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
			this.xtraTabLayoutAndFormat,
			this.xtraTabTotalsAndFilters,
			this.xtraTabDisplay,
			this.xtraTabPrinting,
			this.xtraTabData,
			this.xtraTabAltText});
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblRow);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblColumn);
			this.xtraTabLayoutAndFormat.Controls.Add(this.edtFieldsReportFilterArea);
			this.xtraTabLayoutAndFormat.Controls.Add(this.chkPreserveCellFormatting);
			this.xtraTabLayoutAndFormat.Controls.Add(this.chkAutofitColumnWidths);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblSeparator2);
			this.xtraTabLayoutAndFormat.Controls.Add(this.chkEmptyCellsShow);
			this.xtraTabLayoutAndFormat.Controls.Add(this.chkErrorValuesShow);
			this.xtraTabLayoutAndFormat.Controls.Add(this.edtEmptyCellsShow);
			this.xtraTabLayoutAndFormat.Controls.Add(this.edtErrorValuesShow);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblFormat);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblReportFilterFields);
			this.xtraTabLayoutAndFormat.Controls.Add(this.edtReportFilterFields);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblFieldsReportFilterArea);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblSeparator1);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblCharacters);
			this.xtraTabLayoutAndFormat.Controls.Add(this.edtIndentRowLabels);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblIndentRowLabels);
			this.xtraTabLayoutAndFormat.Controls.Add(this.chkMergeAndCenterCells);
			this.xtraTabLayoutAndFormat.Controls.Add(this.lblLayout);
			this.xtraTabLayoutAndFormat.Name = "xtraTabLayoutAndFormat";
			resources.ApplyResources(this.xtraTabLayoutAndFormat, "xtraTabLayoutAndFormat");
			resources.ApplyResources(this.lblRow, "lblRow");
			this.lblRow.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblRow.Name = "lblRow";
			resources.ApplyResources(this.lblColumn, "lblColumn");
			this.lblColumn.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblColumn.Name = "lblColumn";
			resources.ApplyResources(this.edtFieldsReportFilterArea, "edtFieldsReportFilterArea");
			this.edtFieldsReportFilterArea.Name = "edtFieldsReportFilterArea";
			this.edtFieldsReportFilterArea.Properties.AccessibleName = resources.GetString("edtFieldsReportFilterArea.Properties.AccessibleName");
			this.edtFieldsReportFilterArea.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.ComboBox;
			this.edtFieldsReportFilterArea.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtFieldsReportFilterArea.Properties.Buttons"))))});
			this.edtFieldsReportFilterArea.Properties.NullText = resources.GetString("edtFieldsReportFilterArea.Properties.NullText");
			this.edtFieldsReportFilterArea.Properties.ShowFooter = false;
			this.edtFieldsReportFilterArea.Properties.ShowHeader = false;
			resources.ApplyResources(this.chkPreserveCellFormatting, "chkPreserveCellFormatting");
			this.chkPreserveCellFormatting.Name = "chkPreserveCellFormatting";
			this.chkPreserveCellFormatting.Properties.AccessibleName = resources.GetString("chkPreserveCellFormatting.Properties.AccessibleName");
			this.chkPreserveCellFormatting.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkPreserveCellFormatting.Properties.Caption = resources.GetString("chkPreserveCellFormatting.Properties.Caption");
			resources.ApplyResources(this.chkAutofitColumnWidths, "chkAutofitColumnWidths");
			this.chkAutofitColumnWidths.Name = "chkAutofitColumnWidths";
			this.chkAutofitColumnWidths.Properties.AccessibleName = resources.GetString("chkAutofitColumnWidths.Properties.AccessibleName");
			this.chkAutofitColumnWidths.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkAutofitColumnWidths.Properties.Caption = resources.GetString("chkAutofitColumnWidths.Properties.Caption");
			this.lblSeparator2.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			resources.ApplyResources(this.lblSeparator2, "lblSeparator2");
			this.lblSeparator2.LineVisible = true;
			this.lblSeparator2.Name = "lblSeparator2";
			resources.ApplyResources(this.chkEmptyCellsShow, "chkEmptyCellsShow");
			this.chkEmptyCellsShow.Name = "chkEmptyCellsShow";
			this.chkEmptyCellsShow.Properties.AccessibleName = resources.GetString("chkEmptyCellsShow.Properties.AccessibleName");
			this.chkEmptyCellsShow.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkEmptyCellsShow.Properties.Caption = resources.GetString("chkEmptyCellsShow.Properties.Caption");
			resources.ApplyResources(this.chkErrorValuesShow, "chkErrorValuesShow");
			this.chkErrorValuesShow.Name = "chkErrorValuesShow";
			this.chkErrorValuesShow.Properties.AccessibleName = resources.GetString("chkErrorValuesShow.Properties.AccessibleName");
			this.chkErrorValuesShow.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkErrorValuesShow.Properties.Caption = resources.GetString("chkErrorValuesShow.Properties.Caption");
			resources.ApplyResources(this.edtEmptyCellsShow, "edtEmptyCellsShow");
			this.edtEmptyCellsShow.Name = "edtEmptyCellsShow";
			this.edtEmptyCellsShow.Properties.AccessibleName = resources.GetString("edtEmptyCellsShow.Properties.AccessibleName");
			this.edtEmptyCellsShow.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			resources.ApplyResources(this.edtErrorValuesShow, "edtErrorValuesShow");
			this.edtErrorValuesShow.Name = "edtErrorValuesShow";
			this.edtErrorValuesShow.Properties.AccessibleName = resources.GetString("edtErrorValuesShow.Properties.AccessibleName");
			this.edtErrorValuesShow.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			resources.ApplyResources(this.lblFormat, "lblFormat");
			this.lblFormat.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFormat.LineVisible = true;
			this.lblFormat.Name = "lblFormat";
			resources.ApplyResources(this.lblReportFilterFields, "lblReportFilterFields");
			this.lblReportFilterFields.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblReportFilterFields.Name = "lblReportFilterFields";
			resources.ApplyResources(this.edtReportFilterFields, "edtReportFilterFields");
			this.edtReportFilterFields.Name = "edtReportFilterFields";
			this.edtReportFilterFields.Properties.AccessibleName = resources.GetString("edtReportFilterFields.Properties.AccessibleName");
			this.edtReportFilterFields.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.SpinButton;
			this.edtReportFilterFields.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtReportFilterFields.Properties.Buttons"))))});
			this.edtReportFilterFields.Properties.Mask.EditMask = resources.GetString("edtReportFilterFields.Properties.Mask.EditMask");
			resources.ApplyResources(this.lblFieldsReportFilterArea, "lblFieldsReportFilterArea");
			this.lblFieldsReportFilterArea.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFieldsReportFilterArea.Name = "lblFieldsReportFilterArea";
			this.lblSeparator1.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			resources.ApplyResources(this.lblSeparator1, "lblSeparator1");
			this.lblSeparator1.LineVisible = true;
			this.lblSeparator1.Name = "lblSeparator1";
			resources.ApplyResources(this.lblCharacters, "lblCharacters");
			this.lblCharacters.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblCharacters.Name = "lblCharacters";
			resources.ApplyResources(this.edtIndentRowLabels, "edtIndentRowLabels");
			this.edtIndentRowLabels.Name = "edtIndentRowLabels";
			this.edtIndentRowLabels.Properties.AccessibleName = resources.GetString("edtIndentRowLabels.Properties.AccessibleName");
			this.edtIndentRowLabels.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.SpinButton;
			this.edtIndentRowLabels.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtIndentRowLabels.Properties.Buttons"))))});
			this.edtIndentRowLabels.Properties.Mask.EditMask = resources.GetString("edtIndentRowLabels.Properties.Mask.EditMask");
			resources.ApplyResources(this.lblIndentRowLabels, "lblIndentRowLabels");
			this.lblIndentRowLabels.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblIndentRowLabels.Name = "lblIndentRowLabels";
			resources.ApplyResources(this.chkMergeAndCenterCells, "chkMergeAndCenterCells");
			this.chkMergeAndCenterCells.Name = "chkMergeAndCenterCells";
			this.chkMergeAndCenterCells.Properties.AccessibleName = resources.GetString("chkMergeAndCenterCells.Properties.AccessibleName");
			this.chkMergeAndCenterCells.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkMergeAndCenterCells.Properties.Caption = resources.GetString("chkMergeAndCenterCells.Properties.Caption");
			resources.ApplyResources(this.lblLayout, "lblLayout");
			this.lblLayout.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblLayout.LineVisible = true;
			this.lblLayout.Name = "lblLayout";
			this.xtraTabTotalsAndFilters.Controls.Add(this.chkUseCustomLists);
			this.xtraTabTotalsAndFilters.Controls.Add(this.lblSorting);
			this.xtraTabTotalsAndFilters.Controls.Add(this.chkMultipleFiltersField);
			this.xtraTabTotalsAndFilters.Controls.Add(this.chkSubtotalFilteredItems);
			this.xtraTabTotalsAndFilters.Controls.Add(this.lblFilters);
			this.xtraTabTotalsAndFilters.Controls.Add(this.chkGrandTotalsColumns);
			this.xtraTabTotalsAndFilters.Controls.Add(this.chkGrandTotalsRows);
			this.xtraTabTotalsAndFilters.Controls.Add(this.lblGrandTotals);
			this.xtraTabTotalsAndFilters.Name = "xtraTabTotalsAndFilters";
			resources.ApplyResources(this.xtraTabTotalsAndFilters, "xtraTabTotalsAndFilters");
			resources.ApplyResources(this.chkUseCustomLists, "chkUseCustomLists");
			this.chkUseCustomLists.Name = "chkUseCustomLists";
			this.chkUseCustomLists.Properties.AccessibleName = resources.GetString("chkUseCustomLists.Properties.AccessibleName");
			this.chkUseCustomLists.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkUseCustomLists.Properties.Caption = resources.GetString("chkUseCustomLists.Properties.Caption");
			resources.ApplyResources(this.lblSorting, "lblSorting");
			this.lblSorting.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblSorting.LineVisible = true;
			this.lblSorting.Name = "lblSorting";
			resources.ApplyResources(this.chkMultipleFiltersField, "chkMultipleFiltersField");
			this.chkMultipleFiltersField.Name = "chkMultipleFiltersField";
			this.chkMultipleFiltersField.Properties.AccessibleName = resources.GetString("chkMultipleFiltersField.Properties.AccessibleName");
			this.chkMultipleFiltersField.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.chkMultipleFiltersField.Properties.Caption = resources.GetString("chkMultipleFiltersField.Properties.Caption");
			resources.ApplyResources(this.chkSubtotalFilteredItems, "chkSubtotalFilteredItems");
			this.chkSubtotalFilteredItems.Name = "chkSubtotalFilteredItems";
			this.chkSubtotalFilteredItems.Properties.AccessibleName = resources.GetString("chkSubtotalFilteredItems.Properties.AccessibleName");
			this.chkSubtotalFilteredItems.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkSubtotalFilteredItems.Properties.Caption = resources.GetString("chkSubtotalFilteredItems.Properties.Caption");
			resources.ApplyResources(this.lblFilters, "lblFilters");
			this.lblFilters.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFilters.LineVisible = true;
			this.lblFilters.Name = "lblFilters";
			resources.ApplyResources(this.chkGrandTotalsColumns, "chkGrandTotalsColumns");
			this.chkGrandTotalsColumns.Name = "chkGrandTotalsColumns";
			this.chkGrandTotalsColumns.Properties.AccessibleName = resources.GetString("chkGrandTotalsColumns.Properties.AccessibleName");
			this.chkGrandTotalsColumns.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkGrandTotalsColumns.Properties.Caption = resources.GetString("chkGrandTotalsColumns.Properties.Caption");
			resources.ApplyResources(this.chkGrandTotalsRows, "chkGrandTotalsRows");
			this.chkGrandTotalsRows.Name = "chkGrandTotalsRows";
			this.chkGrandTotalsRows.Properties.AccessibleName = resources.GetString("chkGrandTotalsRows.Properties.AccessibleName");
			this.chkGrandTotalsRows.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkGrandTotalsRows.Properties.Caption = resources.GetString("chkGrandTotalsRows.Properties.Caption");
			resources.ApplyResources(this.lblGrandTotals, "lblGrandTotals");
			this.lblGrandTotals.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblGrandTotals.LineVisible = true;
			this.lblGrandTotals.Name = "lblGrandTotals";
			this.xtraTabDisplay.Controls.Add(this.rgrpSort);
			this.xtraTabDisplay.Controls.Add(this.lblFieldList);
			this.xtraTabDisplay.Controls.Add(this.chkDisplayItemLabels);
			this.xtraTabDisplay.Controls.Add(this.lblSeparator6);
			this.xtraTabDisplay.Controls.Add(this.chkShowItemsWithNoDataOnColumns);
			this.xtraTabDisplay.Controls.Add(this.chkShowItemsWithNoDataOnRows);
			this.xtraTabDisplay.Controls.Add(this.lblSeparator5);
			this.xtraTabDisplay.Controls.Add(this.chkShowTheValuesRow);
			this.xtraTabDisplay.Controls.Add(this.chkDisplayFieldAndFilter);
			this.xtraTabDisplay.Controls.Add(this.lblSeparator4);
			this.xtraTabDisplay.Controls.Add(this.chkShowPropertiesInTooltips);
			this.xtraTabDisplay.Controls.Add(this.chkShowContextualTooltips);
			this.xtraTabDisplay.Controls.Add(this.lblSeparator3);
			this.xtraTabDisplay.Controls.Add(this.chkShowExpandCollapseButtons);
			this.xtraTabDisplay.Controls.Add(this.lblDisplay);
			this.xtraTabDisplay.Name = "xtraTabDisplay";
			resources.ApplyResources(this.xtraTabDisplay, "xtraTabDisplay");
			resources.ApplyResources(this.rgrpSort, "rgrpSort");
			this.rgrpSort.Name = "rgrpSort";
			this.rgrpSort.Properties.AccessibleName = resources.GetString("rgrpSort.Properties.AccessibleName");
			this.rgrpSort.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.RadioButton;
			this.rgrpSort.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
			this.rgrpSort.Properties.Items.AddRange(new DevExpress.XtraEditors.Controls.RadioGroupItem[] {
			new DevExpress.XtraEditors.Controls.RadioGroupItem(((object)(resources.GetObject("rgrpSort.Properties.Items"))), resources.GetString("rgrpSort.Properties.Items1")),
			new DevExpress.XtraEditors.Controls.RadioGroupItem(((object)(resources.GetObject("rgrpSort.Properties.Items2"))), resources.GetString("rgrpSort.Properties.Items3"))});
			resources.ApplyResources(this.lblFieldList, "lblFieldList");
			this.lblFieldList.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblFieldList.LineVisible = true;
			this.lblFieldList.Name = "lblFieldList";
			resources.ApplyResources(this.chkDisplayItemLabels, "chkDisplayItemLabels");
			this.chkDisplayItemLabels.Name = "chkDisplayItemLabels";
			this.chkDisplayItemLabels.Properties.AccessibleName = resources.GetString("chkDisplayItemLabels.Properties.AccessibleName");
			this.chkDisplayItemLabels.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkDisplayItemLabels.Properties.Caption = resources.GetString("chkDisplayItemLabels.Properties.Caption");
			resources.ApplyResources(this.lblSeparator6, "lblSeparator6");
			this.lblSeparator6.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			this.lblSeparator6.LineVisible = true;
			this.lblSeparator6.Name = "lblSeparator6";
			resources.ApplyResources(this.chkShowItemsWithNoDataOnColumns, "chkShowItemsWithNoDataOnColumns");
			this.chkShowItemsWithNoDataOnColumns.Name = "chkShowItemsWithNoDataOnColumns";
			this.chkShowItemsWithNoDataOnColumns.Properties.AccessibleName = resources.GetString("chkShowItemsWithNoDataOnColumns.Properties.AccessibleName");
			this.chkShowItemsWithNoDataOnColumns.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowItemsWithNoDataOnColumns.Properties.Caption = resources.GetString("chkShowItemsWithNoDataOnColumns.Properties.Caption");
			resources.ApplyResources(this.chkShowItemsWithNoDataOnRows, "chkShowItemsWithNoDataOnRows");
			this.chkShowItemsWithNoDataOnRows.Name = "chkShowItemsWithNoDataOnRows";
			this.chkShowItemsWithNoDataOnRows.Properties.AccessibleName = resources.GetString("chkShowItemsWithNoDataOnRows.Properties.AccessibleName");
			this.chkShowItemsWithNoDataOnRows.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowItemsWithNoDataOnRows.Properties.Caption = resources.GetString("chkShowItemsWithNoDataOnRows.Properties.Caption");
			resources.ApplyResources(this.lblSeparator5, "lblSeparator5");
			this.lblSeparator5.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			this.lblSeparator5.LineVisible = true;
			this.lblSeparator5.Name = "lblSeparator5";
			resources.ApplyResources(this.chkShowTheValuesRow, "chkShowTheValuesRow");
			this.chkShowTheValuesRow.Name = "chkShowTheValuesRow";
			this.chkShowTheValuesRow.Properties.AccessibleName = resources.GetString("chkShowTheValuesRow.Properties.AccessibleName");
			this.chkShowTheValuesRow.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowTheValuesRow.Properties.Caption = resources.GetString("chkShowTheValuesRow.Properties.Caption");
			resources.ApplyResources(this.chkDisplayFieldAndFilter, "chkDisplayFieldAndFilter");
			this.chkDisplayFieldAndFilter.Name = "chkDisplayFieldAndFilter";
			this.chkDisplayFieldAndFilter.Properties.AccessibleName = resources.GetString("chkDisplayFieldAndFilter.Properties.AccessibleName");
			this.chkDisplayFieldAndFilter.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkDisplayFieldAndFilter.Properties.Caption = resources.GetString("chkDisplayFieldAndFilter.Properties.Caption");
			resources.ApplyResources(this.lblSeparator4, "lblSeparator4");
			this.lblSeparator4.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			this.lblSeparator4.LineVisible = true;
			this.lblSeparator4.Name = "lblSeparator4";
			resources.ApplyResources(this.chkShowPropertiesInTooltips, "chkShowPropertiesInTooltips");
			this.chkShowPropertiesInTooltips.Name = "chkShowPropertiesInTooltips";
			this.chkShowPropertiesInTooltips.Properties.AccessibleName = resources.GetString("chkShowPropertiesInTooltips.Properties.AccessibleName");
			this.chkShowPropertiesInTooltips.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowPropertiesInTooltips.Properties.Caption = resources.GetString("chkShowPropertiesInTooltips.Properties.Caption");
			resources.ApplyResources(this.chkShowContextualTooltips, "chkShowContextualTooltips");
			this.chkShowContextualTooltips.Name = "chkShowContextualTooltips";
			this.chkShowContextualTooltips.Properties.AccessibleName = resources.GetString("chkShowContextualTooltips.Properties.AccessibleName");
			this.chkShowContextualTooltips.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowContextualTooltips.Properties.Caption = resources.GetString("chkShowContextualTooltips.Properties.Caption");
			resources.ApplyResources(this.lblSeparator3, "lblSeparator3");
			this.lblSeparator3.AccessibleRole = System.Windows.Forms.AccessibleRole.Separator;
			this.lblSeparator3.LineVisible = true;
			this.lblSeparator3.Name = "lblSeparator3";
			resources.ApplyResources(this.chkShowExpandCollapseButtons, "chkShowExpandCollapseButtons");
			this.chkShowExpandCollapseButtons.Name = "chkShowExpandCollapseButtons";
			this.chkShowExpandCollapseButtons.Properties.AccessibleName = resources.GetString("chkShowExpandCollapseButtons.Properties.AccessibleName");
			this.chkShowExpandCollapseButtons.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkShowExpandCollapseButtons.Properties.Caption = resources.GetString("chkShowExpandCollapseButtons.Properties.Caption");
			resources.ApplyResources(this.lblDisplay, "lblDisplay");
			this.lblDisplay.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblDisplay.LineVisible = true;
			this.lblDisplay.Name = "lblDisplay";
			this.xtraTabPrinting.Controls.Add(this.chkSetPrintTitles);
			this.xtraTabPrinting.Controls.Add(this.chkRepeatRowLabels);
			this.xtraTabPrinting.Controls.Add(this.chkPrintExpandColapseButtons);
			this.xtraTabPrinting.Controls.Add(this.lblPrint);
			this.xtraTabPrinting.Name = "xtraTabPrinting";
			resources.ApplyResources(this.xtraTabPrinting, "xtraTabPrinting");
			resources.ApplyResources(this.chkSetPrintTitles, "chkSetPrintTitles");
			this.chkSetPrintTitles.Name = "chkSetPrintTitles";
			this.chkSetPrintTitles.Properties.AccessibleName = resources.GetString("chkSetPrintTitles.Properties.AccessibleName");
			this.chkSetPrintTitles.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkSetPrintTitles.Properties.Caption = resources.GetString("chkSetPrintTitles.Properties.Caption");
			resources.ApplyResources(this.chkRepeatRowLabels, "chkRepeatRowLabels");
			this.chkRepeatRowLabels.Name = "chkRepeatRowLabels";
			this.chkRepeatRowLabels.Properties.AccessibleName = resources.GetString("chkRepeatRowLabels.Properties.AccessibleName");
			this.chkRepeatRowLabels.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkRepeatRowLabels.Properties.Caption = resources.GetString("chkRepeatRowLabels.Properties.Caption");
			resources.ApplyResources(this.chkPrintExpandColapseButtons, "chkPrintExpandColapseButtons");
			this.chkPrintExpandColapseButtons.Name = "chkPrintExpandColapseButtons";
			this.chkPrintExpandColapseButtons.Properties.AccessibleName = resources.GetString("chkPrintExpandColapseButtons.Properties.AccessibleName");
			this.chkPrintExpandColapseButtons.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkPrintExpandColapseButtons.Properties.Caption = resources.GetString("chkPrintExpandColapseButtons.Properties.Caption");
			resources.ApplyResources(this.lblPrint, "lblPrint");
			this.lblPrint.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPrint.LineVisible = true;
			this.lblPrint.Name = "lblPrint";
			this.xtraTabData.Controls.Add(this.edtNumberOfItems);
			this.xtraTabData.Controls.Add(this.chkEnableCellEditing);
			this.xtraTabData.Controls.Add(this.lblWhatIfAnalysis);
			this.xtraTabData.Controls.Add(this.lblNumberOfItems);
			this.xtraTabData.Controls.Add(this.lblRetainItemsDeletedFromTheDataSource);
			this.xtraTabData.Controls.Add(this.chkRerfeshData);
			this.xtraTabData.Controls.Add(this.chkEnableShowDetails);
			this.xtraTabData.Controls.Add(this.chkSaveSourceDataWithFile);
			this.xtraTabData.Controls.Add(this.lblPivotTableData);
			this.xtraTabData.Name = "xtraTabData";
			resources.ApplyResources(this.xtraTabData, "xtraTabData");
			resources.ApplyResources(this.edtNumberOfItems, "edtNumberOfItems");
			this.edtNumberOfItems.Name = "edtNumberOfItems";
			this.edtNumberOfItems.Properties.AccessibleName = resources.GetString("edtNumberOfItems.Properties.AccessibleName");
			this.edtNumberOfItems.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.ComboBox;
			this.edtNumberOfItems.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(((DevExpress.XtraEditors.Controls.ButtonPredefines)(resources.GetObject("edtNumberOfItems.Properties.Buttons"))))});
			this.edtNumberOfItems.Properties.NullText = resources.GetString("edtNumberOfItems.Properties.NullText");
			this.edtNumberOfItems.Properties.ShowFooter = false;
			this.edtNumberOfItems.Properties.ShowHeader = false;
			resources.ApplyResources(this.chkEnableCellEditing, "chkEnableCellEditing");
			this.chkEnableCellEditing.Name = "chkEnableCellEditing";
			this.chkEnableCellEditing.Properties.AccessibleName = resources.GetString("chkEnableCellEditing.Properties.AccessibleName");
			this.chkEnableCellEditing.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkEnableCellEditing.Properties.Caption = resources.GetString("chkEnableCellEditing.Properties.Caption");
			resources.ApplyResources(this.lblWhatIfAnalysis, "lblWhatIfAnalysis");
			this.lblWhatIfAnalysis.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblWhatIfAnalysis.LineVisible = true;
			this.lblWhatIfAnalysis.Name = "lblWhatIfAnalysis";
			resources.ApplyResources(this.lblNumberOfItems, "lblNumberOfItems");
			this.lblNumberOfItems.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblNumberOfItems.Name = "lblNumberOfItems";
			resources.ApplyResources(this.lblRetainItemsDeletedFromTheDataSource, "lblRetainItemsDeletedFromTheDataSource");
			this.lblRetainItemsDeletedFromTheDataSource.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblRetainItemsDeletedFromTheDataSource.LineVisible = true;
			this.lblRetainItemsDeletedFromTheDataSource.Name = "lblRetainItemsDeletedFromTheDataSource";
			resources.ApplyResources(this.chkRerfeshData, "chkRerfeshData");
			this.chkRerfeshData.Name = "chkRerfeshData";
			this.chkRerfeshData.Properties.AccessibleName = resources.GetString("chkRerfeshData.Properties.AccessibleName");
			this.chkRerfeshData.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkRerfeshData.Properties.Caption = resources.GetString("chkRerfeshData.Properties.Caption");
			resources.ApplyResources(this.chkEnableShowDetails, "chkEnableShowDetails");
			this.chkEnableShowDetails.Name = "chkEnableShowDetails";
			this.chkEnableShowDetails.Properties.AccessibleName = resources.GetString("chkEnableShowDetails.Properties.AccessibleName");
			this.chkEnableShowDetails.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkEnableShowDetails.Properties.Caption = resources.GetString("chkEnableShowDetails.Properties.Caption");
			resources.ApplyResources(this.chkSaveSourceDataWithFile, "chkSaveSourceDataWithFile");
			this.chkSaveSourceDataWithFile.Name = "chkSaveSourceDataWithFile";
			this.chkSaveSourceDataWithFile.Properties.AccessibleName = resources.GetString("chkSaveSourceDataWithFile.Properties.AccessibleName");
			this.chkSaveSourceDataWithFile.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
			this.chkSaveSourceDataWithFile.Properties.Caption = resources.GetString("chkSaveSourceDataWithFile.Properties.Caption");
			resources.ApplyResources(this.lblPivotTableData, "lblPivotTableData");
			this.lblPivotTableData.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPivotTableData.LineVisible = true;
			this.lblPivotTableData.Name = "lblPivotTableData";
			this.xtraTabAltText.Controls.Add(this.lblAltText);
			this.xtraTabAltText.Controls.Add(this.edtDecsription);
			this.xtraTabAltText.Controls.Add(this.lblDescription);
			this.xtraTabAltText.Controls.Add(this.edtTitle);
			this.xtraTabAltText.Controls.Add(this.lblTitle);
			this.xtraTabAltText.Name = "xtraTabAltText";
			resources.ApplyResources(this.xtraTabAltText, "xtraTabAltText");
			resources.ApplyResources(this.lblAltText, "lblAltText");
			this.lblAltText.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblAltText.Name = "lblAltText";
			resources.ApplyResources(this.edtDecsription, "edtDecsription");
			this.edtDecsription.Name = "edtDecsription";
			this.edtDecsription.Properties.AccessibleName = resources.GetString("edtDecsription.Properties.AccessibleName");
			this.edtDecsription.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			resources.ApplyResources(this.lblDescription, "lblDescription");
			this.lblDescription.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblDescription.Name = "lblDescription";
			resources.ApplyResources(this.edtTitle, "edtTitle");
			this.edtTitle.Name = "edtTitle";
			this.edtTitle.Properties.AccessibleName = resources.GetString("edtTitle.Properties.AccessibleName");
			this.edtTitle.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			resources.ApplyResources(this.lblTitle, "lblTitle");
			this.lblTitle.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblTitle.Name = "lblTitle";
			resources.ApplyResources(this.btnCancel, "btnCancel");
			this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.btnCancel.Name = "btnCancel";
			resources.ApplyResources(this.btnOk, "btnOk");
			this.btnOk.Name = "btnOk";
			this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
			resources.ApplyResources(this.lblPivotTableName, "lblPivotTableName");
			this.lblPivotTableName.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
			this.lblPivotTableName.Name = "lblPivotTableName";
			resources.ApplyResources(this.edtPivotTableName, "edtPivotTableName");
			this.edtPivotTableName.Name = "edtPivotTableName";
			this.edtPivotTableName.Properties.AccessibleName = resources.GetString("edtPivotTableName.Properties.AccessibleName");
			this.edtPivotTableName.Properties.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
			this.AcceptButton = this.btnOk;
			resources.ApplyResources(this, "$this");
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.btnCancel;
			this.Controls.Add(this.edtPivotTableName);
			this.Controls.Add(this.lblPivotTableName);
			this.Controls.Add(this.btnCancel);
			this.Controls.Add(this.btnOk);
			this.Controls.Add(this.tabControl);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "OptionsPivotTableForm";
			this.ShowInTaskbar = false;
			this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
			((System.ComponentModel.ISupportInitialize)(this.tabControl)).EndInit();
			this.tabControl.ResumeLayout(false);
			this.xtraTabLayoutAndFormat.ResumeLayout(false);
			this.xtraTabLayoutAndFormat.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtFieldsReportFilterArea.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkPreserveCellFormatting.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkAutofitColumnWidths.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEmptyCellsShow.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkErrorValuesShow.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtEmptyCellsShow.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtErrorValuesShow.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtReportFilterFields.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtIndentRowLabels.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMergeAndCenterCells.Properties)).EndInit();
			this.xtraTabTotalsAndFilters.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chkUseCustomLists.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkMultipleFiltersField.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSubtotalFilteredItems.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkGrandTotalsColumns.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkGrandTotalsRows.Properties)).EndInit();
			this.xtraTabDisplay.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.rgrpSort.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkDisplayItemLabels.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowItemsWithNoDataOnColumns.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowItemsWithNoDataOnRows.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowTheValuesRow.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkDisplayFieldAndFilter.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowPropertiesInTooltips.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowContextualTooltips.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkShowExpandCollapseButtons.Properties)).EndInit();
			this.xtraTabPrinting.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chkSetPrintTitles.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkRepeatRowLabels.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkPrintExpandColapseButtons.Properties)).EndInit();
			this.xtraTabData.ResumeLayout(false);
			this.xtraTabData.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtNumberOfItems.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEnableCellEditing.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkRerfeshData.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkEnableShowDetails.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.chkSaveSourceDataWithFile.Properties)).EndInit();
			this.xtraTabAltText.ResumeLayout(false);
			this.xtraTabAltText.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.edtDecsription.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtTitle.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.edtPivotTableName.Properties)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
		private XtraTab.XtraTabControl tabControl;
		private XtraTab.XtraTabPage xtraTabAltText;
		private XtraTab.XtraTabPage xtraTabLayoutAndFormat;
		private XtraTab.XtraTabPage xtraTabTotalsAndFilters;
		private XtraTab.XtraTabPage xtraTabDisplay;
		private XtraTab.XtraTabPage xtraTabPrinting;
		private XtraTab.XtraTabPage xtraTabData;
		private XtraEditors.SimpleButton btnCancel;
		private XtraEditors.SimpleButton btnOk;
		private XtraEditors.LabelControl lblPivotTableName;
		private XtraEditors.TextEdit edtPivotTableName;
		private XtraEditors.CheckEdit chkMergeAndCenterCells;
		private XtraEditors.LabelControl lblLayout;
		private XtraEditors.LabelControl lblSeparator1;
		private XtraEditors.LabelControl lblCharacters;
		private XtraEditors.SpinEdit edtIndentRowLabels;
		private XtraEditors.LabelControl lblIndentRowLabels;
		private XtraEditors.LabelControl lblFieldsReportFilterArea;
		private XtraEditors.LabelControl lblFormat;
		private XtraEditors.LabelControl lblReportFilterFields;
		private XtraEditors.SpinEdit edtReportFilterFields;
		private XtraEditors.TextEdit edtEmptyCellsShow;
		private XtraEditors.TextEdit edtErrorValuesShow;
		private XtraEditors.CheckEdit chkPreserveCellFormatting;
		private XtraEditors.CheckEdit chkAutofitColumnWidths;
		private XtraEditors.LabelControl lblSeparator2;
		private XtraEditors.CheckEdit chkEmptyCellsShow;
		private XtraEditors.CheckEdit chkErrorValuesShow;
		private XtraEditors.CheckEdit chkUseCustomLists;
		private XtraEditors.LabelControl lblSorting;
		private XtraEditors.CheckEdit chkMultipleFiltersField;
		private XtraEditors.CheckEdit chkSubtotalFilteredItems;
		private XtraEditors.LabelControl lblFilters;
		private XtraEditors.CheckEdit chkGrandTotalsColumns;
		private XtraEditors.CheckEdit chkGrandTotalsRows;
		private XtraEditors.LabelControl lblGrandTotals;
		private XtraEditors.CheckEdit chkSetPrintTitles;
		private XtraEditors.CheckEdit chkRepeatRowLabels;
		private XtraEditors.CheckEdit chkPrintExpandColapseButtons;
		private XtraEditors.LabelControl lblPrint;
		private XtraEditors.LabelControl lblFieldList;
		private XtraEditors.CheckEdit chkDisplayItemLabels;
		private XtraEditors.LabelControl lblSeparator6;
		private XtraEditors.CheckEdit chkShowItemsWithNoDataOnColumns;
		private XtraEditors.CheckEdit chkShowItemsWithNoDataOnRows;
		private XtraEditors.LabelControl lblSeparator5;
		private XtraEditors.CheckEdit chkShowTheValuesRow;
		private XtraEditors.CheckEdit chkDisplayFieldAndFilter;
		private XtraEditors.LabelControl lblSeparator4;
		private XtraEditors.CheckEdit chkShowPropertiesInTooltips;
		private XtraEditors.CheckEdit chkShowContextualTooltips;
		private XtraEditors.LabelControl lblSeparator3;
		private XtraEditors.CheckEdit chkShowExpandCollapseButtons;
		private XtraEditors.LabelControl lblDisplay;
		private XtraEditors.RadioGroup rgrpSort;
		private XtraEditors.CheckEdit chkEnableCellEditing;
		private XtraEditors.LabelControl lblWhatIfAnalysis;
		private XtraEditors.LabelControl lblNumberOfItems;
		private XtraEditors.LabelControl lblRetainItemsDeletedFromTheDataSource;
		private XtraEditors.CheckEdit chkRerfeshData;
		private XtraEditors.CheckEdit chkEnableShowDetails;
		private XtraEditors.CheckEdit chkSaveSourceDataWithFile;
		private XtraEditors.LabelControl lblPivotTableData;
		private XtraEditors.LabelControl lblAltText;
		private XtraEditors.MemoEdit edtDecsription;
		private XtraEditors.LabelControl lblDescription;
		private XtraEditors.TextEdit edtTitle;
		private XtraEditors.LabelControl lblTitle;
		private XtraEditors.LookUpEdit edtFieldsReportFilterArea;
		private XtraEditors.LookUpEdit edtNumberOfItems;
		private XtraEditors.LabelControl lblRow;
		private XtraEditors.LabelControl lblColumn;
	}
}
