#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "DevExpress.Xpf.Printing.DataNodes", Justification = "We do want this namespace.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "DevExpress.Xpf.Printing.Tests.Exports", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "XamlGeneratedNamespace", Justification = "Autogenerated code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "DevExpress.Xpf.Printing.Tests.BrickCollectorTests", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PageBuilderFixture.#VerifyDocumentBandContainer(DevExpress.XtraPrinting.Native.DocumentBand,System.Int32)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "DevExpress.Xpf.Printing.Tests.PrintHelperExportTestBase", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PrintHelperExportTestBase.#source", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "DevExpress.Xpf.Printing.Tests.PrintHelperExportToStreamTests", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.XmlDataHelper.#CreateDataset(System.Type,System.String)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.XmlDataHelper.#FillDataset(System.Data.DataSet,System.Reflection.Assembly,System.String)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.XmlDataHelper.#FillDataset(System.Data.DataSet,System.Reflection.Assembly,System.String)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PageBuilderFixture.#VerifyDoubleGroupBand(DevExpress.XtraPrinting.Native.DocumentBand)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PageBuilderFixture.#VerifyGroupBand(DevExpress.XtraPrinting.Native.DocumentBand)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PageBuilderFixture.#VerifyPlainBandContainer(DevExpress.XtraPrinting.Native.DocumentBand,System.Int32)", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#AddEventHandler(System.Reflection.EventInfo,System.Object,System.Delegate)", Justification = "XamlGeneratedNamespace ignored")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#CreateDelegate(System.Type,System.Object,System.String)", Justification = "XamlGeneratedNamespace ignored")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#GetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Globalization.CultureInfo)", Justification = "XamlGeneratedNamespace ignored")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#SetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Object,System.Globalization.CultureInfo)", Justification = "XamlGeneratedNamespace ignored")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "DevExpress.Xpf.Printing.Native.BrickCollector.#InitializeBrick(DevExpress.XtraPrinting.VisualBrick,System.Windows.DependencyObject,System.Windows.DependencyObject)", Justification = "Fixing warnings about duplicated object casting will decrease the code readability.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "DevExpress.Xpf.Printing.Native.DXPageContentCreator.#Create(DevExpress.XtraPrinting.Native.PSPage)", Justification = "Fixing warnings about duplicated object casting will decrease the code readability.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "brickCollector", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.BrickCollectorTests.#CanNotCreateWithNullPrintingSystemTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "panel", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.BrickCollectorTests.#UnsupportedNonUniformBorderThicknessTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "extension", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PrintingResourceImageExtensionTests.#EmptyResourceNameTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "extension", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PrintingResourceImageExtensionTests.#NullResourceNameTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "printPreview", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.PrintPreviewTests.#CommandBindingsTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "link", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.SimpleLinkTests.#NegativeDetailCountCtorTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "link", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.VisualDataNodeLinkTests.#NullRootNodeSourceTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "link", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.VisualDataNodeLinkTests.#NullRootNodeTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "node", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.VisualRootNodeTests.#CanNotCreateWithNullRowsContainerTest()", Justification = "Test code is ignored.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "DevExpress.Xpf.Printing.Tests.BrickCollectorTests.#CreateBrickTest()", Justification = "Test code is ignored.")]
