#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
namespace DevExpress.Web.ASPxHtmlEditor.Internal {
	#region Attribute Names
	public static class A {
		public const string
			Abbr = "abbr",
			Accept = "accept",
			AcceptCharset = "accept-charset",
			AccessKey = "accesskey",
			Action = "action",
			Align = "align",
			Alt = "alt",
			Archive = "archive",
			Axis = "axis",
			Background = "background",
			BgColor = "bgcolor",
			Border = "border",
			BorderColor = "bordercolor",
			Char = "char",
			CharOffset = "charoff",
			CellPadding = "cellpadding",
			CellSpacing = "cellspacing",
			Charset = "charset",
			Checked = "checked",
			Cite = "cite",
			Class = "class",
			ClassID = "classid",
			Clear = "clear",
			Code = "code",
			CodeBase = "codebase",
			CodeType = "codetype",
			Color = "color",
			Cols = "cols",
			ColSpan = "colspan",
			Compact = "compact",
			Content = "content",
			Coords = "coords",
			Data = "data",
			DateTime = "datetime",
			Declare = "declare",
			Defer = "defer",
			Dir = "dir",
			Disabled = "disabled",
			EncType = "enctype",
			Face = "face",
			For = "for",
			Frame = "frame",
			FrameBorder = "frameborder",
			Headers = "headers",
			Height = "height",
			Href = "href",
			HrefLang = "hreflang",
			HSpace = "hspace",
			HttpEquiv = "http-equiv",
			ID = "id",
			IsMap = "ismap",
			Label = "label",
			Lang = "lang",
			Language = "language",
			Link = "link",
			LongDesc = "longdesc",
			MarginHeight = "marginheight",
			MarginWidth = "marginwidth",
			MaxLength = "maxlength",
			Media = "media",
			Method = "method",
			Multiple = "multiple",
			Name = "name",
			NoHref = "nohref",
			NoShade = "noshade",
			NoWrap = "nowrap",
			Object = "object",
			OnClick = "onclick",
			OnDblClick = "ondblclick",
			OnMouseDown = "onmousedown",
			OnMouseUp = "onmouseup",
			OnMouseOver = "onmouseover",
			OnMouseMove = "onmousemove",
			OnMouseOut = "onmouseout",
			OnKeyPress = "onkeypress",
			OnKeyDown = "onkeydown",
			OnKeyUp = "onkeyup",
			OnBlur = "onblur",
			OnChange = "onchange",
			OnFocus = "onfocus",
			OnLoad = "onload",
			OnReset = "onreset",
			OnSelect = "onselect",
			OnSubmit = "onsubmit",
			OnUnload = "onunload",
			Profile = "profile",
			Prompt = "prompt",
			ReadOnly = "readonly",
			Rel = "rel",
			Rev = "rev",
			Rows = "rows",
			RowSpan = "rowspan",
			Rules = "rules",
			Scheme = "scheme",
			Scope = "scope",
			Scrolling = "scrolling",
			Selected = "selected",
			Shape = "shape",
			Size = "size",
			Span = "span",
			Src = "src",
			StandBy = "standby",
			Start = "start",
			Style = "style",
			Summary = "summary",
			TabIndex = "tabindex",
			Target = "target",
			Text = "text",
			Title = "title",
			Type = "type",
			UseMap = "usemap",
			Value = "value",
			ValueType = "valuetype",
			VerticalAlign = "valign",
			VLink = "vlink",
			VSpace = "vspace",
			Width = "width",
			XmlLang = "xml:lang";
		public const string
			ContentEditable = "contenteditable",
			ContextMenu = "contextmenu",
			Draggable = "draggable",
			Dropzone = "dropzone",
			Hidden = "hidden",
			Spellcheck = "spellcheck",
			AutoPlay = "autoplay",
			Controls = "controls",
			Loop = "loop",
			PreLoad = "preload",
			Icon = "icon",
			RadioGroup = "radiogroup",
			Open = "open",
			Keytype = "keytype",
			Optimum = "optimum",
			High = "high",
			Low = "low",
			Max = "max",
			Min = "min",
			SrcLang = "srclang",
			Kind = "kind",
			Default = "default",
			PubDate = "pubdate",
			Poster = "poster",
			Muted = "muted",
			Async = "async",
			Form = "form",
			Challenge = "challenge",
			AutoComplete = "autocomplete",
			AutoFocus = "autofocus",
			FormAction = "formaction",
			FormEncType = "formenctype",
			FormMethod = "formmethod",
			FormNoValidate = "formnovalidate",
			FormTarget = "formtarget",
			List = "list",
			Pattern = "pattern",
			Placeholder = "placeholder",
			Step = "step",
			Required = "required",
			Wrap = "wrap",
			Reversed = "reversed",
			OnAfterPrint = "onafterprint",
			OnBeforePrint = "onbeforeprint",
			OnBeforeOnLoad = "onbeforeonload",
			OnError = "onerror",
			OnHasChange = "onhaschange",
			OnMessage = "onmessage",
			OnOffline = "onoffline",
			OnOnline = "ononline",
			OnPageHide = "onpagehide",
			OnPageShow = "onpageshow",
			OnPopState = "onpopstate",
			OnRedo = "onredo",
			OnResize = "onresize",
			OnStorage = "onstorage",
			OnUndo = "onundo",
			OnContextMenu = "oncontextmenu",
			OnFormChange = "onformchange",
			OnFormInput = "onforminput",
			OnInput = "oninput",
			OnInvalid = "oninvalid",
			OnDrag = "ondrag",
			OnDragEnd = "ondragend",
			OnDragEnter = "ondragenter",
			OnDragLeave = "ondragleave",
			OnDragOver = "ondragover",
			OnDragStart = "ondragstart",
			OnDrop = "ondrop",
			OnMouseWheel = "onmousewheel",
			OnScroll = "onscroll",
			OnCanPlay = "oncanplay",
			OnCanPlayThrough = "oncanplaythrough",
			OnDurationChange = "ondurationchange",
			OnEmptied = "onemptied",
			OnEnded = "onended",
			OnLoadeddata = "onloadeddata",
			OnLoadedmetadata = "onloadedmetadata",
			OnLoadstart = "onloadstart",
			OnPause = "onpause",
			OnPlay = "onplay",
			OnPlaying = "onplaying",
			OnProgress = "onprogress",
			OnRatechange = "onratechange",
			OnReadystatechange = "onreadystatechange",
			OnSeeked = "onseeked",
			OnSeeking = "onseeking",
			OnStalled = "onstalled",
			OnSuspend = "onsuspend",
			OnTimeupdate = "ontimeupdate",
			OnVolumechange = "onvolumechange",
			OnWaiting = "onwaiting",
			Property = "property",
			CrossOrigin = "crossorigin",
			Sizes = "sizes",
			Translate = "translate",
			Manifest = "manifest"
			;
		public const string
			DataPrefix = "data-";
	}
	#endregion
	#region Attribute predefined values
	public static class V {
		public static readonly string[]
			Align = new string[] { "left", "center", "right" },
			ButtonType = new string[] { "button", "submit", "reset" },
			CaptionAlign = new string[] { "top", "bottom", "left", "right" },
			CellHAlign = new string[] { "left", "center", "right", "justify", "char" },
			CellVAlign = new string[] { "top", "middle", "bottom", "baseline" },
			Clear = new string[] { "left", "all", "right", "none" },
			Direction = new string[] { "ltr", "rtl" },
			ImageAlign = new string[] { "top", "middle", "bottom", "left", "right" },
			InputType = new string[] { "text", "password", "checkbox", "radio", "submit", "reset", "file", "hidden", "image", "button", 
				"color", "date", "datetime", "datetime-local", "email", "month", "number", "range", "search", "tel", "time", "url", "week" },
			FrameBorder = new string[] { "1", "0" },
			LegendAlign = new string[] { "top", "bottom", "left", "right" },
			Method = new string[] { "get", "post" },
			Scope = new string[] { "row", "col", "rowgroup", "colgroup" },
			Scrolling = new string[] { "yes", "no", "auto" },
			Shape = new string[] { "rect", "circle", "poly", "default" },
			TableAlign = new string[] { "left", "center", "right" },
			TableFrame = new string[] { "void", "above", "below", "hsides", "lhs", "rhs", "vsides", "box", "border" },
			TableRules = new string[] { "none", "groups", "rows", "cols", "all" },
			TextAlign = new string[] { "left", "center", "right", "justify" },
			ULStyle = new string[] { "disc", "square", "circle" },
			ValueType = new string[] { "data", "ref", "object" };
		public static readonly string
			BdoDirectionDefault = "ltr",
			CaptionAlignDefault = "top",
			ClearDefault = "none",
			CellVAlignDefault = "middle",
			ColSpanDefault = "1",
			EncTypeDefault = "application/x-www-form-urlencoded",
			FrameBorderDefault = "1",
			InputTypeDefault = "text",
			MethodDefault = "get",
			RowSpanDefault = "1",
			ShapeDefault = "rect",
			ScriptTypeDefault = "text/javascript",
			ScrollingDefault = "auto",
			TableAlignDefault = "left",
			TableFrameDefault = "void",
			TableRulesDefault = "none",
			ValueTypeDefault = "data";
	}
	#endregion
	#region Element names
	public static class E {
		public const string
			Document = "#document",
			Html = "html",
			Head = "head",
			Title = "title",
			BaseElement = "base",
			Meta = "meta",
			Style = "style",
			Link = "link",
			Body = "body",
			NoFrames = "noframes",
			BaseFont = "basefont",
			Applet = "applet",
			Menu = "menu",
			Dir = "dir",
			IsIndex = "isindex",
			Script = "script",
			IFrame = "iframe",
			Form = "form",
			Label = "label",
			Input = "input",
			Select = "select",
			Option = "option",
			OptGroup = "optgroup",
			TextArea = "textarea",
			Button = "button",
			U = "u",
			S = "s",
			Strike = "strike",
			Font = "font",
			Center = "center",
			I = "i",
			B = "b",
			NoScript = "noscript",
			Div = "div",
			P = "p",
			FieldSet = "fieldset",
			ObjectElement = "object",
			Param = "param",
			Legend = "legend",
			Span = "span",
			A = "a",
			Img = "img",
			Map = "map",
			Area = "area",
			Bdo = "bdo",
			Hr = "hr",
			Br = "br",
			H1 = "h1",
			H2 = "h2",
			H3 = "h3",
			H4 = "h4",
			H5 = "h5",
			H6 = "h6",
			UL = "ul",
			LI = "li",
			OL = "ol",
			DL = "dl",
			DT = "dt",
			DD = "dd",
			Pre = "pre",
			Address = "address",
			BlockQuote = "blockquote",
			Ins = "ins",
			Del = "del",
			Q = "q",
			Em = "em",
			Strong = "strong",
			Dfn = "dfn",
			Code = "code",
			Samp = "samp",
			Kbd = "kbd",
			Var = "var",
			Cite = "cite",
			Abbr = "abbr",
			Acronym = "acronym",
			Sub = "sub",
			Sup = "sup",
			TT = "tt",
			Big = "big",
			Small = "small",
			Table = "table",
			Caption = "caption",
			THead = "thead",
			TFoot = "tfoot",
			TBody = "tbody",
			ColGroup = "colgroup",
			Col = "col",
			TR = "tr",
			TH = "th",
			TD = "td";
		public const string
			Article = "article",
			Aside = "aside",
			Audio = "audio",
			Bdi = "bdi",
			Canvas = "canvas",
			Command = "command",
			Datalist = "datalist",
			Details = "details",
			Embed = "embed",
			FigCaption = "figcaption",
			Figure = "figure",
			Footer = "footer",
			Header = "header",
			Hgroup = "hgroup",
			Keygen = "keygen",
			Mark = "mark",
			Meter = "meter",
			Nav = "nav",
			Output = "output",
			Progress = "progress",
			Rp = "rp",
			Rt = "rt",
			Ruby = "ruby",
			Section = "section",
			Source = "source",
			Summary = "summary",
			Time = "time",
			Track = "track",
			Video = "video",
			Wbr = "wbr";
	}
	#endregion
}
