


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module __aspxRichEdit {
	export class JSONCharacterPropertiesConverter {
		static convertFromJSON(obj: any): CharacterProperties {
			var result = new CharacterProperties();
			result.fontSize = obj[JSONCharacterFormattingProperty.FontSize];
			result.fontBold = obj[JSONCharacterFormattingProperty.FontBold];
			result.fontItalic = obj[JSONCharacterFormattingProperty.FontItalic];
			result.fontStrikeoutType = obj[JSONCharacterFormattingProperty.FontStrikeoutType];
			result.fontUnderlineType = obj[JSONCharacterFormattingProperty.FontUnderlineType];
			result.allCaps = obj[JSONCharacterFormattingProperty.AllCaps];
			result.strikeoutWordsOnly = obj[JSONCharacterFormattingProperty.StrikeoutWordsOnly];
			result.underlineWordsOnly = obj[JSONCharacterFormattingProperty.UnderlineWordsOnly];
			result.foreColor = obj[JSONCharacterFormattingProperty.ForeColor];
			result.backColor = obj[JSONCharacterFormattingProperty.BackColor];
			result.underlineColor = obj[JSONCharacterFormattingProperty.UnderlineColor];
			result.strikeoutColor = obj[JSONCharacterFormattingProperty.StrikeoutColor];
			result.script = obj[JSONCharacterFormattingProperty.Script];
			result.hidden = obj[JSONCharacterFormattingProperty.Hidden];
			result.noProof = obj[JSONCharacterFormattingProperty.NoProof];
			return result;
		}
		static convertToJSON(source: CharacterProperties): any {
			var result = {};
			result[JSONCharacterFormattingProperty.FontInfoIndex] = source.fontInfo.index;
			result[JSONCharacterFormattingProperty.FontSize] = source.fontSize;
			result[JSONCharacterFormattingProperty.FontBold] = source.fontBold;
			result[JSONCharacterFormattingProperty.FontItalic] = source.fontItalic;
			result[JSONCharacterFormattingProperty.FontStrikeoutType] = source.fontStrikeoutType;
			result[JSONCharacterFormattingProperty.FontUnderlineType] = source.fontUnderlineType;
			result[JSONCharacterFormattingProperty.AllCaps] = source.allCaps;
			result[JSONCharacterFormattingProperty.StrikeoutWordsOnly] = source.strikeoutWordsOnly;
			result[JSONCharacterFormattingProperty.UnderlineWordsOnly] = source.underlineWordsOnly;
			result[JSONCharacterFormattingProperty.ForeColor] = source.foreColor;
			result[JSONCharacterFormattingProperty.BackColor] = source.backColor;
			result[JSONCharacterFormattingProperty.UnderlineColor] = source.underlineColor;
			result[JSONCharacterFormattingProperty.StrikeoutColor] = source.strikeoutColor;
			result[JSONCharacterFormattingProperty.Script] = source.script;
			result[JSONCharacterFormattingProperty.Hidden] = source.hidden;
			result[JSONCharacterFormattingProperty.NoProof] = source.noProof;
			return result;
		}
	}
}