

 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module __aspxRichEdit {
	export class JSONSectionPropertiesConverter {
		static convertFromJSON(obj: any): SectionProperties {
			var result = new SectionProperties();
			result.marginLeft = obj[JSONSectionProperty.MarginLeft];
			result.marginTop = obj[JSONSectionProperty.MarginTop];
			result.marginRight = obj[JSONSectionProperty.MarginRight];
			result.marginBottom = obj[JSONSectionProperty.MarginBottom];
			result.columnCount = obj[JSONSectionProperty.ColumnCount];
			result.space = obj[JSONSectionProperty.Space];
			result.columnsInfo = JSONColumnsSectionPropertiesConverter.convertFromJSON(obj[JSONSectionProperty.ColumnsInfo]);
			result.pageWidth = obj[JSONSectionProperty.PageWidth];
			result.pageHeight = obj[JSONSectionProperty.PageHeight];
			result.startType = obj[JSONSectionProperty.StartType];
			result.landscape = obj[JSONSectionProperty.Landscape];
			result.equalWidthColumns = obj[JSONSectionProperty.EqualWidthColumns];
			result.differentFirstPage = obj[JSONSectionProperty.DifferentFirstPage];
			result.headerOffset = obj[JSONSectionProperty.HeaderOffset];
			result.footerOffset = obj[JSONSectionProperty.FooterOffset];
			return result;
		}
		static convertToJSON(source: SectionProperties): any {
			var result = {};
			result[JSONSectionProperty.MarginLeft] = source.marginLeft;
			result[JSONSectionProperty.MarginTop] = source.marginTop;
			result[JSONSectionProperty.MarginRight] = source.marginRight;
			result[JSONSectionProperty.MarginBottom] = source.marginBottom;
			result[JSONSectionProperty.ColumnCount] = source.columnCount;
			result[JSONSectionProperty.Space] = source.space;
			result[JSONSectionProperty.ColumnsInfo] = JSONColumnsSectionPropertiesConverter.convertToJSON(source.columnsInfo);
			result[JSONSectionProperty.PageWidth] = source.pageWidth;
			result[JSONSectionProperty.PageHeight] = source.pageHeight;
			result[JSONSectionProperty.StartType] = source.startType;
			result[JSONSectionProperty.Landscape] = source.landscape;
			result[JSONSectionProperty.EqualWidthColumns] = source.equalWidthColumns;
			result[JSONSectionProperty.DifferentFirstPage] = source.differentFirstPage;
			result[JSONSectionProperty.HeaderOffset] = source.headerOffset;
			result[JSONSectionProperty.FooterOffset] = source.footerOffset;
			return result;
		}
	}
}