#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

namespace DevExpress.XtraCharts.Designer.Native {
	partial class FibonacciIndicatorOptionsControl {
		private System.ComponentModel.IContainer components = null;
		protected override void Dispose(bool disposing) {
			if(disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		#region Component Designer generated code
		private void InitializeComponent() {
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation1 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation2 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation3 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation4 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation5 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation6 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation7 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation8 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation9 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation10 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation11 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation12 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation13 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.EnumElementPresentation enumElementPresentation14 = new DevExpress.XtraCharts.Designer.Native.EnumElementPresentation();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink1 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink2 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink3 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink4 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink5 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink6 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink7 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink8 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink9 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink10 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink11 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink12 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink13 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink14 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			DevExpress.XtraCharts.Designer.Native.PropertyLink propertyLink15 = new DevExpress.XtraCharts.Designer.Native.PropertyLink();
			this.uiOptionsBuilder1 = new DevExpress.XtraCharts.Designer.Native.UIOptionsBuilder();
			this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
			this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.GeneralGroup = new DevExpress.XtraLayout.LayoutControlGroup();
			this.titleElement1 = new DevExpress.XtraCharts.Designer.Native.TitleElement();
			this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
			this.simpleSeparator1 = new DevExpress.XtraLayout.SimpleSeparator();
			this.checkEdit1 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
			this.textEdit1 = new DevExpress.XtraEditors.TextEdit();
			this.labelControl2 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
			this.checkEdit2 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl3 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
			this.BehaviorGroup = new DevExpress.XtraLayout.LayoutControlGroup();
			this.titleElement2 = new DevExpress.XtraCharts.Designer.Native.TitleElement();
			this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
			this.simpleSeparator2 = new DevExpress.XtraLayout.SimpleSeparator();
			this.checkEdit3 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl4 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem9 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem10 = new DevExpress.XtraLayout.LayoutControlItem();
			this.checkEdit4 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl5 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem11 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem12 = new DevExpress.XtraLayout.LayoutControlItem();
			this.checkEdit5 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl6 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem13 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem14 = new DevExpress.XtraLayout.LayoutControlItem();
			this.checkEdit6 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl7 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem15 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem16 = new DevExpress.XtraLayout.LayoutControlItem();
			this.checkEdit7 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl8 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem17 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem18 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.titleElement3 = new DevExpress.XtraCharts.Designer.Native.TitleElement();
			this.layoutControlItem19 = new DevExpress.XtraLayout.LayoutControlItem();
			this.simpleSeparator3 = new DevExpress.XtraLayout.SimpleSeparator();
			this.comboBoxEdit1 = new DevExpress.XtraEditors.ComboBoxEdit();
			this.labelControl9 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem20 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem21 = new DevExpress.XtraLayout.LayoutControlItem();
			this.textEdit2 = new DevExpress.XtraEditors.TextEdit();
			this.labelControl10 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem22 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem23 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlGroup3 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.titleElement4 = new DevExpress.XtraCharts.Designer.Native.TitleElement();
			this.layoutControlItem24 = new DevExpress.XtraLayout.LayoutControlItem();
			this.simpleSeparator4 = new DevExpress.XtraLayout.SimpleSeparator();
			this.comboBoxEdit2 = new DevExpress.XtraEditors.ComboBoxEdit();
			this.labelControl11 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem25 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem26 = new DevExpress.XtraLayout.LayoutControlItem();
			this.textEdit3 = new DevExpress.XtraEditors.TextEdit();
			this.labelControl12 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem27 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem28 = new DevExpress.XtraLayout.LayoutControlItem();
			this.LabelGroup = new DevExpress.XtraLayout.LayoutControlGroup();
			this.titleElement5 = new DevExpress.XtraCharts.Designer.Native.TitleElement();
			this.layoutControlItem29 = new DevExpress.XtraLayout.LayoutControlItem();
			this.simpleSeparator5 = new DevExpress.XtraLayout.SimpleSeparator();
			this.checkEdit8 = new DevExpress.XtraEditors.CheckEdit();
			this.labelControl13 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem30 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem31 = new DevExpress.XtraLayout.LayoutControlItem();
			this.colorPickEdit1 = new DevExpress.XtraEditors.ColorPickEdit();
			this.labelControl14 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem32 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem33 = new DevExpress.XtraLayout.LayoutControlItem();
			this.colorPickEdit2 = new DevExpress.XtraEditors.ColorPickEdit();
			this.labelControl15 = new DevExpress.XtraEditors.LabelControl();
			this.layoutControlItem34 = new DevExpress.XtraLayout.LayoutControlItem();
			this.layoutControlItem35 = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
			((System.ComponentModel.ISupportInitialize)(this.uiOptionsBuilder1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
			this.layoutControl1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.GeneralGroup)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit2.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BehaviorGroup)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit3.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit4.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit5.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit6.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit7.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit2.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit2.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem26)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit3.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem27)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem28)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.LabelGroup)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem29)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit8.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem30)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem31)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.colorPickEdit1.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem32)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem33)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.colorPickEdit2.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem34)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem35)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
			this.SuspendLayout();
			this.layoutControl1.AllowCustomization = false;
			this.layoutControl1.Controls.Add(this.titleElement1);
			this.layoutControl1.Controls.Add(this.labelControl1);
			this.layoutControl1.Controls.Add(this.checkEdit1);
			this.layoutControl1.Controls.Add(this.labelControl2);
			this.layoutControl1.Controls.Add(this.textEdit1);
			this.layoutControl1.Controls.Add(this.labelControl3);
			this.layoutControl1.Controls.Add(this.checkEdit2);
			this.layoutControl1.Controls.Add(this.titleElement2);
			this.layoutControl1.Controls.Add(this.labelControl4);
			this.layoutControl1.Controls.Add(this.checkEdit3);
			this.layoutControl1.Controls.Add(this.labelControl5);
			this.layoutControl1.Controls.Add(this.checkEdit4);
			this.layoutControl1.Controls.Add(this.labelControl6);
			this.layoutControl1.Controls.Add(this.checkEdit5);
			this.layoutControl1.Controls.Add(this.labelControl7);
			this.layoutControl1.Controls.Add(this.checkEdit6);
			this.layoutControl1.Controls.Add(this.labelControl8);
			this.layoutControl1.Controls.Add(this.checkEdit7);
			this.layoutControl1.Controls.Add(this.titleElement3);
			this.layoutControl1.Controls.Add(this.labelControl9);
			this.layoutControl1.Controls.Add(this.comboBoxEdit1);
			this.layoutControl1.Controls.Add(this.labelControl10);
			this.layoutControl1.Controls.Add(this.textEdit2);
			this.layoutControl1.Controls.Add(this.titleElement4);
			this.layoutControl1.Controls.Add(this.labelControl11);
			this.layoutControl1.Controls.Add(this.comboBoxEdit2);
			this.layoutControl1.Controls.Add(this.labelControl12);
			this.layoutControl1.Controls.Add(this.textEdit3);
			this.layoutControl1.Controls.Add(this.titleElement5);
			this.layoutControl1.Controls.Add(this.labelControl13);
			this.layoutControl1.Controls.Add(this.checkEdit8);
			this.layoutControl1.Controls.Add(this.labelControl14);
			this.layoutControl1.Controls.Add(this.colorPickEdit1);
			this.layoutControl1.Controls.Add(this.labelControl15);
			this.layoutControl1.Controls.Add(this.colorPickEdit2);
			this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.layoutControl1.Location = new System.Drawing.Point(0, 0);
			this.layoutControl1.Name = "layoutControl1";
			this.layoutControl1.Root = this.layoutControlGroup1;
			this.layoutControl1.Size = new System.Drawing.Size(300, 653);
			this.layoutControl1.TabIndex = 0;
			this.layoutControlGroup1.GroupBordersVisible = false;
			this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.GeneralGroup,
			this.BehaviorGroup,
			this.layoutControlGroup2,
			this.layoutControlGroup3,
			this.LabelGroup,
			this.emptySpaceItem1});
			this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
			this.layoutControlGroup1.Name = "layoutControlGroup1";
			this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
			this.layoutControlGroup1.Size = new System.Drawing.Size(300, 653);
			this.layoutControlGroup1.TextVisible = false;
			this.GeneralGroup.GroupBordersVisible = false;
			this.GeneralGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.layoutControlItem1,
			this.simpleSeparator1,
			this.layoutControlItem2,
			this.layoutControlItem3,
			this.layoutControlItem4,
			this.layoutControlItem5,
			this.layoutControlItem6,
			this.layoutControlItem7});
			this.GeneralGroup.Location = new System.Drawing.Point(0, 0);
			this.GeneralGroup.Name = "GeneralGroup";
			this.GeneralGroup.Size = new System.Drawing.Size(300, 116);
			this.titleElement1.Location = new System.Drawing.Point(12, 12);
			this.titleElement1.Name = "titleElement1";
			this.titleElement1.Size = new System.Drawing.Size(286, 13);
			this.titleElement1.TabIndex = 4;
			this.titleElement1.Title = "GENERAL";
			this.layoutControlItem1.Control = this.titleElement1;
			this.layoutControlItem1.Location = new System.Drawing.Point(0, 0);
			this.layoutControlItem1.MaxSize = new System.Drawing.Size(0, 27);
			this.layoutControlItem1.MinSize = new System.Drawing.Size(40, 27);
			this.layoutControlItem1.Name = "layoutControlItem1";
			this.layoutControlItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 12, 2);
			this.layoutControlItem1.Size = new System.Drawing.Size(300, 27);
			this.layoutControlItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem1.TextVisible = false;
			this.simpleSeparator1.AllowHotTrack = false;
			this.simpleSeparator1.Location = new System.Drawing.Point(0, 27);
			this.simpleSeparator1.Name = "simpleSeparator1";
			this.simpleSeparator1.Size = new System.Drawing.Size(300, 11);
			this.simpleSeparator1.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 9);
			this.checkEdit1.Location = new System.Drawing.Point(152, 41);
			this.checkEdit1.Name = "checkEdit1";
			this.checkEdit1.Properties.Caption = "";
			this.checkEdit1.Size = new System.Drawing.Size(136, 19);
			this.checkEdit1.StyleController = this.layoutControl1;
			this.checkEdit1.TabIndex = 6;
			this.labelControl1.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl1.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl1.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl1.Location = new System.Drawing.Point(12, 44);
			this.labelControl1.Name = "labelControl1";
			this.labelControl1.Size = new System.Drawing.Size(136, 13);
			this.labelControl1.StyleController = this.layoutControl1;
			this.labelControl1.TabIndex = 5;
			this.labelControl1.Text = "Visible:";
			this.layoutControlItem2.Control = this.labelControl1;
			this.layoutControlItem2.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem2.FillControlToClientArea = false;
			this.layoutControlItem2.Location = new System.Drawing.Point(0, 38);
			this.layoutControlItem2.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem2.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem2.Name = "layoutControlItem2";
			this.layoutControlItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem2.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem2.TextVisible = false;
			this.layoutControlItem3.Control = this.checkEdit1;
			this.layoutControlItem3.Location = new System.Drawing.Point(150, 38);
			this.layoutControlItem3.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem3.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem3.Name = "layoutControlItem3";
			this.layoutControlItem3.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem3.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem3.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem3.TextVisible = false;
			this.textEdit1.Location = new System.Drawing.Point(152, 67);
			this.textEdit1.Name = "textEdit1";
			this.textEdit1.Size = new System.Drawing.Size(136, 20);
			this.textEdit1.StyleController = this.layoutControl1;
			this.textEdit1.TabIndex = 8;
			this.labelControl2.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl2.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl2.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl2.Location = new System.Drawing.Point(12, 70);
			this.labelControl2.Name = "labelControl2";
			this.labelControl2.Size = new System.Drawing.Size(136, 13);
			this.labelControl2.StyleController = this.layoutControl1;
			this.labelControl2.TabIndex = 7;
			this.labelControl2.Text = "Name:";
			this.layoutControlItem4.Control = this.labelControl2;
			this.layoutControlItem4.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem4.FillControlToClientArea = false;
			this.layoutControlItem4.Location = new System.Drawing.Point(0, 64);
			this.layoutControlItem4.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem4.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem4.Name = "layoutControlItem4";
			this.layoutControlItem4.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem4.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem4.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem4.TextVisible = false;
			this.layoutControlItem5.Control = this.textEdit1;
			this.layoutControlItem5.Location = new System.Drawing.Point(150, 64);
			this.layoutControlItem5.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem5.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem5.Name = "layoutControlItem5";
			this.layoutControlItem5.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem5.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem5.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem5.TextVisible = false;
			this.checkEdit2.Location = new System.Drawing.Point(152, 93);
			this.checkEdit2.Name = "checkEdit2";
			this.checkEdit2.Properties.Caption = "";
			this.checkEdit2.Size = new System.Drawing.Size(136, 19);
			this.checkEdit2.StyleController = this.layoutControl1;
			this.checkEdit2.TabIndex = 10;
			this.labelControl3.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl3.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl3.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl3.Location = new System.Drawing.Point(12, 96);
			this.labelControl3.Name = "labelControl3";
			this.labelControl3.Size = new System.Drawing.Size(136, 13);
			this.labelControl3.StyleController = this.layoutControl1;
			this.labelControl3.TabIndex = 9;
			this.labelControl3.Text = "Show In Legend:";
			this.layoutControlItem6.Control = this.labelControl3;
			this.layoutControlItem6.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem6.FillControlToClientArea = false;
			this.layoutControlItem6.Location = new System.Drawing.Point(0, 90);
			this.layoutControlItem6.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem6.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem6.Name = "layoutControlItem6";
			this.layoutControlItem6.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem6.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem6.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem6.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem6.TextVisible = false;
			this.layoutControlItem7.Control = this.checkEdit2;
			this.layoutControlItem7.Location = new System.Drawing.Point(150, 90);
			this.layoutControlItem7.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem7.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem7.Name = "layoutControlItem7";
			this.layoutControlItem7.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem7.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem7.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem7.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem7.TextVisible = false;
			this.BehaviorGroup.GroupBordersVisible = false;
			this.BehaviorGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.layoutControlItem8,
			this.simpleSeparator2,
			this.layoutControlItem9,
			this.layoutControlItem10,
			this.layoutControlItem11,
			this.layoutControlItem12,
			this.layoutControlItem13,
			this.layoutControlItem14,
			this.layoutControlItem15,
			this.layoutControlItem16,
			this.layoutControlItem17,
			this.layoutControlItem18});
			this.BehaviorGroup.Location = new System.Drawing.Point(0, 116);
			this.BehaviorGroup.Name = "BehaviorGroup";
			this.BehaviorGroup.Size = new System.Drawing.Size(300, 180);
			this.titleElement2.Location = new System.Drawing.Point(12, 140);
			this.titleElement2.Name = "titleElement2";
			this.titleElement2.Size = new System.Drawing.Size(286, 13);
			this.titleElement2.TabIndex = 11;
			this.titleElement2.Title = "BEHAVIOR";
			this.layoutControlItem8.Control = this.titleElement2;
			this.layoutControlItem8.Location = new System.Drawing.Point(0, 0);
			this.layoutControlItem8.MaxSize = new System.Drawing.Size(0, 39);
			this.layoutControlItem8.MinSize = new System.Drawing.Size(40, 39);
			this.layoutControlItem8.Name = "layoutControlItem8";
			this.layoutControlItem8.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 24, 2);
			this.layoutControlItem8.Size = new System.Drawing.Size(300, 39);
			this.layoutControlItem8.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem8.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem8.TextVisible = false;
			this.simpleSeparator2.AllowHotTrack = false;
			this.simpleSeparator2.Location = new System.Drawing.Point(0, 39);
			this.simpleSeparator2.Name = "simpleSeparator2";
			this.simpleSeparator2.Size = new System.Drawing.Size(300, 11);
			this.simpleSeparator2.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 9);
			this.checkEdit3.Location = new System.Drawing.Point(152, 169);
			this.checkEdit3.Name = "checkEdit3";
			this.checkEdit3.Properties.Caption = "";
			this.checkEdit3.Size = new System.Drawing.Size(136, 19);
			this.checkEdit3.StyleController = this.layoutControl1;
			this.checkEdit3.TabIndex = 13;
			this.labelControl4.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl4.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl4.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl4.Location = new System.Drawing.Point(12, 172);
			this.labelControl4.Name = "labelControl4";
			this.labelControl4.Size = new System.Drawing.Size(136, 13);
			this.labelControl4.StyleController = this.layoutControl1;
			this.labelControl4.TabIndex = 12;
			this.labelControl4.Text = "Show Level 0:";
			this.layoutControlItem9.Control = this.labelControl4;
			this.layoutControlItem9.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem9.FillControlToClientArea = false;
			this.layoutControlItem9.Location = new System.Drawing.Point(0, 50);
			this.layoutControlItem9.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem9.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem9.Name = "layoutControlItem9";
			this.layoutControlItem9.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem9.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem9.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem9.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem9.TextVisible = false;
			this.layoutControlItem10.Control = this.checkEdit3;
			this.layoutControlItem10.Location = new System.Drawing.Point(150, 50);
			this.layoutControlItem10.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem10.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem10.Name = "layoutControlItem10";
			this.layoutControlItem10.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem10.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem10.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem10.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem10.TextVisible = false;
			this.checkEdit4.Location = new System.Drawing.Point(152, 195);
			this.checkEdit4.Name = "checkEdit4";
			this.checkEdit4.Properties.Caption = "";
			this.checkEdit4.Size = new System.Drawing.Size(136, 19);
			this.checkEdit4.StyleController = this.layoutControl1;
			this.checkEdit4.TabIndex = 15;
			this.labelControl5.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl5.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl5.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl5.Location = new System.Drawing.Point(12, 198);
			this.labelControl5.Name = "labelControl5";
			this.labelControl5.Size = new System.Drawing.Size(136, 13);
			this.labelControl5.StyleController = this.layoutControl1;
			this.labelControl5.TabIndex = 14;
			this.labelControl5.Text = "Show Level 100:";
			this.layoutControlItem11.Control = this.labelControl5;
			this.layoutControlItem11.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem11.FillControlToClientArea = false;
			this.layoutControlItem11.Location = new System.Drawing.Point(0, 76);
			this.layoutControlItem11.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem11.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem11.Name = "layoutControlItem11";
			this.layoutControlItem11.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem11.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem11.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem11.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem11.TextVisible = false;
			this.layoutControlItem12.Control = this.checkEdit4;
			this.layoutControlItem12.Location = new System.Drawing.Point(150, 76);
			this.layoutControlItem12.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem12.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem12.Name = "layoutControlItem12";
			this.layoutControlItem12.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem12.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem12.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem12.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem12.TextVisible = false;
			this.checkEdit5.Location = new System.Drawing.Point(152, 221);
			this.checkEdit5.Name = "checkEdit5";
			this.checkEdit5.Properties.Caption = "";
			this.checkEdit5.Size = new System.Drawing.Size(136, 19);
			this.checkEdit5.StyleController = this.layoutControl1;
			this.checkEdit5.TabIndex = 17;
			this.labelControl6.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl6.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl6.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl6.Location = new System.Drawing.Point(12, 224);
			this.labelControl6.Name = "labelControl6";
			this.labelControl6.Size = new System.Drawing.Size(136, 13);
			this.labelControl6.StyleController = this.layoutControl1;
			this.labelControl6.TabIndex = 16;
			this.labelControl6.Text = "Show Level 23_ 6:";
			this.layoutControlItem13.Control = this.labelControl6;
			this.layoutControlItem13.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem13.FillControlToClientArea = false;
			this.layoutControlItem13.Location = new System.Drawing.Point(0, 102);
			this.layoutControlItem13.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem13.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem13.Name = "layoutControlItem13";
			this.layoutControlItem13.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem13.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem13.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem13.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem13.TextVisible = false;
			this.layoutControlItem14.Control = this.checkEdit5;
			this.layoutControlItem14.Location = new System.Drawing.Point(150, 102);
			this.layoutControlItem14.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem14.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem14.Name = "layoutControlItem14";
			this.layoutControlItem14.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem14.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem14.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem14.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem14.TextVisible = false;
			this.checkEdit6.Location = new System.Drawing.Point(152, 247);
			this.checkEdit6.Name = "checkEdit6";
			this.checkEdit6.Properties.Caption = "";
			this.checkEdit6.Size = new System.Drawing.Size(136, 19);
			this.checkEdit6.StyleController = this.layoutControl1;
			this.checkEdit6.TabIndex = 19;
			this.labelControl7.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl7.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl7.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl7.Location = new System.Drawing.Point(12, 250);
			this.labelControl7.Name = "labelControl7";
			this.labelControl7.Size = new System.Drawing.Size(136, 13);
			this.labelControl7.StyleController = this.layoutControl1;
			this.labelControl7.TabIndex = 18;
			this.labelControl7.Text = "Show Level 76_ 4:";
			this.layoutControlItem15.Control = this.labelControl7;
			this.layoutControlItem15.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem15.FillControlToClientArea = false;
			this.layoutControlItem15.Location = new System.Drawing.Point(0, 128);
			this.layoutControlItem15.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem15.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem15.Name = "layoutControlItem15";
			this.layoutControlItem15.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem15.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem15.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem15.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem15.TextVisible = false;
			this.layoutControlItem16.Control = this.checkEdit6;
			this.layoutControlItem16.Location = new System.Drawing.Point(150, 128);
			this.layoutControlItem16.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem16.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem16.Name = "layoutControlItem16";
			this.layoutControlItem16.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem16.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem16.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem16.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem16.TextVisible = false;
			this.checkEdit7.Location = new System.Drawing.Point(152, 273);
			this.checkEdit7.Name = "checkEdit7";
			this.checkEdit7.Properties.Caption = "";
			this.checkEdit7.Size = new System.Drawing.Size(136, 19);
			this.checkEdit7.StyleController = this.layoutControl1;
			this.checkEdit7.TabIndex = 21;
			this.labelControl8.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl8.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl8.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl8.Location = new System.Drawing.Point(12, 276);
			this.labelControl8.Name = "labelControl8";
			this.labelControl8.Size = new System.Drawing.Size(136, 13);
			this.labelControl8.StyleController = this.layoutControl1;
			this.labelControl8.TabIndex = 20;
			this.labelControl8.Text = "Show Additional Levels:";
			this.layoutControlItem17.Control = this.labelControl8;
			this.layoutControlItem17.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem17.FillControlToClientArea = false;
			this.layoutControlItem17.Location = new System.Drawing.Point(0, 154);
			this.layoutControlItem17.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem17.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem17.Name = "layoutControlItem17";
			this.layoutControlItem17.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem17.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem17.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem17.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem17.TextVisible = false;
			this.layoutControlItem18.Control = this.checkEdit7;
			this.layoutControlItem18.Location = new System.Drawing.Point(150, 154);
			this.layoutControlItem18.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem18.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem18.Name = "layoutControlItem18";
			this.layoutControlItem18.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem18.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem18.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem18.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem18.TextVisible = false;
			this.layoutControlGroup2.GroupBordersVisible = false;
			this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.layoutControlItem19,
			this.simpleSeparator3,
			this.layoutControlItem20,
			this.layoutControlItem21,
			this.layoutControlItem22,
			this.layoutControlItem23});
			this.layoutControlGroup2.Location = new System.Drawing.Point(0, 296);
			this.layoutControlGroup2.Name = "layoutControlGroup2";
			this.layoutControlGroup2.Size = new System.Drawing.Size(300, 102);
			this.titleElement3.Location = new System.Drawing.Point(12, 320);
			this.titleElement3.Name = "titleElement3";
			this.titleElement3.Size = new System.Drawing.Size(286, 13);
			this.titleElement3.TabIndex = 22;
			this.titleElement3.Title = "POINT 1";
			this.layoutControlItem19.Control = this.titleElement3;
			this.layoutControlItem19.Location = new System.Drawing.Point(0, 0);
			this.layoutControlItem19.MaxSize = new System.Drawing.Size(0, 39);
			this.layoutControlItem19.MinSize = new System.Drawing.Size(40, 39);
			this.layoutControlItem19.Name = "layoutControlItem19";
			this.layoutControlItem19.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 24, 2);
			this.layoutControlItem19.Size = new System.Drawing.Size(300, 39);
			this.layoutControlItem19.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem19.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem19.TextVisible = false;
			this.simpleSeparator3.AllowHotTrack = false;
			this.simpleSeparator3.Location = new System.Drawing.Point(0, 39);
			this.simpleSeparator3.Name = "simpleSeparator3";
			this.simpleSeparator3.Size = new System.Drawing.Size(300, 11);
			this.simpleSeparator3.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 9);
			enumElementPresentation1.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation1.Name = "Value";
			enumElementPresentation1.Value = DevExpress.XtraCharts.ValueLevel.Value;
			this.comboBoxEdit1.EditValue = enumElementPresentation1;
			this.comboBoxEdit1.Location = new System.Drawing.Point(152, 349);
			this.comboBoxEdit1.Name = "comboBoxEdit1";
			this.comboBoxEdit1.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			enumElementPresentation2.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation2.Name = "Value_1";
			enumElementPresentation2.Value = DevExpress.XtraCharts.ValueLevel.Value_1;
			enumElementPresentation3.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation3.Name = "Value_2";
			enumElementPresentation3.Value = DevExpress.XtraCharts.ValueLevel.Value_2;
			enumElementPresentation4.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation4.Name = "Low";
			enumElementPresentation4.Value = DevExpress.XtraCharts.ValueLevel.Low;
			enumElementPresentation5.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation5.Name = "High";
			enumElementPresentation5.Value = DevExpress.XtraCharts.ValueLevel.High;
			enumElementPresentation6.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation6.Name = "Open";
			enumElementPresentation6.Value = DevExpress.XtraCharts.ValueLevel.Open;
			enumElementPresentation7.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation7.Name = "Close";
			enumElementPresentation7.Value = DevExpress.XtraCharts.ValueLevel.Close;
			this.comboBoxEdit1.Properties.Items.AddRange(new object[] {
			enumElementPresentation1,
			enumElementPresentation2,
			enumElementPresentation3,
			enumElementPresentation4,
			enumElementPresentation5,
			enumElementPresentation6,
			enumElementPresentation7});
			this.comboBoxEdit1.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.comboBoxEdit1.Size = new System.Drawing.Size(136, 20);
			this.comboBoxEdit1.StyleController = this.layoutControl1;
			this.comboBoxEdit1.TabIndex = 24;
			this.comboBoxEdit1.Tag = "ValueLevel";
			this.labelControl9.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl9.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl9.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl9.Location = new System.Drawing.Point(12, 352);
			this.labelControl9.Name = "labelControl9";
			this.labelControl9.Size = new System.Drawing.Size(136, 13);
			this.labelControl9.StyleController = this.layoutControl1;
			this.labelControl9.TabIndex = 23;
			this.labelControl9.Text = "Value Level:";
			this.layoutControlItem20.Control = this.labelControl9;
			this.layoutControlItem20.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem20.FillControlToClientArea = false;
			this.layoutControlItem20.Location = new System.Drawing.Point(0, 50);
			this.layoutControlItem20.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem20.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem20.Name = "layoutControlItem20";
			this.layoutControlItem20.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem20.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem20.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem20.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem20.TextVisible = false;
			this.layoutControlItem21.Control = this.comboBoxEdit1;
			this.layoutControlItem21.Location = new System.Drawing.Point(150, 50);
			this.layoutControlItem21.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem21.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem21.Name = "layoutControlItem21";
			this.layoutControlItem21.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem21.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem21.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem21.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem21.TextVisible = false;
			this.textEdit2.Location = new System.Drawing.Point(152, 375);
			this.textEdit2.Name = "textEdit2";
			this.textEdit2.Size = new System.Drawing.Size(136, 20);
			this.textEdit2.StyleController = this.layoutControl1;
			this.textEdit2.TabIndex = 26;
			this.labelControl10.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl10.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl10.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl10.Location = new System.Drawing.Point(12, 378);
			this.labelControl10.Name = "labelControl10";
			this.labelControl10.Size = new System.Drawing.Size(136, 13);
			this.labelControl10.StyleController = this.layoutControl1;
			this.labelControl10.TabIndex = 25;
			this.labelControl10.Text = "Argument:";
			this.layoutControlItem22.Control = this.labelControl10;
			this.layoutControlItem22.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem22.FillControlToClientArea = false;
			this.layoutControlItem22.Location = new System.Drawing.Point(0, 76);
			this.layoutControlItem22.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem22.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem22.Name = "layoutControlItem22";
			this.layoutControlItem22.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem22.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem22.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem22.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem22.TextVisible = false;
			this.layoutControlItem23.Control = this.textEdit2;
			this.layoutControlItem23.Location = new System.Drawing.Point(150, 76);
			this.layoutControlItem23.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem23.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem23.Name = "layoutControlItem23";
			this.layoutControlItem23.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem23.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem23.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem23.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem23.TextVisible = false;
			this.layoutControlGroup3.GroupBordersVisible = false;
			this.layoutControlGroup3.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.layoutControlItem24,
			this.simpleSeparator4,
			this.layoutControlItem25,
			this.layoutControlItem26,
			this.layoutControlItem27,
			this.layoutControlItem28});
			this.layoutControlGroup3.Location = new System.Drawing.Point(0, 398);
			this.layoutControlGroup3.Name = "layoutControlGroup3";
			this.layoutControlGroup3.Size = new System.Drawing.Size(300, 102);
			this.titleElement4.Location = new System.Drawing.Point(12, 422);
			this.titleElement4.Name = "titleElement4";
			this.titleElement4.Size = new System.Drawing.Size(286, 13);
			this.titleElement4.TabIndex = 27;
			this.titleElement4.Title = "POINT 2";
			this.layoutControlItem24.Control = this.titleElement4;
			this.layoutControlItem24.Location = new System.Drawing.Point(0, 0);
			this.layoutControlItem24.MaxSize = new System.Drawing.Size(0, 39);
			this.layoutControlItem24.MinSize = new System.Drawing.Size(40, 39);
			this.layoutControlItem24.Name = "layoutControlItem24";
			this.layoutControlItem24.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 24, 2);
			this.layoutControlItem24.Size = new System.Drawing.Size(300, 39);
			this.layoutControlItem24.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem24.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem24.TextVisible = false;
			this.simpleSeparator4.AllowHotTrack = false;
			this.simpleSeparator4.Location = new System.Drawing.Point(0, 39);
			this.simpleSeparator4.Name = "simpleSeparator4";
			this.simpleSeparator4.Size = new System.Drawing.Size(300, 11);
			this.simpleSeparator4.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 9);
			enumElementPresentation8.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation8.Name = "Value";
			enumElementPresentation8.Value = DevExpress.XtraCharts.ValueLevel.Value;
			this.comboBoxEdit2.EditValue = enumElementPresentation8;
			this.comboBoxEdit2.Location = new System.Drawing.Point(152, 451);
			this.comboBoxEdit2.Name = "comboBoxEdit2";
			this.comboBoxEdit2.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
			new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			enumElementPresentation9.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation9.Name = "Value_1";
			enumElementPresentation9.Value = DevExpress.XtraCharts.ValueLevel.Value_1;
			enumElementPresentation10.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation10.Name = "Value_2";
			enumElementPresentation10.Value = DevExpress.XtraCharts.ValueLevel.Value_2;
			enumElementPresentation11.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation11.Name = "Low";
			enumElementPresentation11.Value = DevExpress.XtraCharts.ValueLevel.Low;
			enumElementPresentation12.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation12.Name = "High";
			enumElementPresentation12.Value = DevExpress.XtraCharts.ValueLevel.High;
			enumElementPresentation13.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation13.Name = "Open";
			enumElementPresentation13.Value = DevExpress.XtraCharts.ValueLevel.Open;
			enumElementPresentation14.EnamType = typeof(DevExpress.XtraCharts.ValueLevel);
			enumElementPresentation14.Name = "Close";
			enumElementPresentation14.Value = DevExpress.XtraCharts.ValueLevel.Close;
			this.comboBoxEdit2.Properties.Items.AddRange(new object[] {
			enumElementPresentation8,
			enumElementPresentation9,
			enumElementPresentation10,
			enumElementPresentation11,
			enumElementPresentation12,
			enumElementPresentation13,
			enumElementPresentation14});
			this.comboBoxEdit2.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.comboBoxEdit2.Size = new System.Drawing.Size(136, 20);
			this.comboBoxEdit2.StyleController = this.layoutControl1;
			this.comboBoxEdit2.TabIndex = 29;
			this.comboBoxEdit2.Tag = "ValueLevel";
			this.labelControl11.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl11.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl11.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl11.Location = new System.Drawing.Point(12, 454);
			this.labelControl11.Name = "labelControl11";
			this.labelControl11.Size = new System.Drawing.Size(136, 13);
			this.labelControl11.StyleController = this.layoutControl1;
			this.labelControl11.TabIndex = 28;
			this.labelControl11.Text = "Value Level:";
			this.layoutControlItem25.Control = this.labelControl11;
			this.layoutControlItem25.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem25.FillControlToClientArea = false;
			this.layoutControlItem25.Location = new System.Drawing.Point(0, 50);
			this.layoutControlItem25.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem25.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem25.Name = "layoutControlItem25";
			this.layoutControlItem25.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem25.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem25.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem25.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem25.TextVisible = false;
			this.layoutControlItem26.Control = this.comboBoxEdit2;
			this.layoutControlItem26.Location = new System.Drawing.Point(150, 50);
			this.layoutControlItem26.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem26.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem26.Name = "layoutControlItem26";
			this.layoutControlItem26.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem26.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem26.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem26.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem26.TextVisible = false;
			this.textEdit3.Location = new System.Drawing.Point(152, 477);
			this.textEdit3.Name = "textEdit3";
			this.textEdit3.Size = new System.Drawing.Size(136, 20);
			this.textEdit3.StyleController = this.layoutControl1;
			this.textEdit3.TabIndex = 31;
			this.labelControl12.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl12.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl12.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl12.Location = new System.Drawing.Point(12, 480);
			this.labelControl12.Name = "labelControl12";
			this.labelControl12.Size = new System.Drawing.Size(136, 13);
			this.labelControl12.StyleController = this.layoutControl1;
			this.labelControl12.TabIndex = 30;
			this.labelControl12.Text = "Argument:";
			this.layoutControlItem27.Control = this.labelControl12;
			this.layoutControlItem27.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem27.FillControlToClientArea = false;
			this.layoutControlItem27.Location = new System.Drawing.Point(0, 76);
			this.layoutControlItem27.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem27.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem27.Name = "layoutControlItem27";
			this.layoutControlItem27.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem27.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem27.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem27.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem27.TextVisible = false;
			this.layoutControlItem28.Control = this.textEdit3;
			this.layoutControlItem28.Location = new System.Drawing.Point(150, 76);
			this.layoutControlItem28.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem28.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem28.Name = "layoutControlItem28";
			this.layoutControlItem28.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem28.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem28.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem28.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem28.TextVisible = false;
			this.LabelGroup.GroupBordersVisible = false;
			this.LabelGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
			this.layoutControlItem29,
			this.simpleSeparator5,
			this.layoutControlItem30,
			this.layoutControlItem31,
			this.layoutControlItem32,
			this.layoutControlItem33,
			this.layoutControlItem34,
			this.layoutControlItem35});
			this.LabelGroup.Location = new System.Drawing.Point(0, 500);
			this.LabelGroup.Name = "LabelGroup";
			this.LabelGroup.Size = new System.Drawing.Size(300, 128);
			this.titleElement5.Location = new System.Drawing.Point(12, 524);
			this.titleElement5.Name = "titleElement5";
			this.titleElement5.Size = new System.Drawing.Size(286, 13);
			this.titleElement5.TabIndex = 32;
			this.titleElement5.Title = "LABEL";
			this.layoutControlItem29.Control = this.titleElement5;
			this.layoutControlItem29.Location = new System.Drawing.Point(0, 0);
			this.layoutControlItem29.MaxSize = new System.Drawing.Size(0, 39);
			this.layoutControlItem29.MinSize = new System.Drawing.Size(40, 39);
			this.layoutControlItem29.Name = "layoutControlItem29";
			this.layoutControlItem29.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 24, 2);
			this.layoutControlItem29.Size = new System.Drawing.Size(300, 39);
			this.layoutControlItem29.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem29.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem29.TextVisible = false;
			this.simpleSeparator5.AllowHotTrack = false;
			this.simpleSeparator5.Location = new System.Drawing.Point(0, 39);
			this.simpleSeparator5.Name = "simpleSeparator5";
			this.simpleSeparator5.Size = new System.Drawing.Size(300, 11);
			this.simpleSeparator5.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 9);
			this.checkEdit8.Location = new System.Drawing.Point(152, 553);
			this.checkEdit8.Name = "checkEdit8";
			this.checkEdit8.Properties.Caption = "";
			this.checkEdit8.Size = new System.Drawing.Size(136, 19);
			this.checkEdit8.StyleController = this.layoutControl1;
			this.checkEdit8.TabIndex = 34;
			this.labelControl13.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl13.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl13.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl13.Location = new System.Drawing.Point(12, 556);
			this.labelControl13.Name = "labelControl13";
			this.labelControl13.Size = new System.Drawing.Size(136, 13);
			this.labelControl13.StyleController = this.layoutControl1;
			this.labelControl13.TabIndex = 33;
			this.labelControl13.Text = "Visible:";
			this.layoutControlItem30.Control = this.labelControl13;
			this.layoutControlItem30.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem30.FillControlToClientArea = false;
			this.layoutControlItem30.Location = new System.Drawing.Point(0, 50);
			this.layoutControlItem30.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem30.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem30.Name = "layoutControlItem30";
			this.layoutControlItem30.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem30.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem30.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem30.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem30.TextVisible = false;
			this.layoutControlItem31.Control = this.checkEdit8;
			this.layoutControlItem31.Location = new System.Drawing.Point(150, 50);
			this.layoutControlItem31.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem31.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem31.Name = "layoutControlItem31";
			this.layoutControlItem31.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem31.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem31.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem31.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem31.TextVisible = false;
			this.colorPickEdit1.EditValue = System.Drawing.Color.Empty;
			this.colorPickEdit1.Location = new System.Drawing.Point(152, 579);
			this.colorPickEdit1.Name = "colorPickEdit1";
			this.colorPickEdit1.Properties.AutomaticColor = System.Drawing.Color.Empty;
			this.colorPickEdit1.Size = new System.Drawing.Size(136, 20);
			this.colorPickEdit1.StyleController = this.layoutControl1;
			this.colorPickEdit1.TabIndex = 36;
			this.labelControl14.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl14.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl14.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl14.Location = new System.Drawing.Point(12, 582);
			this.labelControl14.Name = "labelControl14";
			this.labelControl14.Size = new System.Drawing.Size(136, 13);
			this.labelControl14.StyleController = this.layoutControl1;
			this.labelControl14.TabIndex = 35;
			this.labelControl14.Text = "Text Color:";
			this.layoutControlItem32.Control = this.labelControl14;
			this.layoutControlItem32.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem32.FillControlToClientArea = false;
			this.layoutControlItem32.Location = new System.Drawing.Point(0, 76);
			this.layoutControlItem32.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem32.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem32.Name = "layoutControlItem32";
			this.layoutControlItem32.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem32.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem32.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem32.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem32.TextVisible = false;
			this.layoutControlItem33.Control = this.colorPickEdit1;
			this.layoutControlItem33.Location = new System.Drawing.Point(150, 76);
			this.layoutControlItem33.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem33.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem33.Name = "layoutControlItem33";
			this.layoutControlItem33.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem33.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem33.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem33.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem33.TextVisible = false;
			this.colorPickEdit2.EditValue = System.Drawing.Color.Empty;
			this.colorPickEdit2.Location = new System.Drawing.Point(152, 605);
			this.colorPickEdit2.Name = "colorPickEdit2";
			this.colorPickEdit2.Properties.AutomaticColor = System.Drawing.Color.Empty;
			this.colorPickEdit2.Size = new System.Drawing.Size(136, 20);
			this.colorPickEdit2.StyleController = this.layoutControl1;
			this.colorPickEdit2.TabIndex = 38;
			this.labelControl15.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
			this.labelControl15.Appearance.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
			this.labelControl15.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.None;
			this.labelControl15.Location = new System.Drawing.Point(12, 608);
			this.labelControl15.Name = "labelControl15";
			this.labelControl15.Size = new System.Drawing.Size(136, 13);
			this.labelControl15.StyleController = this.layoutControl1;
			this.labelControl15.TabIndex = 37;
			this.labelControl15.Text = "Base Level Text Color:";
			this.layoutControlItem34.Control = this.labelControl15;
			this.layoutControlItem34.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
			this.layoutControlItem34.FillControlToClientArea = false;
			this.layoutControlItem34.Location = new System.Drawing.Point(0, 102);
			this.layoutControlItem34.MaxSize = new System.Drawing.Size(150, 0);
			this.layoutControlItem34.MinSize = new System.Drawing.Size(150, 1);
			this.layoutControlItem34.Name = "layoutControlItem34";
			this.layoutControlItem34.Padding = new DevExpress.XtraLayout.Utils.Padding(12, 2, 3, 3);
			this.layoutControlItem34.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem34.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem34.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem34.TextVisible = false;
			this.layoutControlItem35.Control = this.colorPickEdit2;
			this.layoutControlItem35.Location = new System.Drawing.Point(150, 102);
			this.layoutControlItem35.MaxSize = new System.Drawing.Size(0, 26);
			this.layoutControlItem35.MinSize = new System.Drawing.Size(150, 26);
			this.layoutControlItem35.Name = "layoutControlItem35";
			this.layoutControlItem35.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 12, 3, 3);
			this.layoutControlItem35.Size = new System.Drawing.Size(150, 26);
			this.layoutControlItem35.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.layoutControlItem35.TextSize = new System.Drawing.Size(0, 0);
			this.layoutControlItem35.TextVisible = false;
			this.emptySpaceItem1.AllowHotTrack = false;
			this.emptySpaceItem1.Location = new System.Drawing.Point(0, 628);
			this.emptySpaceItem1.Name = "emptySpaceItem1";
			this.emptySpaceItem1.Size = new System.Drawing.Size(300, 25);
			this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.layoutControl1);
			this.Name = "FibonacciIndicatorOptionsControl";
			propertyLink1.Editor = this.colorPickEdit2;
			propertyLink1.PropertyFullName = new string[] {
		"Label",
		"BaseLevelTextColor"};
			propertyLink1.PropertyType = typeof(System.Drawing.Color);
			propertyLink1.TitleControl = this.labelControl15;
			propertyLink2.Editor = this.checkEdit8;
			propertyLink2.PropertyFullName = new string[] {
		"Label",
		"Visible"};
			propertyLink2.PropertyType = typeof(bool);
			propertyLink2.TitleControl = this.labelControl13;
			propertyLink3.Editor = this.colorPickEdit1;
			propertyLink3.PropertyFullName = new string[] {
		"Label",
		"TextColor"};
			propertyLink3.PropertyType = typeof(System.Drawing.Color);
			propertyLink3.TitleControl = this.labelControl14;
			propertyLink4.Editor = this.checkEdit3;
			propertyLink4.PropertyName = "ShowLevel0";
			propertyLink4.PropertyType = typeof(bool);
			propertyLink4.TitleControl = this.labelControl4;
			propertyLink5.Editor = this.checkEdit4;
			propertyLink5.PropertyName = "ShowLevel100";
			propertyLink5.PropertyType = typeof(bool);
			propertyLink5.TitleControl = this.labelControl5;
			propertyLink6.Editor = this.checkEdit5;
			propertyLink6.PropertyName = "ShowLevel23_6";
			propertyLink6.PropertyType = typeof(bool);
			propertyLink6.TitleControl = this.labelControl6;
			propertyLink7.Editor = this.checkEdit6;
			propertyLink7.PropertyName = "ShowLevel76_4";
			propertyLink7.PropertyType = typeof(bool);
			propertyLink7.TitleControl = this.labelControl7;
			propertyLink8.Editor = this.checkEdit7;
			propertyLink8.PropertyName = "ShowAdditionalLevels";
			propertyLink8.PropertyType = typeof(bool);
			propertyLink8.TitleControl = this.labelControl8;
			propertyLink9.Editor = this.comboBoxEdit1;
			propertyLink9.PropertyFullName = new string[] {
		"Point1",
		"ValueLevel"};
			propertyLink9.PropertyType = typeof(DevExpress.XtraCharts.ValueLevel);
			propertyLink9.TitleControl = this.labelControl9;
			propertyLink10.Editor = this.textEdit2;
			propertyLink10.PropertyFullName = new string[] {
		"Point1",
		"Argument"};
			propertyLink10.PropertyType = typeof(object);
			propertyLink10.TitleControl = this.labelControl10;
			propertyLink11.Editor = this.comboBoxEdit2;
			propertyLink11.PropertyFullName = new string[] {
		"Point2",
		"ValueLevel"};
			propertyLink11.PropertyType = typeof(DevExpress.XtraCharts.ValueLevel);
			propertyLink11.TitleControl = this.labelControl11;
			propertyLink12.Editor = this.textEdit3;
			propertyLink12.PropertyFullName = new string[] {
		"Point2",
		"Argument"};
			propertyLink12.PropertyType = typeof(object);
			propertyLink12.TitleControl = this.labelControl12;
			propertyLink13.Editor = this.checkEdit1;
			propertyLink13.PropertyName = "Visible";
			propertyLink13.PropertyType = typeof(bool);
			propertyLink13.TitleControl = this.labelControl1;
			propertyLink14.Editor = this.textEdit1;
			propertyLink14.PropertyName = "Name";
			propertyLink14.PropertyType = typeof(string);
			propertyLink14.TitleControl = this.labelControl2;
			propertyLink15.Editor = this.checkEdit2;
			propertyLink15.PropertyName = "ShowInLegend";
			propertyLink15.PropertyType = typeof(bool);
			propertyLink15.TitleControl = this.labelControl3;
			this.PropertyLinks.Add(propertyLink1);
			this.PropertyLinks.Add(propertyLink2);
			this.PropertyLinks.Add(propertyLink3);
			this.PropertyLinks.Add(propertyLink4);
			this.PropertyLinks.Add(propertyLink5);
			this.PropertyLinks.Add(propertyLink6);
			this.PropertyLinks.Add(propertyLink7);
			this.PropertyLinks.Add(propertyLink8);
			this.PropertyLinks.Add(propertyLink9);
			this.PropertyLinks.Add(propertyLink10);
			this.PropertyLinks.Add(propertyLink11);
			this.PropertyLinks.Add(propertyLink12);
			this.PropertyLinks.Add(propertyLink13);
			this.PropertyLinks.Add(propertyLink14);
			this.PropertyLinks.Add(propertyLink15);
			this.Size = new System.Drawing.Size(300, 653);
			this.Titles.Add(this.titleElement1);
			this.Titles.Add(this.titleElement2);
			this.Titles.Add(this.titleElement3);
			this.Titles.Add(this.titleElement4);
			this.Titles.Add(this.titleElement5);
			((System.ComponentModel.ISupportInitialize)(this.uiOptionsBuilder1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
			this.layoutControl1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.GeneralGroup)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit2.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BehaviorGroup)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit3.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit4.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit5.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit6.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit7.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit2.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.comboBoxEdit2.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem26)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.textEdit3.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem27)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem28)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.LabelGroup)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem29)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.simpleSeparator5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.checkEdit8.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem30)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem31)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.colorPickEdit1.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem32)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem33)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.colorPickEdit2.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem34)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem35)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
			this.ResumeLayout(false);
		}
		#endregion
		private UIOptionsBuilder uiOptionsBuilder1;
		private XtraLayout.LayoutControl layoutControl1;
		private TitleElement titleElement1;
		private XtraEditors.LabelControl labelControl1;
		private XtraEditors.CheckEdit checkEdit1;
		private XtraEditors.LabelControl labelControl2;
		private XtraEditors.TextEdit textEdit1;
		private XtraEditors.LabelControl labelControl3;
		private XtraEditors.CheckEdit checkEdit2;
		private TitleElement titleElement2;
		private XtraEditors.LabelControl labelControl4;
		private XtraEditors.CheckEdit checkEdit3;
		private XtraEditors.LabelControl labelControl5;
		private XtraEditors.CheckEdit checkEdit4;
		private XtraEditors.LabelControl labelControl6;
		private XtraEditors.CheckEdit checkEdit5;
		private XtraEditors.LabelControl labelControl7;
		private XtraEditors.CheckEdit checkEdit6;
		private XtraEditors.LabelControl labelControl8;
		private XtraEditors.CheckEdit checkEdit7;
		private TitleElement titleElement3;
		private XtraEditors.LabelControl labelControl9;
		private XtraEditors.ComboBoxEdit comboBoxEdit1;
		private XtraEditors.LabelControl labelControl10;
		private XtraEditors.TextEdit textEdit2;
		private TitleElement titleElement4;
		private XtraEditors.LabelControl labelControl11;
		private XtraEditors.ComboBoxEdit comboBoxEdit2;
		private XtraEditors.LabelControl labelControl12;
		private XtraEditors.TextEdit textEdit3;
		private TitleElement titleElement5;
		private XtraEditors.LabelControl labelControl13;
		private XtraEditors.CheckEdit checkEdit8;
		private XtraEditors.LabelControl labelControl14;
		private XtraEditors.ColorPickEdit colorPickEdit1;
		private XtraEditors.LabelControl labelControl15;
		private XtraEditors.ColorPickEdit colorPickEdit2;
		private XtraLayout.LayoutControlGroup layoutControlGroup1;
		private XtraLayout.LayoutControlGroup GeneralGroup;
		private XtraLayout.LayoutControlItem layoutControlItem1;
		private XtraLayout.SimpleSeparator simpleSeparator1;
		private XtraLayout.LayoutControlItem layoutControlItem2;
		private XtraLayout.LayoutControlItem layoutControlItem3;
		private XtraLayout.LayoutControlItem layoutControlItem4;
		private XtraLayout.LayoutControlItem layoutControlItem5;
		private XtraLayout.LayoutControlItem layoutControlItem6;
		private XtraLayout.LayoutControlItem layoutControlItem7;
		private XtraLayout.LayoutControlGroup BehaviorGroup;
		private XtraLayout.LayoutControlItem layoutControlItem8;
		private XtraLayout.SimpleSeparator simpleSeparator2;
		private XtraLayout.LayoutControlItem layoutControlItem9;
		private XtraLayout.LayoutControlItem layoutControlItem10;
		private XtraLayout.LayoutControlItem layoutControlItem11;
		private XtraLayout.LayoutControlItem layoutControlItem12;
		private XtraLayout.LayoutControlItem layoutControlItem13;
		private XtraLayout.LayoutControlItem layoutControlItem14;
		private XtraLayout.LayoutControlItem layoutControlItem15;
		private XtraLayout.LayoutControlItem layoutControlItem16;
		private XtraLayout.LayoutControlItem layoutControlItem17;
		private XtraLayout.LayoutControlItem layoutControlItem18;
		private XtraLayout.LayoutControlGroup layoutControlGroup2;
		private XtraLayout.LayoutControlItem layoutControlItem19;
		private XtraLayout.SimpleSeparator simpleSeparator3;
		private XtraLayout.LayoutControlItem layoutControlItem20;
		private XtraLayout.LayoutControlItem layoutControlItem21;
		private XtraLayout.LayoutControlItem layoutControlItem22;
		private XtraLayout.LayoutControlItem layoutControlItem23;
		private XtraLayout.LayoutControlGroup layoutControlGroup3;
		private XtraLayout.LayoutControlItem layoutControlItem24;
		private XtraLayout.SimpleSeparator simpleSeparator4;
		private XtraLayout.LayoutControlItem layoutControlItem25;
		private XtraLayout.LayoutControlItem layoutControlItem26;
		private XtraLayout.LayoutControlItem layoutControlItem27;
		private XtraLayout.LayoutControlItem layoutControlItem28;
		private XtraLayout.LayoutControlGroup LabelGroup;
		private XtraLayout.LayoutControlItem layoutControlItem29;
		private XtraLayout.SimpleSeparator simpleSeparator5;
		private XtraLayout.LayoutControlItem layoutControlItem30;
		private XtraLayout.LayoutControlItem layoutControlItem31;
		private XtraLayout.LayoutControlItem layoutControlItem32;
		private XtraLayout.LayoutControlItem layoutControlItem33;
		private XtraLayout.LayoutControlItem layoutControlItem34;
		private XtraLayout.LayoutControlItem layoutControlItem35;
		private XtraLayout.EmptySpaceItem emptySpaceItem1;
	}
}
