#region Copyright (c) 2000-2015 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2015 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2015 Developer Express Inc.

using System;
using DevExpress.Web;
using DevExpress.Utils;
namespace DevExpress.Web.Mvc {
	public class ImageSliderSettings : SettingsBase {
		public ImageSliderSettings() {
			Items = new MVCxImageSliderItemCollection();
			SettingsBehavior = new ImageSliderBehaviorSettings(null);
			SettingsImageArea = new ImageSliderImageAreaSettings(null);
			SettingsNavigationBar = new ImageSliderNavigationBarSettings(null);
			SettingsSlideShow = new ImageSliderSlideShowSettings(null);
			SettingsAutoGeneratedImages = new ImageSliderAutoGeneratedImagesSettings(null);
			KeyboardSupport = true;
			ShowImageArea = true;
			ShowNavigationBar = true;
		}
		public int ActiveItemIndex { get; set; }
		[Obsolete("Use the SettingsAutoGeneratedImages.ImageCacheFolder property instead.")]
		public string BinaryImageCacheFolder {
			get { return SettingsAutoGeneratedImages.ImageCacheFolder; }
			set { SettingsAutoGeneratedImages.ImageCacheFolder = value; }
		}
		public bool KeyboardSupport { get; set; }
		public bool SeoFriendly { get; set; }
		public bool ShowImageArea { get; set; }
		public bool ShowNavigationBar { get; set; }
		public string Target { get; set; }
		public ImageSliderImages Images { get { return (ImageSliderImages)ImagesInternal; } }
		public ImageSliderStyles Styles { get { return (ImageSliderStyles)StylesInternal; } }
		public ImageSliderClientSideEvents ClientSideEvents { get { return (ImageSliderClientSideEvents)ClientSideEventsInternal; } }
		public ImageSliderBehaviorSettings SettingsBehavior { get; private set; }
		public ImageSliderImageAreaSettings SettingsImageArea { get; private set; }
		public ImageSliderNavigationBarSettings SettingsNavigationBar { get; private set; }
		public ImageSliderSlideShowSettings SettingsSlideShow { get; private set; }
		public ImageSliderAutoGeneratedImagesSettings SettingsAutoGeneratedImages { get; private set; }
		public string NameField { get; set; }
		public string TextField { get; set; }
		public string ImageUrlField { get; set; }
		public string ImageUrlFormatString { get; set; }
		public string ThumbnailUrlField { get; set; }
		public string ThumbnailUrlFormatString { get; set; }
		public string NavigateUrlField { get; set; }
		public string NavigateUrlFormatString { get; set; }
		public string ImageContentBytesField { get; set; }
		public string ThumbnailContentBytesField { get; set; }
		public MVCxImageSliderItemCollection Items { get; private set; }
		public DefaultBoolean RightToLeft { get { return RightToLeftInternal; } set { RightToLeftInternal = value; } }
		public EventHandler DataBound { get; set; }
		public ImageSliderItemEventHandler ItemDataBound { get; set; }
		protected internal string ItemTemplateContent { get; set; }
		protected internal Action<ImageSliderItemTemplateContainer> ItemTemplateContentMethod { get; set; }
		protected internal string ItemTextTemplateContent { get; set; }
		protected internal Action<ImageSliderItemTemplateContainer> ItemTextTemplateContentMethod { get; set; }
		protected internal string ItemThumbnailTemplateContent { get; set; }
		protected internal Action<ImageSliderItemTemplateContainer> ItemThumbnailTemplateContentMethod { get; set; }
		public void SetItemTemplateContent(Action<ImageSliderItemTemplateContainer> contentMethod) {
			ItemTemplateContentMethod = contentMethod;
		}
		public void SetItemTemplateContent(string content) {
			ItemTemplateContent = content;
		}
		public void SetItemTextTemplateContent(Action<ImageSliderItemTemplateContainer> contentMethod) {
			ItemTextTemplateContentMethod = contentMethod;
		}
		public void SetItemTextTemplateContent(string content) {
			ItemTextTemplateContent = content;
		}
		public void SetItemThumbnailTemplateContent(Action<ImageSliderItemTemplateContainer> contentMethod) {
			ItemThumbnailTemplateContentMethod = contentMethod;
		}
		public void SetItemThumbnailTemplateContent(string content) {
			ItemThumbnailTemplateContent = content;
		}
		protected override ClientSideEventsBase CreateClientSideEvents() {
			return new ImageSliderClientSideEvents();
		}
		protected override ImagesBase CreateImages() {
			return new ImageSliderImages(null);
		}
		protected override StylesBase CreateStyles() {
			return new ImageSliderStyles(null);
		}
	}
}
